### PR TITLE
consensus, accrual: Fix newbie accrual

### LINKED ISSUE #1999: Pending rewards reset in the morning
Hello

Since I've switched to solo mining several days (a week -ish?) ago my pending rewards seem to reset sometime during the night/early morning every day.

my CPID and beacon etc are ok: http://main.gridcoinstats.eu/cpid/cbc3f2f4e582dff425f355e0c2767ef9 at 41 mag right now.

I have not staked yet since going solo, have almost 8k GRC.
```
$ gridcoinresearchd explainmagnitude
...
  {
    "project": "total",
    "rac": 38701.885535,
    "magnitude": 41.5
  }
```

yet every morning I start from 0 pending rewards:
```
$ gridcoinresearchd getmininginfo
{
  "blocks": 2142052,
  "stakeweight": {
    "minimum": 180,
    "maximum": 462560,
    "combined": 635816,
    "valuesum": 7947.760915350001,
    "legacy": 7947.76091535
  },
  "netstakeweight": 12071730451.02193,
  "netstakingGRCvalue": 150896630.6377741,
  "staking": true,
  "mining-error": "",
  "time-to-stake_days": 19.77722222222222,
  "expectedtime": 1708752,
  "mining-version": 11,
  "mining-created": 0,
  "mining-accepted": 0,
  "mining-kernels-found": 0,
  "stake-splitting": {
    "stake-splitting-enabled": false
  },
  "side-staking": {
    "side-staking-enabled": false
  },
  "difficulty": {
    "current": 14.51159797492793,
    "target": 16.43763784202704,
    "last-search-interval": 1610443536
  },
  "errors": "",
  "pooledtx": 0,
  "testnet": false,
  "CPID": "cbc3f2f4e582dff425f355e0c2767ef9",
  "Magnitude Unit": 0.25,
  "BoincRewardPending": 1.51824652,
  "researcher_status": "Eligible for Research Rewards",
  "current_poll": "No current polls"
}
...
$ gridcoinresearchd beaconstatus
{
  "active": [
    {
      "cpid": "cbc3f2f4e582dff425f355e0c2767ef9",
      "active": true,
      "pending": false,
      "expired": false,
      "renewable": false,
...
      "private_key_available": true,
      "magnitude": 42,
      "is_mine": true
    }
  ],
  "pending": [
  ]
}
```

could it be related to not staking yet? Or is it just a visual glitch? I did not see anything interesting in debug.log nor scraper (which is empty?)

Thanks, Ashley

### PR DESCRIPTION
**Pull request by jamescowens**
This PR implements CAmount GetNewbieSuperblockAccrualCorrection(Cpid cpid) and is the fix for the newbie accrual bug.

This PR closes #1999.

### CODE REVIEW

File: src/gridcoin/beacon.cpp [hunk 1]
```diff
@@ -62,7 +65,12 @@ bool TryRenewal(BeaconRegistry::BeaconMap& beacons, const BeaconPayload& payload
         return false;
     }
 
+    // Insert current beacon into historical map.
+    historical_beacons.emplace(std::make_pair(ctx_hash, current_beacon));
```
Comment (denravonska) [inline src/gridcoin/beacon.cpp:69]: I haven't dug into where this is used, but don't you want to insert the historical beacon after the timestamp and hash are assigned?

Edit: Nvm, the hash is the key.

Comment (jamescowens) [reply src/gridcoin/beacon.cpp:69]: See the latest push....

**Comment by jamescowens** [comment]
Ok. This is getting close I think. You have to test this against mainnet, because the only CPID's that fail are on mainnet right now.

If you run this with a test node against mainnet and delete the accrual directory beforehand to force rebuilding the accruals, then run the auditsnapshot accruals, you get the following:

[accrual_mismatches_20210124_after_accrual_rebuild.log](https://github.com/gridcoin-community/Gridcoin-Research/files/5863372/accrual_mismatches_20210124_after_accrual_rebuild.log)

and 

[TallySuperblockAccrual_debug_out_20210124.log](https://github.com/gridcoin-community/Gridcoin-Research/files/5863373/TallySuperblockAccrual_debug_out_20210124.log)

This is based on having the corrections actually replay at the first superblock higher than the original newbie fix height of 2104000.

**Comment by jamescowens** [comment]
When you move the

inline int GetNewbieSnapshotFixHeight()
{
    // This was the original hard fork point for the newbie accrual fix that didn't work.
    // return fTestNet ? 1393000 : 2104000;
    return fTestNet ? 1393000 : 2152000;
}

to a different height, in this case right before the latest superblock, the corrections grow of course, because they are being made later, but the final accruals on the current snapshot still match. See

[accrual_mismatches_20210124_after_accrual_rebuild_3.log](https://github.com/gridcoin-community/Gridcoin-Research/files/5863399/accrual_mismatches_20210124_after_accrual_rebuild_3.log)

and

[TallySuperblockAccrual_debug_out_20210124_3.log](https://github.com/gridcoin-community/Gridcoin-Research/files/5863400/TallySuperblockAccrual_debug_out_20210124_3.log)

So I think this is ready for a initial review.

**Comment by jamescowens** [comment]
This is the current state of mismatches when the mainnet fix height is set to max (i.e. beyond the current height) so that it is not activated...

[accrual_mismatches_20210124_after_accrual_rebuild_fork_height_reset_to_max.log](https://github.com/gridcoin-community/Gridcoin-Research/files/5863425/accrual_mismatches_20210124_after_accrual_rebuild_fork_height_reset_to_max.log)

There are 89 mismatches, of which 88 are last period only accruals (i.e. due to the failure to record an accrual account for a newly activated CPID).

**Comment by jamescowens** [comment]
I am leaving the commented out code in there for right now for reference purposes. This will be removed post review. The height for the mainnet mandatory will most likely be set in a separate PR depending on the timing of testing and exchange and community notification.

**Review by div72 — APPROVED** [review]

File: src/rpc/mining.cpp [hunk 2]
```diff
@@ -441,15 +460,20 @@ UniValue auditsnapshotaccrual(const UniValue& params, bool fHelp)
 
     int64_t period = tally_accrual_period("tip", 0, pindex_low->nTime, now, 0);
 
+    result.pushKV("cpid", cpid->ToString());
```
[the remark this answers is not in the document]
Comment (jamescowens) [reply src/rpc/mining.cpp:463]: I might rearrange things a bit, but not right now, because yes, they are not laid out optimally, but I am using the output for analysis, and I don't want to change the analytical parts downstream. I will some cleanup in a subsequent PR. I am doing test syncs from zero to make sure this didn't break anything before merging this.

**Comment by jamescowens** [comment]
I discovered almost simultaneously in sync from zero test with this PR (prior to the last push) and being notified on Slack, that some newbie CPID's had managed to get non-truncated accruals staked onto the blockchain after the original newbie height fix at 2104000. This has necessitated further changes to the PR: See the extensive comments in GetNewbieSuperblockAccrualCorrection, reposted here:

This function was moved from the anonymous namespace and private, to public and made static, because it has
to be called from ClaimValidator::CheckResearchReward() directly too. Why?

The broken original newbie fix was CONDITIONAL. The initialization in Tally::Initialize was broken and would
never activate, yet the alternate path through AcceptBlock AddToBlockIndex could actually set the original
global boolean if syncing and passing through the trigger block height (now memorialized in
GetOrigNewbieSnapshotFixHeight()). This led to the following fracture:

Nodes that synced from zero through the original newbie trigger block height would have the global boolean set to
activate the fix. On the other hand as time (height passes) after the trigger height, nodes would get restarted
and are already beyond that height, so their boolean would be set to zero. So if a node that hadn't been restarted
is a newbie and actually stakes with the fix enabled, it will have an accrual account on that node and report
the correct historical accrual to be paid, rather than the newbie truncated value prior to the fix. There are
actually some blocks that made it on the chain that way.

Rather than leave the original broken global boolean flag for the original newbie fix, which doesn't actually work
and would be confusing to code maintainers in the future, I decided to implement this correction function.

The function has two current uses:

1. It is used in TallySuperblockAccrual() above to compute the "catch-up" correction on the acceptance of a staked
   superblock for any CPIDs that were subject to the newbie bug and have historical accruals that need to be
   included. This is activated at GetNewbieSnapshotFixHeight(), and will cause this function to be used to apply
   the corrections to any CPID's that do not have an accrual account at that height.

2. It is used in ConnectBlock (the ClaimValidator::CheckResearchReward()) to conditionally apply the accrual
   correction if the claimed value by the block fails the original CheckReward. If the original computed reward
   plus the correction equals the claimed reward, then the block is passed with a warning. This enables any
   node to conditionally validate a block that was staked with the accrual correction active, even if the
   receiving node does not have the NEW correction active.

This function computes the accrual that should have been recorded in the periods between the first superblock that
posted that validated the original verified beacon in a chain of renewals and the current superblock. This uses a
calculation very similar to the calculation in the auditsnapshotaccrual RPC function.

The reason I go through the trouble to limit the lookback scope to the chain of beacon renewals (including the
original advertisement that was validated) is to limit the lookback for this function, and it is proper to limit
the scope of the lookback accrual correction to be done only over the time-frame that is covered by an unbroken
beacon chain.

This function should be very light after the new newbie fix is crossed by the network (after the application of
the accrual corrections for all the CPID's in the first superblock past that height), since the AccrualDelta with
no additional corrections will be necessary (i.e. this function will generate no periods).

**Comment by jamescowens** [comment]
I am running sync from zero and some other final tests on this on both testnet and mainnet and then will merge into the development branch. Given the situation we need to move on this.

**Comment by jamescowens** [comment]
The sync from zero on both mainnet and testnet passed. Temporarily resetting the GetNewbieSnapshotFixHeight() for mainnet to 2154000 (before the last superblock), deleting the accrual directory, and restarting then running auditsnapshotaccruals results in 0 mismatches. Merging to the dev branch.
