### PR TITLE
beacon, contracts: Fix sync from zero issue due to ApplyContracts problem in 5.2.1.0

### LINKED ISSUE #2045: cannot sync from genesis
syncing stalls at block height ~2083376~ 2069264. the other block 2083376 is also affected, and others from that cpid
The block cannot be verified, as it seems like an beacon has timed out.

when an the stalled wallet the following beacon report for the beacon staking is reported:
```
{
  "active": [
    {
      "cpid": "271870e186c59eeb85f29c65888d4b54",
      "active": false,
      "pending": false,
      "expired": true,
      "renewable": true,
      "timestamp": "05-20-2020 00:42:34",
      "address": "S1QUvNo2QsMPPMMNiSHgrFPgUZb8ZC3q4b",
      "public_key": "02a03823370909b4288c748e64dd0925a9af1f52ec30d38d60a0e375bf3e2a969e",                                                                                      
      "private_key_available": false,
      "magnitude": 28,
      "verification_code": "XaTUB8AGTa3FadAXdG4Liumngxb",
      "is_mine": false
    }
  ],
  "pending": [
  ]
}
```

other blocks staked by this CPID are also affected at least until including block 2165659.

### PR DESCRIPTION
**Pull request by jamescowens**
This corrects a problem involving the application of multiple contracts to the block index on sync from zero, and also the storage of those in the beacon db. Closes #2045.

### CODE REVIEW

**Comment by jamescowens** [comment]
Note that https://github.com/gridcoin-community/Gridcoin-Research/pull/2047/commits/d54fb5e7297f9a3c7efb301e3baddd888fee936b is the only commit strictly necessary to solve the problem, although it requires starting the sync from zero over again. The other commit is an attempt to be able to recover a node stuck on 2069264 by simply shutting down the wallet and restarting with this PR applied. The PR does what it is supposed to do and applies the missing contracts and corrects the blockindex, but the wallet remains stuck on a missing tx index. Despite that, in the interest of correctness, I want to include the blockindex correction to ensure there are no bad records in the blockindex created by running 5.2.1.0.

**Comment by jamescowens** [comment]
Notice this PR is against hotfix, which I have brought even with master. The intention is to merge this to master for the 5.2.2.0 release and then back merge to testnet and development.

File: src/gridcoin/beacon.cpp [hunk 1]
```diff
@@ -435,7 +436,16 @@ void BeaconRegistry::Add(const ContractContext& ctx)
...
+        {
+            LogPrint(LogFlags::BEACON, "INFO: %s: In activation of v1 beacon for cpid %s, address %s, hash %s, beacon db record "
+                                       "already exists. This can be expected on a restart of the wallet to ensure multiple "
+                                       "contracts in the same block get stored/replayed.",
+                     __func__,
+                     historical.m_cpid.ToString(),
+                     historical.GetAddress().ToString(),
+                     historical.m_hash.GetHex());
+        }
         m_beacons[payload.m_cpid] = std::make_shared<Beacon>(m_beacon_db[ctx.m_tx.GetHash()]);
```
Comment (cyrossignol) [inline src/gridcoin/beacon.cpp:449]: Minor... worth wrapping this in an else clause to save a few cycles?

File: src/gridcoin/beacon.cpp [hunk 2]
```diff
@@ -458,7 +468,16 @@ void BeaconRegistry::Add(const ContractContext& ctx)
...
+                                   "already exists. This can be expected on a restart of the wallet to ensure multiple "
+                                   "contracts in the same block get stored/replayed.",
+                 __func__,
+                 pending.m_cpid.ToString(),
+                 pending.GetAddress().ToString(),
+                 pending.m_hash.GetHex());
+    }
 
     // Insert a pointer to the entry in the m_pending map.
     m_pending[pending.GetId()] =  std::make_shared<Beacon>(m_beacon_db[ctx.m_tx.GetHash()]);
```
Comment (cyrossignol) [inline src/gridcoin/beacon.cpp:483]: Same here.

**Review by cyrossignol — COMMENTED** [review]
Sync from zero works as expected. Testing correction cases.

**Review by cyrossignol — APPROVED** [review]
