### PR TITLE
gui, util: Improve upgrade dialog

### LINKED ISSUE #2666: Gridcoin update notification is too small and unresizeable.
# Bug Report

**Current behavior**

It can displays changelog in 47x5 window
**Expected behavior**

Window can be resized
**Steps to reproduce:**

Install gridcoin wallet 5.4.1.0.
get update notification.
**Screenshots**

image

**Gridcoin version**

v5.4.1.0-4
**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SSD):

**Extra information**

### PR DESCRIPTION
**Pull request by jamescowens**
This changes the upgrade message box to a subclassed dialog box that is bigger in size and allows for further refinement in the future, plus makes other minor improvements.

Closes #2666.

A "version information" button has been added to the About Gridcoin dialog box, which brings up the same dialog as the upgrade check. This button only appears if the wallet is on mainnet.

image

The new version information/upgrade dialog box now includes the GitHub release information by default, and also displays an appropriate icon based on the nature of the version, mandatory or leisure. It also is larger by default and can be resized.

image

If you happen to be running a release that is actually greater than the official release (as this case with a test node on mainnet for testing), it will warn you about this too.

### CODE REVIEW

File: src/qt/aboutdialog.cpp [hunk 1]
```diff
@@ -11,6 +13,12 @@ AboutDialog::AboutDialog(QWidget *parent) :
     ui->copyrightLabel->setText("Copyright 2009-2024 The Bitcoin/Peercoin/Black-Coin/Gridcoin developers");
 
     resize(GRC::ScaleSize(this, width(), height()));
+
+    if (!fTestNet) {
+        connect(ui->versionInfoButton, &QAbstractButton::pressed, this, [this]() { handlePressVersionInfoButton(); });
+    } else {
+        ui->versionInfoButton->hide();
```
Comment (div72) [inline src/qt/aboutdialog.cpp]: nit: Would be nicer to disable the button with a message instead of hiding it.
```suggestion
        ui->versionInfoButton->setDisabled(true);
        ui->versionInfoButton->setToolTip(tr("Version information is not available on testnet."));
```

File: src/gridcoin/upgrade.cpp [hunk 2]
```diff
@@ -163,26 +164,35 @@ bool Upgrade::CheckForLatestUpdate(std::string& client_message_out, Upgrade::Upg
...
                                                           CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD) + "\r\n";
     client_message_out.append(_("GitHub version: ") + GithubReleaseData + "\r\n");
-    client_message_out.append(_("This update is ") + GithubReleaseType + "\r\n\r\n");
 
-    // For snapshot requests we will handle things differently after this point
+    if (NewVersion) {
+        client_message_out.append(_("This update is ") + GithubReleaseType + "\r\n\r\n");
+    } else {
+        client_message_out.append(_("The latest release is ") + GithubReleaseType + "\r\n\r\n");
+        client_message_out.append(_("WARNING: You are running a version that is higher than the latest release.") + "\n");
```
Comment (div72) [inline src/gridcoin/upgrade.cpp:187]: Doesn't this also get appended if the current version == github version so that there's no new version?

Also a bit of an edge case but the original comparison above would go off in a case where latest github release is something like v5.7.1 and local version is v5.8.0 (only you'd encounter such a case probably) I think.

File: src/qt/aboutdialog.cpp [hunk 3]
```diff
@@ -30,3 +38,28 @@ void AboutDialog::on_buttonBox_accepted()
...
 }
+
+void AboutDialog::handlePressVersionInfoButton()
+{
+    std::string client_message_out;
+    std::string change_log;
+    GRC::Upgrade::UpgradeType upgrade_type = GRC::Upgrade::UpgradeType::Unknown;
+
+
+    GRC::Upgrade::CheckForLatestUpdate(client_message_out, change_log, upgrade_type, false, false);
```
Comment (div72) [inline src/qt/aboutdialog.cpp:70]: This completely locks the GUI thread for a few seconds if you have bad connectivity.

Comment (jamescowens) [reply src/qt/aboutdialog.cpp:70]: I actually tested this with no connectivity, and it was faster than I could get to the ok. It is not worth the hassle to do the threadsafe pattern on this, although we could.

File: src/gridcoin/upgrade.cpp (hunk 2 above)
Comment (jamescowens) [reply src/gridcoin/upgrade.cpp:187]: I was making changes to deal with the current version case as you were looking at this. See the force push.

File: src/qt/aboutdialog.cpp (hunk 1 above)
Comment (jamescowens) [reply src/qt/aboutdialog.cpp]: Seems equivalent in this case since the only way you can get to that button is this one screen, but ok.

File: src/qt/aboutdialog.cpp (hunk 3 above)
Comment (jamescowens) [reply src/qt/aboutdialog.cpp:70]: Do you really think it is worth the plumbing?

Comment (div72) [reply src/qt/aboutdialog.cpp:70]: > Do you really think it is worth the plumbing?

Eh, not really on second thought.

**Review by div72 — APPROVED** [review]
