### PR TITLE
qt: Prevent pasting (no label) as label in consolidation transaction

### LINKED ISSUE #2252: "(no label)" gets added as label
# Bug Report

**Current behavior**
When using the consolidate wizard label "(no label)" gets added to the address as a label.

**Expected behavior**
No label should not be added if not inputed by the user.

**Steps to reproduce:**
Run the wizard and consolidate to and from addresses without a label.

**Screenshots**

**Gridcoin version**
v5.3.1.9-gba069f300 

**Machine specs**
- OS: MacOS
- CPU: arm64
- RAM: 16 GB
- Disk size: 512 GB
- Disk Type (HD/SSD): SSD

**Extra information**

### PR DESCRIPTION
**Pull request by jamescowens**
QVariant AddressTableModel::data substitutes tr("(no label)") for an empty QString label for display prettification. Unfortunately since the model values are used in the void SendCoinsDialog::selectedConsolidationRecipient, without filtering this substitution back out, it results in pasting a literal translation of "(no label)" as the label for the consolidation transaction. This label is then saved for that address. This one-liner filters that out and restores the intended behavior.

Together with #2253 closes #2252.

### CODE REVIEW

File: src/qt/sendcoinsdialog.cpp [hunk 1]
```diff
@@ -505,6 +503,12 @@ void SendCoinsDialog::selectedConsolidationRecipient(SendCoinsRecipient consolid
         }
     }
 
+    // This ugly hack is because the AddressTableModel substitutes the translated "(no label)" when
+    // the label is empty. If we use that here, we will end up pasting a literal lable of "(no label)".
```
Comment (barton2526) [inline src/qt/sendcoinsdialog.cpp]:
```suggestion
    // the label is empty. If we use that here, we will end up pasting a literal label of "(no label)".
```

**Review by cyrossignol — APPROVED** [review]
Looks fine to me. Eventually, we'll want to use the model directly to avoid special handling for the display values.

**Review by iFoggz — APPROVED** [review]
utACK 12660e3

Reasonable.
