### PR TITLE
rpc: Enhance consolidateunspent and fix fee calculation

### LINKED ISSUE #638: Coin control sometimes displays wrong quantity
Coin control sometimes says that selected quantity is nonzero while all utxos are unchecked. It stays nonzero even after toggling the "(un)select all" button.

### LINKED ISSUE #1296: coin control counts spent inputs when they stake
if you select an input with coin control and just leave it selected and it stakes, it continues to be counted and can no longer be deselected. rebooting the wallet resolves the issue.

### PR DESCRIPTION
**Pull request by jamescowens**
This PR enhances consolidateunspent. It implements two new parameters which correspond to two new features:

1. [sweep all addresses], which is an optional boolean that defaults to false. If set true, then all inputs that belong to the walletholder (ISMINE) are selected as candidates for the consolidation, not just inputs from the specified address. The output of the consolidation will go to the specified address in this case.
2. [sweep change], which is an optional boolean that defaults to false. If set true then inputs that have change addresses that were change of an input address that corresponds to the specified consolidation address are also included in the consolidation. If the [sweep all addresses] is set true, then the setting of this is irrelevant and is ignored (i.e. change sweep is implied when [sweep all addresses] is set).

I also corrected the fee calculations, as I discovered a slight error was causing rejects in certain corner cases.

This PR also closes #1296 and #638 in a very simple way by adding a "reset" button to reset the inputs.

### CODE REVIEW

File: src/rpc/rawtransaction.cpp [hunk 1]
```diff
@@ -488,19 +490,38 @@ UniValue listunspent(const UniValue& params, bool fHelp)
...
-                "whichever is less.\n"
+                "The script is designed to be run repeatedly and will become a no-op if the UTXO's are consolidated such\n"
+                "that no more meet the specified criteria. This is ideal for automated periodic scripting.\n"
                 "\n"
-                "The script is designed to be run repeatedly and will become a no-op\n"
-                "if the UTXO's are consolidated such that no more meet the specified\n"
-                "criteria. This is ideal for automated periodic scripting.\n");
+                "To consolidate the entire wallet to one address do something like:\n"
+                "\n"
+                "consolidate unspent <address> <amount equal or larger than balance> 200 true repeatedly until there are\n"
```
Comment (div72) [inline src/rpc/rawtransaction.cpp]:
```suggestion
                "consolidateunspent <address> <amount equal or larger than balance> 200 true repeatedly until there are\n"
```

File: src/rpc/rawtransaction.cpp [hunk 2]
```diff
@@ -534,33 +567,107 @@ UniValue consolidateunspent(const UniValue& params, bool fHelp)
...
+        } // else if (pwalletMain->IsChange(out.tx->vout[out.i]))
+    } // for (auto const& out : vecInputs)
+
+    CWalletTx wtxNew;
 
     set<pair<const CWalletTx*,unsigned int>> setCoins;
 
     unsigned int iInputCount = 0;
-    int64_t nValue = 0;
+    int64_t nAmount = 0;
```
Comment (div72) [inline src/rpc/rawtransaction.cpp]:
```suggestion
    CAmount nAmount = 0;
```

**Review by div72 — APPROVED** [review]

**Review by div72 — APPROVED** [review]
