### PR TITLE
scraper, util, qt: Fix several deprecations and warnings

### LINKED ISSUE #2132: QT functions deprecated with QT update
Taken from the macOS build log.  This is not a complete listing of all locations where the deprecations exist, just the unique calls that need replacing.

QFlags
`qt/bitcoin.cpp:529:54: warning: 'QFlags' is deprecated: Use default constructor instead [-Wdeprecated-declarations]
      QSplashScreen splash(QPixmap(":/images/splash"), 0);`

SystemLocaleShortDate
`qt/guiutil.cpp:45:37: warning: 'SystemLocaleShortDate' is deprecated: Use QLocale [-Wdeprecated-declarations]
      return date.date().toString(Qt::SystemLocaleShortDate) + QString(" ") + date.toString("hh:mm");`

QDateTime
`qt/optionsmodel.cpp:307:15: warning: 'QDateTime' is deprecated: Use QDate::startOfDay() [-Wdeprecated-declarations]
      QDateTime limitTxnDateTime(limitTxnDate);`

mapped
qt/rpcconsole.cpp:354:73: warning: 'mapped' is deprecated: Use QSignalMapper::mappedInt(int) instead [-Wdeprecated-declarations]
`connect(signalMapper, static_cast<void (QSignalMapper::*)(int)>(&QSignalMapper::mapped), this, &RPCConsole::banSelectedNode);`

### PR DESCRIPTION
**Pull request by jamescowens**
Closes #2132.

Note that the destructor on the class CSplitBlob should have been virtual because it has virtual members that are overridden in derived classes (CScraperManifest).

The ENTER_CRITICAL_SECTION / LEAVE_CRITICAL_SECTION approach to cs_vSend locking was causing clang threadsafe warnings. I replaced these with the standard LOCK treatment, in this case external to those functions in the only two places that they are called from. I added comments that a lock must be taken on cs_vSend prior to using those functions.

QFlags::Zero is deprecated. Using the default constructor is recommended.

Qt::SystemLocaleShortDate is deprecated. I replaced it with the recommended QLocale call.

For the SignalMapper, this is irritating. The QSignalMapper::mapped is deprecated in Qt 5.15+, but the replacement, mappedInt, is not even available prior to 5.15, so this requires a conditional preprocessor directive to use the correct one.

Constructing a QDateTime from QDate via QDatetime(QDate) is now deprecated. Qt recommends using QDate::startOfDay(), except that method is not available until 5.14+. So this also requires a conditional preprocessor directive.

### CODE REVIEW

File: src/gridcoin/scraper/scraper_net.h [hunk 1]
```diff
@@ -164,6 +164,7 @@ class CScraperManifest
     bool bCheckedAuthorized;
 
 public: /* public methods */
+    virtual ~CScraperManifest();
```
Comment (denravonska) [inline src/gridcoin/scraper/scraper_net.h]: The virtuality comes from `CSplitBlob`, so what I think you want is `virtual ~CSplitBlob() = default;` and it should be good to go.

Comment (jamescowens) [reply src/gridcoin/scraper/scraper_net.h]: Ah. But I just looked. The CSplitBlob destructor already has a concrete implementation. I think all we have to do is add "virtual" to the header. I am trying that now.

File: src/qt/optionsmodel.cpp [hunk 2]
```diff
@@ -304,7 +304,11 @@ QDate OptionsModel::getLimitTxnDate()
 
 int64_t OptionsModel::getLimitTxnDateTime()
 {
+#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
     QDateTime limitTxnDateTime(limitTxnDate);
+#else
+    QDateTime limitTxnDateTime = limitTxnDate.startOfDay();
+#endif
```
Comment (cyrossignol) [inline src/qt/optionsmodel.cpp:311]: Heh, this one again... 🙂

**Review by cyrossignol — APPROVED** [review]

File: src/qt/optionsmodel.cpp (hunk 2 above)
Comment (jamescowens) [reply src/qt/optionsmodel.cpp:311]: Yep... :) You remembered that.... :)
