### PR TITLE
Fix missing poll in GUI when most recent poll expired

### LINKED ISSUE #1454: Polls not showing on overview UI (RC3 staging QT)
~This is possibly a regression as a result of the fix for Issue #1446~

Build is `v4.0.2.4-g127baf4dc-0` Windows 64 bit QT

Overview screen shows this:

polls

Moving to the poll UI shows there are three active polls currently:

polls2

Relevant segment of `getmininginfo`:

`"MiningInfo 1": "",`
`"MiningInfo 2": "Poll: this_is_a_poll",`
`"MiningInfo 5": "",`
`"MiningInfo 6": "",`
`"MiningInfo 7": "",`
`"MiningInfo 8": ""`

@cyrossignol Also reports seeing this issue.

**NOTE THIS ISSUE IS ALSO PRESENT IN RC2**

### PR DESCRIPTION
**Pull request by cyrossignol**
This fixes #1454 by fetching the next most recent active poll from the `AppCache` when the poll stored in `msPoll` expired. The most recent poll published to the network is not necessarily the poll that expires last--an earlier poll could exist that expires later.

Also updates the RPC output from #1437.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -675,36 +676,33 @@ void GetGlobalStatus()
...
-    if(sPollExpiration.empty())
-    {
-        uPollExpiration = pindexBest->nTime;
+    AssertLockHeld(MinerStatus.lock);
+
+    // The global msPoll variable contains the poll most-recently published to
+    // the network. If it hasn't expired, return the title of this poll:
+    if (PollIsActive(msPoll)) {
+        return ExtractXML(msPoll, "<MK>", "</MK>").substr(0, 80);
     }
```
Comment (cyrossignol) [inline src/main.cpp:685]: Note: need to investigate how the alerts plug into the polls--I couldn't see how this works.

Comment (cyrossignol) [reply src/main.cpp:685]: Looks like that logic was introduced in #1250.

File: src/main.cpp [hunk 2]
```diff
@@ -675,36 +676,33 @@ void GetGlobalStatus()
...
-        {
-            uPollExpiration = stoll(sPollExpiration);
-        }
-        catch(std::exception &e)
-        {
-            // Malformed poll expiration, don't display
-            uPollExpiration = 0;
+
+    // Otherwise, find the most recent active poll from the AppCache:
+    AppCacheSection::value_type const* selected_ptr = nullptr;
```
Comment (denravonska) [inline src/main.cpp]: I think we should use a copy here. While `ReadCacheSection` returns a reference now, if we change that this will break. The check whether a poll existed or not can be solved using

```
boost::optional<AppCacheEntry> selected_entry;
for(auto& entry : ReadCacheSection(...))
   if(...)
      selected_entry = entry;

if(!selected_entry)
   return _("No current polls");
```

Comment (cyrossignol) [reply src/main.cpp]: Done 🙂 I just went with a string for a faster copy, but `optional` is pretty neat. I figured the pointer was okay because we're talking about moving away from the AppCache, but good to be safe!

**Comment by jamescowens** [comment]
I created a testnet alert to see if this PR affects the alert display. It does not.

image

**Comment by jamescowens** [comment]
The PR works. The above image is from a wallet with the PR applied and the below is not...
image

**Review by jamescowens — APPROVED** [review]

**Review by denravonska — APPROVED** [review]
