### PR TITLE
gui: Modify VerifyTCPPort to use the status of CheckOutboundConnectionCount

### LINKED ISSUE #2445: Diagnostics screen reports outbound port is not working on both Testnet and Mainnet wallets version 5.3.3.0
Both wallets have been working fine after the new update.  Diagnostics passed on both wallets. No changes to configuration files.
Rebooted the computer after 11 days and now both wallets show the error.
Rebooted several times and still shows the error.

Made many changes to the computers network firewall settings which were never activated before. Port forwarded ports 32748 and 32749 and no change in symptoms. Changed listen=0 to listen=1 in the config files.  No change in symptoms.

Both wallets do in fact show outbound port activity. Diagnostics still failing.

Screenshot from 2022-03-01 09-35-46

Screenshot from 2022-03-01 10-15-05

Gridcoin wallets version 5.3.3.0 both for Testnet and Mainnet
Pulled from the PPA's via apt update

AMD 5950X
32GB RAM
512GB M.2 SSD
Ubuntu 20.04.4 LTS

### PR DESCRIPTION
**Pull request by jamescowens**
Note that the VerifyTCPPort test has historically used the port testing service portquiz.net. This service has gone down in the past. Since we are checking outbound and the CheckOutboundConnection test is done first, if that check did not fail, simply mark the VerifyTCPPort test successful, since the port must be working properly if successful outbound connections have been made. This makes it much less likely to get an inaccurate Port test, since BOTH no connections would have to be occurring AND portquiz.net would have to be down.

Obviously using more than one port verification service as a fallback would eliminate this possibility entirely, but this is reserved for consideration when the diagnostics get refactored to address #2477. (The diagnostics really need to be refactored anyway. I did a refactoring a while back to clean up some of the mess, but it still is ugly.)

This PR is sufficient to close #2445.

### CODE REVIEW

File: src/qt/diagnosticsdialog.cpp [hunk 1]
```diff
@@ -126,17 +126,41 @@ unsigned int DiagnosticsDialog::UpdateTestStatus(std::string test_name, QLabel *
...
+void DiagnosticsDialog::UpdateTestResult(std::string test_name, DiagnosticResult test_result)
+{
+    LOCK(cs_diagnostictests);
+
+    m_test_result_map[test_name] = test_result;
+}
+
+DiagnosticsDialog::DiagnosticResult DiagnosticsDialog::GetTestResult(std::string test_name)
+{
+    DiagnosticResult result;
```
Comment (div72) [inline src/qt/diagnosticsdialog.cpp:147]:
```suggestion
    LOCK(cs_diagnostictests);

    DiagnosticResult result;
```

**Review by div72 — APPROVED** [review]
utACK.
