### PR TITLE
gui: Port Bitcoin Intro class (implement the ability to choose a data directory via the GUI)

### LINKED ISSUE #1303: Gridcoin wallet exits silently if the config file is badly formatted.
My gridcoinresearch.conf file someone because overwritten with nulls. The result was that gridcoinresearch.exe started and exited silently 1/2 second later. Silently means no messages, no debug logs, no relevant events in the Windows event log. This was time consuming to run down.

There need to be appropriate error messages if
  - the config file is absent,
  - the config file is badly formatted.
  - the config file contains all nulls,
  - the config file contains random garbage.

A silent exit is really not acceptable.

### LINKED ISSUE #1872: cli gridcoinresearchd running, gui gridcoinresearch-qt does not get lock (shows alert box) and segfaults after close
Hello,
This is under Linux (Ubtunu bionic, Richard's PPA-provided packages) , i.e. remotely logged in from a Windows machine with X display forwarding. It is a completely new 5.0 install, gridcoinresearchd started, responsive but non-informative about my wallet, wanted to start the GUI to it to learn if there is extra information for me. I presume gridcoinresearchd to be still syncing, at least the disk space still grows it occupies (about 700MB).

While gridcoinresearchd is running, gridcoinresearch complains in an alert box that it cannot get hold of the lock. After closing the window, gridcoinresearch (not researchd) segfaults. This is very reproducible. So much so that I took the freedom to add a backtrace below.

The biggest problem I had was that the altert box was appearing behind (i.e. invisibly) behind the fancy gridcoin splash screen. A tiny bit was visible for me that after quite a wait (presumed it syncing) eventually discovered. That is quite a no-go as I am confident you will agree.

Many thanks and regards,
Steffen

```
Core was generated by `gridcoinresearch'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:65
65      ../nptl/pthread_mutex_lock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1a801f1780 (LWP 11317))]
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:65
#1  0x000055ba61d32992 in __gthread_mutex_lock (__mutex=0x7fff6b5df1a0) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:748
#2  __gthread_recursive_mutex_lock (__mutex=0x7fff6b5df1a0) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:810
#3  std::recursive_mutex::lock (this=0x7fff6b5df1a0) at /usr/include/c++/7/mutex:107
#4  AnnotatedMixin<std::recursive_mutex>::lock (this=0x7fff6b5df1a0) at ./sync.h:58
#5  std::unique_lock<CCriticalSection>::lock (this=0x7fff6b5df1a0) at /usr/include/c++/7/bits/std_mutex.h:267
#6  CCriticalBlock::Enter (pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, this=0x7fff6b5df1a0) at ./sync.h:121
#7  CCriticalBlock::CCriticalBlock (this=this@entry=0x7fff6b5df1a0, mutexIn=..., fTry=fTry@entry=false, nLine=<optimized out>, pszFile=<optimized out>, pszName=<optimized out>) at ./sync.h:142
#8  0x000055ba61d336be in BanMan::GetBanned (this=0x0, banmap=std::map with 0 elements) at banman.cpp:181
#9  0x000055ba61cfc878 in BanTablePriv::refreshBanlist (this=0x55ba63843cc0) at qt/bantablemodel.cpp:53
#10 BanTableModel::refresh (this=this@entry=0x55ba63861ed0) at qt/bantablemodel.cpp:168
#11 0x000055ba61cfcc4f in BanTableModel::BanTableModel (this=0x55ba63861ed0, parent=<optimized out>) at qt/bantablemodel.cpp:93
#12 0x000055ba61c51be3 in ClientModel::ClientModel (this=0x7fff6b5df560, optionsModel=<optimized out>, parent=<optimized out>) at qt/clientmodel.cpp:29
#13 0x000055ba61c2a726 in StartGridcoinQt (argc=<optimized out>, argv=0x7fff6b5e03e8) at qt/bitcoin.cpp:475
#14 0x000055ba61c118a8 in main (argc=1, argv=0x7fff6b5e03e8) at qt/bitcoin.cpp:280
```

### LINKED ISSUE #1952: Squashed text after change to inter font.
Relevant to #1926 

With the new inter font the body text in the program is visible squashed on my machine.

5.0.1:
image

5.1.0:
image

Screenshot from mockup for comparison:
mockup

### LINKED ISSUE #1953: Low dpi error
On low dpi (13"), gridcoin window is... big. 
Image here : 
image

### PR DESCRIPTION
**Pull request by jamescowens**
This PR is a port of Bitcoin's Intro class and the associated form to support the choice of a data directory via the GUI. This PR also has implemented stateful management of that choice in the optionsModel, similar to the Bitcoin approach. This should make the choice of non-default data directories much easier for people with GUI wallet installations, especially the MacOS, where it is difficult to supply program arguments to the underlying command line in the icon.

I have also solved the silent exit if the gridcoinresearch.conf file is corrupted/badly formatted. The solution uses a simplified form of the newer Bitcoin config file parsing functions, which needed to be ported anyway to suppport Intro. (Closes #1303.)

Most of the issues with scaling I think I have solved with this PR. (Closes #1952 and closes #1953.)

Also implements an early check for the ability to lock the data directory. Closes #1872.

### CODE REVIEW

**Comment by jamescowens** [comment]
I think I have solved many of the issues in #1926 also with this PR.

**Comment by jamescowens** [comment]
I have done quite a bit of testing and "futzing" with this on several different platforms.

The appearance looks good on my hidpi openSUSE Linux box, my hidpi W10 box, my old Windows 2008 32 bit server VM (not hidpi), and my ARM Odroid. I have reduced the default size of the window, and implemented memorization of the window geometry (size and position).

Functionality testing:
1. Fresh start of Gridcoin with missing data dir, the dialog comes up.
2. Snapshot download functionality still works correctly.
3. Stateful storage of data directory works as it should. Verified on Windows with unicode path.
4. Window geometry is memorized correctly
5. -choosedatadir override argument correctly re-presents the Intro dialog box to choose a new data directory
6. Specifying -datadir as an argument overrides the setting in the GUI config file/registry entry area and does not disturb the entry in the GUI config.
7. On the config file silent exit problem. Bad config files now produce a dialog box that warns that config file cannot be parsed correctly and the application exits rather than exiting silently.

**Comment by jamescowens** [comment]
I still don't like the look of the intro dialog on Windows hidpi displays. It is too narrow. @cyrossignol maybe you can take a look. Windows is doing something funky with the logicalDpi I think.

**Comment by jamescowens** [comment]
I am not fooling with the dialog size anymore. It is pretty narrow on Windows hidpi displays, but it doesn't cut any of the text off. Good enough for right now.

**Review by cyrossignol — COMMENTED** [review]
Looks pretty good from an initial glance... building to test and play with different DPIs...

**Comment by nathanielcwm** [comment]
I'll take a look soon...

**Comment by jamescowens** [comment]
Please take a look. I don't want this PR to sit around too much longer.

**Comment by nathanielcwm** [comment]
idk don't really see an appreciable difference between this pr and 5.1.0 in terms of the font rendering.
image

Datadir choice box looks fine though.

**Comment by jamescowens** [comment]
@nathanielcwm What resolution are you running and what scale factor do you have set for the GUI?

File: src/qt/bitcoin.cpp [hunk 1]
```diff
@@ -232,10 +233,92 @@ int main(int argc, char *argv[])
...
+    if (qtTranslator.load("qt_" + lang_territory, QLibraryInfo::location(QLibraryInfo::TranslationsPath)))
+        app.installTranslator(&qtTranslator);
+
+    // Load e.g. bitcoin_de.qm (shortcut "de" needs to be defined in bitcoin.qrc)
+    if (translatorBase.load(lang, ":/translations/"))
+        app.installTranslator(&translatorBase);
+
+    // Load e.g. bitcoin_de_DE.qm (shortcut "de_DE" needs to be defined in bitcoin.qrc)
+    if (translator.load(lang_territory, ":/translations/"))
+        app.installTranslator(&translator);
```
Comment (cyrossignol) [inline src/qt/bitcoin.cpp:301]: Localization works with the tip of the development branch, but it seems broken with this PR. Not sure why yet.

Comment (jamescowens) [reply src/qt/bitcoin.cpp:301]: Hmm... that's strange. I really didn't do anything that should disturb that.

File: src/qt/intro.cpp [hunk 2]
```diff
@@ -0,0 +1,324 @@
...
+        /* Use selectParams here to guarantee Params() can be used by node interface when we implement it from
+           Bitcoin. */
+        try {
+            SelectParams(mapArgs.count("-testnet") ? CBaseChainParams::TESTNET : CBaseChainParams::MAIN);
+        } catch (const std::exception&) {
+            return false;
+        }
+
+        /* If current default data directory does not exist, let the user choose one */
+        Intro intro(0);
```
Comment (cyrossignol) [inline src/qt/intro.cpp]: We should be able to keep the free space heuristic from Bitcoin even though we don't have pruning since we maintain the estimates now (as of #1878).

```suggestion
        Intro intro(0, Params().AssumedBlockchainSize());
```

Comment (jamescowens) [reply src/qt/intro.cpp]: Agreed.

Comment (jamescowens) [reply src/qt/intro.cpp]: I just went and looked. Where are the estimates?

Comment (cyrossignol) [reply src/qt/intro.cpp]: https://github.com/gridcoin-community/Gridcoin-Research/blob/91a4862374e239165db54ef9c9865b902263b855/src/chainparams.cpp#L77

Comment (jamescowens) [reply src/qt/intro.cpp]: I see m_assumed_blockchain_size in chainparams.h, but I don't see anything filling that out.

Comment (jamescowens) [reply src/qt/intro.cpp]: Hmm... where is Bitcoin filling out blockchain_size_gb...

Comment (jamescowens) [reply src/qt/intro.cpp]: Geez... it is just as simple as 2 GB for testnet and 4 GB for mainnet?

Comment (jamescowens) [reply src/qt/intro.cpp]: That is a pretty bad heuristic.

Comment (jamescowens) [reply src/qt/intro.cpp]: Ok. Put that back in.

**Comment by nathanielcwm** [comment]
@jamescowens 1280x1024
It's at 100%

File: src/qt/bitcoin.cpp (hunk 1 above)
Comment (jamescowens) [reply src/qt/bitcoin.cpp:301]: I have set up a Windows VM with German. It is definitely broke. I will figure it out.

Comment (jamescowens) [reply src/qt/bitcoin.cpp:301]: Nope it is working for me.

image

Comment (jamescowens) [reply src/qt/bitcoin.cpp:301]: Note that the fields in the Intro dialog box are not translated, in either Bitcoin or this PR...

**Comment by jamescowens** [comment]
@nathanielcwm did you resize the application window? This is the default size with 1280x1024 and 100% scaling in Windows 10 (with German localization active). It looks good to me, and different from yours above.


VirtualBox_W10-2_05_12_2020_22_16_41

It also appears the same as the 5.1.0.0 release on Windows.

**Comment by nathanielcwm** [comment]
Weird...
Nope I didn't except I think that screenshot was maximised.
Could you send me a compiled executable to test, just in case I messed up building lol.

I'm using the native theme but it looks like your screenshot might be with the light theme? @jamescowens

File: src/qt/bitcoin.cpp (hunk 1 above)
Comment (cyrossignol) [reply src/qt/bitcoin.cpp:301]: Hmm... let me try rebuilding.

Comment (cyrossignol) [reply src/qt/bitcoin.cpp:301]: Did you try changing the language from the options as well as with the system locale?

**Comment by jamescowens** [comment]
It was light. But native is no different.

VirtualBox_W10-2_05_12_2020_23_07_29

**Comment by jamescowens** [comment]
If you maximize the window, of course the layout is going to look sparse. The text is sized for the window to take up 40% to 60% of the x and y dimensions of the screen. It is 40% for hidpi screens and increases to more like 60% of low dpi screens because of minimum size settings for some of the widgets. (It used to be 60% plus in each dimension for all, but I changed it to 40%, because 60% is really too big for today's aesthetic.)

The text does not change scale even if the wallet is maximized, and is not meant to. Most people have been asking for a smaller window layout anyway.

**Comment by jamescowens** [comment]
If we think this font is too squashed, maybe we should change to a different open source sans serif with a little wider layout for a given point size.

File: src/qt/bitcoin.cpp (hunk 1 above)
Comment (jamescowens) [reply src/qt/bitcoin.cpp:301]: Nope. I moved the initialization of the options model to above the translation inits. So that should fix it.

**Comment by nathanielcwm** [comment]
@jamescowens well my issue isn't it looking sparse it's the text being squished

Just built on 04d0c77 and it looks like i'm still experiencing squished text

image

Maybe it's just an issue with my Windows installation, especially since it doesn't look like anyone else is reporting this issue.

**Comment by jamescowens** [comment]
I think it depends on your definitiion of squished. :) That text looks ok to me. It is a little "tight" but many modern sans-serif fonts are that way.

**Comment by jamescowens** [comment]
Cy has been too busy to finish testing this on MacOS. It appears to be working well now. I am going to go ahead and merge this so that folks on testnet with MacOS can try it out easily.
