### PR TITLE
util, qt: Fix snapshot download

### LINKED ISSUE #2208: Unexpected crash on macOS
# Bug Report

**Current behavior**

I was installing the BOINC client on my Macbook Pro 16" while concurrently downloading the Gridcoin blockchain snapshot by selecting File->Snapshot Download on the toolbar. The snapshot was downloading between 3-4 MB/s and had downloaded about 0.6 GB so far. While installing the BOINC client, I noticed that the small download window with progress bar had gone blank. I clicked the Gridcoin dock icon which produced an immediate crash. 

**Expected behavior**
Crash happened on clicking Gridcoin dock icon, usually that would just bring the Gridcoin windows (in this case, wallet and snapshot download progress bar window) to the forefront. 

**Steps to reproduce:**
Haven't reproduced, not sure how. I'll keep an eye out if it happens again. 

**Screenshots**

**Gridcoin version**

Downloaded from this GitHub repo using tag 5.3.1.0_test. 

**Machine specs**
MacBook Pro (16-inch, 2019)
- OS: macOS Big Sur 11.4
- CPU: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz [x86 Family 6 Model 158 Stepping 13]
- RAM: 16 GB 2667 MHz DDR4
- Disk size: 1TB
- Disk Type (HD/SDD): SSD

**Extra information**

<details>
<summary>Apple-generated debug report</summary>
Process:               gridcoinresearch [2548]
Path:                  /Volumes/VOLUME/*/Gridcoin.app/Contents/MacOS/gridcoinresearch
Identifier:            org.bitcoinfoundation.Bitcoin-Qt
Version:               5.3.1 (5.3.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gridcoinresearch [2548]
User ID:               502

Date/Time:             2021-07-01 14:31:03.747 -0700
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        2AC711AD-12B3-4FE8-863A-EC5FBA337756

Sleep/Wake UUID:       AAD4B540-192A-4772-BCC8-3C7E21D1033D

Time Awake Since Boot: 4000 seconds
Time Since Wake:       1700 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2548]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x00000001046a5a27 QWidget::show() + 23
1   com.apple.Foundation          	0x00007fff2140b516 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308
2   com.apple.Foundation          	0x00007fff2140b386 _NSAppleEventManagerGenericHandler + 80
3   com.apple.AE                  	0x00007fff2647e7f3 0x7fff26472000 + 51187
4   com.apple.AE                  	0x00007fff2647df0e 0x7fff26472000 + 48910
5   com.apple.AE                  	0x00007fff26476c23 aeProcessAppleEvent + 448
6   com.apple.HIToolbox           	0x00007fff288f88d2 AEProcessAppleEvent + 54
7   com.apple.AppKit              	0x00007fff22ea9b90 _DPSNextEvent + 2046
8   com.apple.AppKit              	0x00007fff22ea7ec5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
9   libqcocoa.dylib               	0x000000010733f9f3 0x107304000 + 244211
10  org.bitcoinfoundation.Bitcoin-Qt	0x00000001031639a7 0x10309a000 + 825767
11  org.bitcoinfoundation.Bitcoin-Qt	0x00000001030a72c6 0x10309a000 + 53958
12  libdyld.dylib                 	0x00007fff205ccf5d start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff2057c2ba mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff2057c62c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206aab5f __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206a923f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation      	0x00007fff206a864c CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff2302f68a _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff2057ecde __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205b1e49 _pthread_cond_wait + 1298
2   org.bitcoinfoundation.Bitcoin-Qt	0x000000010344f2ad 0x10309a000 + 3887789
3   org.bitcoinfoundation.Bitcoin-Qt	0x000000010344f25f 0x10309a000 + 3887711
4   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff20584656 __select + 10
1   libcurl.4.dylib               	0x00007fff330c589a Curl_poll + 615
2   libcurl.4.dylib               	0x00007fff330c0907 Curl_multi_wait + 603
3   libcurl.4.dylib               	0x00007fff330b8b0a curl_easy_perform + 296
4   org.bitcoinfoundation.Bitcoin-Qt	0x00000001031ee18b 0x10309a000 + 1393035
5   org.bitcoinfoundation.Bitcoin-Qt	0x0000000103270346 0x10309a000 + 1925958
6   org.bitcoinfoundation.Bitcoin-Qt	0x0000000103165277 0x10309a000 + 832119
7   libboost_thread-mt.dylib      	0x00000001039eebf8 0x1039ec000 + 11256
8   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
9   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff205ad420 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff205ad420 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff205ad420 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff205ad420 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0xb526f5604fc90022  rbx: 0x00007ffeecb65678  rcx: 0x0000000000000000  rdx: 0x0000600003197a40
  rdi: 0x00006000018e9610  rsi: 0x0000000103868ead  rbp: 0x00007ffeecb64b00  rsp: 0x00007ffeecb64af0
   r8: 0x00006000031940a0   r9: 0x00007fff216e2d7b  r10: 0x0000000103894ed2  r11: 0x00000001030b66d2
  r12: 0x000060000395f960  r13: 0x00007fff2044f800  r14: 0x0000600003ac0b40  r15: 0x00006000034f1250
  rip: 0x00000001046a5a27  rfl: 0x0000000000010202  cr2: 0x000060002f424716
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     13

Thread 0 instruction stream:
  00 00 00 00 0f 1f 44 00-00 55 48 89 e5 48 8b 7f  ......D..UH..H..
  08 8b 87 a0 01 00 00 89-c1 c1 e9 1b 83 e1 01 31  ...............1
  f1 80 f9 01 74 19 89 c1-81 c9 00 00 00 08 25 ff  ....t.........%.
  ff ff f7 40 84 f6 0f 44-c1 89 87 a0 01 00 00 40  ...@...D.......@
  0f b6 f6 5d e9 10 36 ff-ff 55 48 89 e5 53 50 48  ...]..6..UH..SPH
  89 fb 48 8b 05 f0 06 40-00 48 8b 38 48 8b 43 28  ..H....@.H.8H.C(
 [8b]70 0c 48 8b 07 ff 90-a8 00 00 00 83 f8 02 74  .p.H...........t	<==
  7a 83 f8 04 0f 85 8e 00-00 00 48 89 df e8 87 59  z.........H....Y
  ff ff 48 8b 43 28 8b 70-10 83 e6 08 83 ce 04 48  ..H.C(.p.......H
  89 df e8 e2 5a ff ff 48-8b 03 48 89 df be 01 00  ....Z..H..H.....
  00 00 ff 50 68 0f 1f 40-00 48 8b 43 08 48 8b 48  ...Ph..@.H.C.H.H
  10 48 85 c9 74 0f 48 8b-53 28 8b 52 0c 48 89 cb  .H..t.H.S(.R.H..
  
Thread 0 last branch register state not available.

Binary Images:
       0x10309a000 -        0x103879fff +org.bitcoinfoundation.Bitcoin-Qt (5.3.1 - 5.3.1) <7EF847B9-B90E-379D-92F9-C8ACE92AF6A6> /var/folders/*/Gridcoin.app/Contents/MacOS/gridcoinresearch
       0x10396e000 -        0x103971fff +libboost_system.dylib (0) <AAAF2C2E-C95A-30A0-AA83-D37839B0F934> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_system.dylib
       0x103978000 -        0x10398bfff +libboost_filesystem.dylib (0) <ED5058BA-697C-3391-A32E-96A71FD9829B> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10399c000 -        0x1039cbfff +libboost_program_options-mt.dylib (0) <21A3D046-A354-34AD-90C4-3060AAE2BDBD> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x1039ec000 -        0x1039f7fff +libboost_thread-mt.dylib (0) <5A04F107-39F0-3560-8FAA-5CB5C94B5C9A> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x103a09000 -        0x103a0cfff +libboost_chrono-mt.dylib (0) <8DD3519B-0184-321D-B401-81130FEE3BE5> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x103a17000 -        0x103a22fff +libboost_iostreams-mt.dylib (0) <6D652ACF-96B1-30C8-BA21-3ABF4836D1B3> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_iostreams-mt.dylib
       0x103a38000 -        0x103a3bfff +libboost_system-mt.dylib (0) <F77E16D3-42F5-3CFF-AD44-B03000D087EC> /var/folders/*/Gridcoin.app/Contents/Frameworks/libboost_system-mt.dylib
       0x103a3f000 -        0x103f82fff +org.qt-project.QtCore (5.15 - 5.15.2) <226F4F10-F8C2-301E-AA19-240048D7C206> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x104052000 -        0x10453dfff +org.qt-project.QtGui (5.15 - 5.15.2) <535A424C-EF63-3E4C-A42A-5B5F18D0C07C> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10465a000 -        0x104aa5fff +org.qt-project.QtWidgets (5.15 - 5.15.2) <151402D2-0EE6-34F3-A101-E6CDD04F398A> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x104c0c000 -        0x104d1ffff +org.qt-project.QtNetwork (5.15 - 5.15.2) <7C449550-8880-3C41-B131-388DCC0585FA> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x104d6d000 -        0x104d74fff +org.qt-project.QtConcurrent (5.15 - 5.15.2) <ADB3D95D-2B0D-3B82-A68E-FFC9E063A29E> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x104d7e000 -        0x104e59fff +org.qt-project.QtCharts (5.15 - 5.15.2) <8E09C7D2-5611-31B5-9D3C-264A159ACDF2> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtCharts.framework/Versions/5/QtCharts
       0x104f06000 -        0x104f65fff +org.qt-project.QtDBus (5.15 - 5.15.2) <170FD3F7-EA0D-3344-8290-A0E9ACB3A883> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x104f81000 -        0x104f88fff +libqrencode.4.dylib (0) <CFF61E40-5BA6-362A-97C2-643588DE7A99> /var/folders/*/Gridcoin.app/Contents/Frameworks/libqrencode.4.dylib
       0x104f97000 -        0x1050a6fff +libdb_cxx-4.8.dylib (0) <77CBA1BA-E715-31C0-85AE-31B882D4E38E> /var/folders/*/Gridcoin.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x1050d2000 -        0x105121fff +libssl.1.1.dylib (0) <9BD08628-AC20-3489-B3D2-AC117A5BC2F8> /var/folders/*/Gridcoin.app/Contents/Frameworks/libssl.1.1.dylib
       0x10514b000 -        0x10530afff +libcrypto.1.1.dylib (0) <EF694AAC-B437-322C-B619-BF3EB122466C> /var/folders/*/Gridcoin.app/Contents/Frameworks/libcrypto.1.1.dylib
       0x10538e000 -        0x105399fff +libminiupnpc.17.dylib (0) <3F1F08BD-AAD9-3F43-9E7E-0DF421C559CE> /var/folders/*/Gridcoin.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x1053ab000 -        0x1053bbfff +libzip.5.dylib (0) <01712EF1-7BA0-3073-ACE4-806C184CE3D5> /var/folders/*/Gridcoin.app/Contents/Frameworks/libzip.5.dylib
       0x107304000 -        0x10746bfff +libqcocoa.dylib (0) <FDFF1859-EE45-351C-8ECF-A60FE4EDACA0> /var/folders/*/Gridcoin.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x1074bc000 -        0x1074e7fff +org.qt-project.QtPrintSupport (5.15 - 5.15.2) <767E9D97-E124-385F-9679-87C5FE69CCE9> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x1082cf000 -        0x1082defff  libobjc-trampolines.dylib (824) <361143B8-E66E-3402-85B5-C20893AAB9C9> /usr/lib/libobjc-trampolines.dylib
       0x108668000 -        0x10868ffff +libqmacstyle.dylib (0) <1849A958-4393-35D9-AEEC-ECEBE5934C8C> /var/folders/*/Gridcoin.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x1103c1000 -        0x1103c8fff +libqsvgicon.dylib (0) <F6733EC9-07BB-30B7-8D8D-FE14B0918C93> /var/folders/*/Gridcoin.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
       0x1103d0000 -        0x110407fff +org.qt-project.QtSvg (5.15 - 5.15.2) <4234EABD-88DA-328F-8A40-9A50E2C534CC> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x1113b5000 -        0x1113bcfff +libqgif.dylib (0) <6E8E4247-37C6-3204-ADDC-6244EB6DE497> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x1113c3000 -        0x1113cafff +libqicns.dylib (0) <EB86CC3D-B823-343D-9044-8A219D8AF4C6> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x1113d2000 -        0x1113d9fff +libqico.dylib (0) <FCC41E97-598C-32F4-8BCF-B7C2825E64F7> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqico.dylib
       0x1113e1000 -        0x111444fff +libqjpeg.dylib (0) <07224DB9-385C-330C-8B17-421EA26A9D9D> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x11144d000 -        0x111454fff +libqmacheif.dylib (0) <050A0EA9-DFE0-3D52-8C32-3B188BB04825> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqmacheif.dylib
       0x11145c000 -        0x111463fff +libqmacjp2.dylib (0) <3A670177-35BE-3FB6-A060-D758107E1F38> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x11146b000 -        0x111472fff +libqpdf.dylib (0) <E818633B-0FA2-38E4-9276-6BC5AE1F12C6> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqpdf.dylib
       0x111479000 -        0x111480fff +libqtga.dylib (0) <B3FA3E55-84F4-3793-B4C6-F2A60F67FD3A> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x111487000 -        0x1114eefff +libqtiff.dylib (0) <809F2B79-3FFC-359F-8893-73BBBCE6F317> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x1114f7000 -        0x1114fefff +libqwbmp.dylib (0) <E24690D9-FB9A-3A1A-A5AC-B91010343286> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x111505000 -        0x1115a0fff +libqwebp.dylib (0) <3BD34DC5-8B37-37ED-ADBB-642DA4B98402> /var/folders/*/Gridcoin.app/Contents/PlugIns/imageformats/libqwebp.dylib
       0x111c4f000 -        0x1120eefff  com.apple.AMDRadeonX6000MTLDriver (4.5.14 - 4.0.5) <B3387E41-6C51-3665-8931-791F5EAC36D6> /System/Library/Extensions/AMDRadeonX6000MTLDriver.bundle/Contents/MacOS/AMDRadeonX6000MTLDriver
       0x112bd0000 -        0x1131ebfff +org.qt-project.QtPdf (5.15 - 5.15.2) <3DCCF55A-4EA3-3076-B5EC-3965580022CB> /var/folders/*/Gridcoin.app/Contents/Frameworks/QtPdf.framework/Versions/5/QtPdf
       0x1132d2000 -        0x11336dfff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld
    0x7fff202e9000 -     0x7fff202eafff  libsystem_blocks.dylib (79) <48AF56A9-6E42-3A5E-A213-E6AFD8F81044> /usr/lib/system/libsystem_blocks.dylib
    0x7fff202eb000 -     0x7fff20320fff  libxpc.dylib (2038.120.1) <5751A7F5-6DC5-3090-B7F1-D90ED71BEF1F> /usr/lib/system/libxpc.dylib
    0x7fff20321000 -     0x7fff20338fff  libsystem_trace.dylib (1277.120.1) <8E243C00-BFC2-3FAA-989C-0D72314DB04D> /usr/lib/system/libsystem_trace.dylib
    0x7fff20339000 -     0x7fff203d6fff  libcorecrypto.dylib (1000.120.2) <FADB19A0-1BF3-3F47-B729-87B4FA8CA677> /usr/lib/system/libcorecrypto.dylib
    0x7fff203d7000 -     0x7fff20403fff  libsystem_malloc.dylib (317.121.1) <CAD162A5-7367-3A30-9C15-5D036411AEDE> /usr/lib/system/libsystem_malloc.dylib
    0x7fff20404000 -     0x7fff20448fff  libdispatch.dylib (1271.120.2) <7B229797-1F2E-3409-9D0C-060C7EEF2E12> /usr/lib/system/libdispatch.dylib
    0x7fff20449000 -     0x7fff20482fff  libobjc.A.dylib (824) <FE5AF22E-80A1-34BB-98D6-610879988BAA> /usr/lib/libobjc.A.dylib
    0x7fff20483000 -     0x7fff20485fff  libsystem_featureflags.dylib (28.60.1) <77F7F479-39BD-3111-BE3C-C74567FD120C> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff20486000 -     0x7fff2050efff  libsystem_c.dylib (1439.100.3) <38F8A126-C995-349A-B909-FF831914ED2E> /usr/lib/system/libsystem_c.dylib
    0x7fff2050f000 -     0x7fff20564fff  libc++.1.dylib (905.6) <B3812B86-4FCF-3A10-8866-DF67940A974C> /usr/lib/libc++.1.dylib
    0x7fff20565000 -     0x7fff2057afff  libc++abi.dylib (905.6) <A0FE88B7-E157-3C9C-A29A-11D3BE3436B3> /usr/lib/libc++abi.dylib
    0x7fff2057b000 -     0x7fff205aafff  libsystem_kernel.dylib (7195.121.3) <A4938CF5-ABC0-397B-8A6E-B7BEEFA24D0A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff205ab000 -     0x7fff205b6fff  libsystem_pthread.dylib (454.120.2) <17482C9D-061E-3769-AC9E-BE1239D33098> /usr/lib/system/libsystem_pthread.dylib
    0x7fff205b7000 -     0x7fff205f2fff  libdyld.dylib (852) <C10CEA28-D5A0-324F-8F07-8C7CE4805412> /usr/lib/system/libdyld.dylib
    0x7fff205f3000 -     0x7fff205fcfff  libsystem_platform.dylib (254.80.2) <8664A4CD-EE27-3C71-B5CC-06E2B1B4F394> /usr/lib/system/libsystem_platform.dylib
    0x7fff205fd000 -     0x7fff20628fff  libsystem_info.dylib (542.40.3) <EA3F9C9C-3116-3DB4-A3F1-5B03172C1E72> /usr/lib/system/libsystem_info.dylib
    0x7fff20629000 -     0x7fff20ac6fff  com.apple.CoreFoundation (6.9 - 1776.103) <01EFB7F8-BCE6-32DF-A0B8-02F9027F882C> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff20ac7000 -     0x7fff20cfbfff  com.apple.LaunchServices (1122.38 - 1122.38) <241B3D82-2C9C-3F7D-88BD-AC78A689FF04> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff20cfc000 -     0x7fff20dcffff  com.apple.gpusw.MetalTools (1.0 - 1) <03202B68-E515-3CBE-AC5A-39E80A702A6F> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff20dd0000 -     0x7fff2102cfff  libBLAS.dylib (1336.120.1) <44514FE9-B994-380E-8341-4ABA30DB8895> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff2102d000 -     0x7fff2107afff  com.apple.Lexicon-framework (1.0 - 86.2) <F69DF515-4980-36C8-9F5D-987B67D2AFAF> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff2107b000 -     0x7fff210e9fff  libSparse.dylib (106) <E7F273C0-18F8-3688-9B63-C86DEB06740A> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff210ea000 -     0x7fff21167fff  com.apple.SystemConfiguration (1.20 - 1.20) <81EDA68C-051A-3F4C-B79E-B53B365B67B1> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff21168000 -     0x7fff2119cfff  libCRFSuite.dylib (50) <703BB228-D959-3009-AF3F-0015588F531A> /usr/lib/libCRFSuite.dylib
    0x7fff2119d000 -     0x7fff213d5fff  libmecabra.dylib (929.10) <43C2A11F-7F68-31B6-AD65-31282837DED3> /usr/lib/libmecabra.dylib
    0x7fff213d6000 -     0x7fff21734fff  com.apple.Foundation (6.9 - 1776.103) <3C3B967D-778D-30BF-A3F8-E734FAFD76F2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21735000 -     0x7fff2181dfff  com.apple.LanguageModeling (1.0 - 247.3) <58ACD840-A17B-3CB0-B010-7E4493C5BC5C> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff2181e000 -     0x7fff21954fff  com.apple.CoreDisplay (237.3 - 237.3) <65322ECF-632D-362D-870D-5CE69B1B6C60> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff21955000 -     0x7fff21bc5fff  com.apple.audio.AudioToolboxCore (1.0 - 1181.68) <87BA778B-6634-30D8-BF69-678C36246242> /System/Library/PrivateFrameworks/AudioToolboxCore.framework/Versions/A/AudioToolboxCore
    0x7fff21bc6000 -     0x7fff21dabfff  com.apple.CoreText (677.5.0.5 - 677.5.0.5) <C148A259-D01A-3634-9449-119EB084ABA9> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21dac000 -     0x7fff2243cfff  com.apple.audio.CoreAudio (5.0 - 5.0) <E987DC18-3396-3AAD-A66A-2B755C8D242A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2243d000 -     0x7fff22791fff  com.apple.security (7.0 - 59754.120.12) <7C3D689E-9B3E-3F73-ACF0-F40C1297D180> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff22792000 -     0x7fff229f1fff  libicucore.A.dylib (66112) <9957A773-012E-3ABA-9587-CFF787170AE8> /usr/lib/libicucore.A.dylib
    0x7fff229f2000 -     0x7fff229fbfff  libsystem_darwin.dylib (1439.100.3) <BF5B5FD8-B5A3-3035-8641-466E625A6CE8> /usr/lib/system/libsystem_darwin.dylib
    0x7fff229fc000 -     0x7fff22ce7fff  com.apple.CoreServices.CarbonCore (1307.3 - 1307.3) <1C5425B5-0E8C-3691-99AB-44F17F357C81> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff22ce8000 -     0x7fff22d26fff  com.apple.CoreServicesInternal (476.1.1 - 476.1.1) <6CF5F363-4653-3605-A340-363C743BBEDD> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff22d27000 -     0x7fff22d61fff  com.apple.CSStore (1122.38 - 1122.38) <A664672F-440D-3BA8-8851-68B4C6AB1022> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
    0x7fff22d62000 -     0x7fff22e10fff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <C6E70E82-8508-3515-ACE1-361E575D466A> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22e11000 -     0x7fff22e1cfff  libsystem_notify.dylib (279.40.4) <7FFECC25-FA84-3B59-9CC8-4D9DC84E6EC1> /usr/lib/system/libsystem_notify.dylib
    0x7fff22e1d000 -     0x7fff22e6afff  libsandbox.1.dylib (1441.120.5) <F4FF5F3E-6533-3BD5-8EF1-D298E0C954F6> /usr/lib/libsandbox.1.dylib
    0x7fff22e6b000 -     0x7fff23bb3fff  com.apple.AppKit (6.9 - 2022.50.114) <02279013-2888-3A1D-8F28-0C39A64EF5FA> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff23bb4000 -     0x7fff23e02fff  com.apple.UIFoundation (1.0 - 728.8) <A901F2AB-A1C3-3BDB-A2ED-33CAEC118589> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff23e03000 -     0x7fff23e15fff  com.apple.UniformTypeIdentifiers (637 - 637) <8DEE5893-C380-335B-B3DA-DD49DA8FB037> /System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/UniformTypeIdentifiers
    0x7fff23e16000 -     0x7fff23fa0fff  com.apple.desktopservices (1.20 - 1346.5.1) <E4F2E32A-6D94-35D5-B510-44C604236A64> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff24280000 -     0x7fff24906fff  libnetwork.dylib (2288.121.1) <728F736C-8AB2-30C0-8E61-A84F34642B18> /usr/lib/libnetwork.dylib
    0x7fff24907000 -     0x7fff24da5fff  com.apple.CFNetwork (1240.0.4 - 1240.0.4) <83684BEF-A3CE-3227-8E10-A8A538CCA9AE> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff24da6000 -     0x7fff24db4fff  libsystem_networkextension.dylib (1295.120.5) <02486B74-EAAD-3055-AE20-F12E79B39297> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24db5000 -     0x7fff24db5fff  libenergytrace.dylib (22.100.1) <7039CE14-0DED-3FD3-A540-A01DEFC4314D> /usr/lib/libenergytrace.dylib
    0x7fff24db6000 -     0x7fff24e12fff  libMobileGestalt.dylib (978.120.1) <9FF187B8-854F-338D-BD6A-AE142C815617> /usr/lib/libMobileGestalt.dylib
    0x7fff24e13000 -     0x7fff24e29fff  libsystem_asl.dylib (385) <B3E89650-A7FE-3E93-8A1B-D88145FDD45C> /usr/lib/system/libsystem_asl.dylib
    0x7fff24e2a000 -     0x7fff24e41fff  com.apple.TCC (1.0 - 1) <5D202FF3-7BD8-3384-A8AB-7D62CD14C412> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff24e42000 -     0x7fff251a6fff  com.apple.SkyLight (1.600.0 - 588.1) <D5925B80-2468-3709-9DFD-BEAF418169EC> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff251a7000 -     0x7fff25830fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <8E1776B9-0046-3FCF-BF54-F76490EA4A27> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff25831000 -     0x7fff25927fff  com.apple.ColorSync (4.13.0 - 3473.4.3) <CB975116-61F8-330F-B111-3F0467F88BC1> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff25928000 -     0x7fff25983fff  com.apple.HIServices (1.22 - 716) <132B9E44-BF23-3B61-96F2-7678C81115AA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff25d2a000 -     0x7fff26149fff  com.apple.CoreData (120 - 1048) <D3DAFFD5-CC38-3A82-B138-015DBFD551D9> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff2614a000 -     0x7fff2615ffff  com.apple.ProtocolBuffer (1 - 285.24.10.20.1) <C92547DE-86B8-3734-A17D-D0F9B4AE1300> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff26160000 -     0x7fff26313fff  libsqlite3.dylib (321.3) <E9324AF2-968F-3459-A0EB-2FD4E8A3BF09> /usr/lib/libsqlite3.dylib
    0x7fff26314000 -     0x7fff26390fff  com.apple.Accounts (113 - 113) <E31BCCDB-C1E3-3C74-9527-EF1643FF6224> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff26391000 -     0x7fff263a8fff  com.apple.commonutilities (8.0 - 900) <4EBBE25A-3599-3DC8-B846-F90BD23FED85> /System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities
    0x7fff263a9000 -     0x7fff26428fff  com.apple.BaseBoard (526 - 526) <ECED5758-3FD9-3F09-8E55-2230E391373A> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff26429000 -     0x7fff26471fff  com.apple.RunningBoardServices (1.0 - 505.100.8) <F72D5FDE-6DC0-3068-AD08-CA8D165E574D> /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices
    0x7fff26472000 -     0x7fff264e6fff  com.apple.AE (918.6 - 918.6) <A9B7A6D0-85CE-31CD-8926-81D3A714AF42> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff264e7000 -     0x7fff264edfff  libdns_services.dylib (1310.120.71) <6F77A4C7-40B9-3062-8650-6E1E2FD07046> /usr/lib/libdns_services.dylib
    0x7fff264ee000 -     0x7fff264f5fff  libsystem_symptoms.dylib (1431.120.1) <3BEA5355-D267-39D4-8BC6-A1703845BD3F> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff264f6000 -     0x7fff26681fff  com.apple.Network (1.0 - 1) <39B5F4D8-5105-37CB-9F18-2B2C36CB4B42> /System/Library/Frameworks/Network.framework/Versions/A/Network
    0x7fff26682000 -     0x7fff266b1fff  com.apple.analyticsd (1.0 - 1) <2DABBC97-042F-39C7-85A5-A6F47BCAC5EC> /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics
    0x7fff266b2000 -     0x7fff266b4fff  libDiagnosticMessagesClient.dylib (112) <8D0655AC-218F-3AA6-9802-2444E6801067> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff266b5000 -     0x7fff26701fff  com.apple.spotlight.metadata.utilities (1.0 - 2150.21) <7CE4BC56-65ED-3D75-8DA0-05EFE1BA2256> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff26702000 -     0x7fff2679cfff  com.apple.Metadata (10.7.0 - 2150.21) <04F83B90-3535-326F-8897-D43F55DDE771> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff2679d000 -     0x7fff267a3fff  com.apple.DiskArbitration (2.7 - 2.7) <97F9E5D9-0942-3AD6-8D31-65106C452CB8> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff267a4000 -     0x7fff26e0bfff  com.apple.vImage (8.1 - 544.4) <A711FD44-1495-3D7B-BF5C-E238C17B1A79> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff26e0c000 -     0x7fff270e8fff  com.apple.QuartzCore (1.11 - 927.21) <F384A0C0-F855-3B4D-AAD0-E0F0550E226C> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff270e9000 -     0x7fff2712afff  libFontRegistry.dylib (309) <5D9848B3-14C7-34A8-A981-B3C2CFD12BD9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff2712b000 -     0x7fff2726bfff  com.apple.coreui (2.1 - 692.1) <76D85525-8D99-3F0F-BC36-DEA342D4589D> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff2726c000 -     0x7fff27357fff  com.apple.ViewBridge (553.1 - 553.1) <21A4A790-5A90-3C45-979E-9CF3ED9E8092> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff27358000 -     0x7fff27363fff  com.apple.PerformanceAnalysis (1.278.3 - 278.3) <3FE8B4FD-B159-38B0-BA07-DE6722AC9F55> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff27364000 -     0x7fff27373fff  com.apple.OpenDirectory (11.4 - 230.40.1) <32596EC3-5500-3B18-ABCD-D92EDEDE74BF> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff27374000 -     0x7fff27393fff  com.apple.CFOpenDirectory (11.4 - 230.40.1) <3AA364D1-58AE-3C8D-B897-5B4AC3256BE7> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff27394000 -     0x7fff273a0fff  com.apple.CoreServices.FSEvents (1290.120.5 - 1290.120.5) <4C4959DF-FE61-30E8-8BBB-3BF674BE203A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff273a1000 -     0x7fff273c5fff  com.apple.coreservices.SharedFileList (144 - 144) <4418DDA1-CA34-3402-97F2-CE9B60019617> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff273c6000 -     0x7fff273c8fff  libapp_launch_measurement.dylib (14.1) <78905455-A807-3D67-AD56-FF8C22D31B16> /usr/lib/libapp_launch_measurement.dylib
    0x7fff273c9000 -     0x7fff27410fff  com.apple.CoreAutoLayout (1.0 - 21.10.1) <E848DF1F-1C82-3F04-87B8-9BF0C956A587> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/Versions/A/CoreAutoLayout
    0x7fff27411000 -     0x7fff274f3fff  libxml2.2.dylib (34.9) <08E7CAB2-0EED-376C-880A-E52CC01E82F3> /usr/lib/libxml2.2.dylib
    0x7fff274f4000 -     0x7fff27541fff  com.apple.CoreVideo (1.8 - 414.7) <29D4EA46-F0B6-3004-863C-0940ACD200C2> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff27542000 -     0x7fff27544fff  com.apple.loginsupport (1.0 - 1) <02FCC3AF-1E2D-3603-9D6F-33589ED28A00> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff27545000 -     0x7fff2756cfff  com.apple.aps.framework (4.0 - 4.0) <6BF45799-EAA7-3F54-B3BB-501F40B0F62F> /System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService
    0x7fff2756d000 -     0x7fff27588fff  com.apple.UserManagement (1.0 - 1) <12F6D91A-C660-37CD-90E7-A0137393F080> /System/Library/PrivateFrameworks/UserManagement.framework/Versions/A/UserManagement
    0x7fff27589000 -     0x7fff2771afff  com.apple.cloudkit.CloudKit (985 - 985) <B6A0F4FE-3993-3646-B79C-0F34D2AB7F49> /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
    0x7fff2847f000 -     0x7fff284fbfff  com.apple.corelocation (2420.19.23 - 2420.19.23) <0D8A0FDD-86BA-30B9-B5A2-0755D880CB2F> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff284fc000 -     0x7fff2850cfff  libsystem_containermanager.dylib (318.100.4) <2BBFF58C-D27E-3371-968D-7DE1E53749F6> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff2850d000 -     0x7fff2851efff  com.apple.IOSurface (290.8.1 - 290.8.1) <BA97183F-8EE4-3833-8AA7-06D9B9D39BDF> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff2851f000 -     0x7fff28528fff  com.apple.IOAccelerator (442.9 - 442.9) <91FA0C86-BD36-373C-B91A-7360D27CA614> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff28529000 -     0x7fff2864cfff  com.apple.Metal (244.201 - 244.201) <5197E017-D6CD-3611-A8B5-76A4FB901C6A> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff2864d000 -     0x7fff28669fff  com.apple.audio.caulk (1.0 - 70) <B6AB0B5B-ED36-3567-8112-5C9DEDBFBBFA> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7fff2866a000 -     0x7fff28754fff  com.apple.CoreMedia (1.0 - 2775.22) <9C15E6D0-245E-3A6E-BC67-C1DF67F7EB2A> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff28755000 -     0x7fff288b5fff  libFontParser.dylib (305.5.0.1) <DFE3F79C-849C-3FC7-AFC0-24AB83171A36> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
    0x7fff288b6000 -     0x7fff28bb1fff  com.apple.HIToolbox (2.1.1 - 1061.11) <DFAA0674-E367-36D9-925A-4EA9A6954BB0> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff28bb2000 -     0x7fff28bc5fff  com.apple.framework.DFRFoundation (1.0 - 266) <0B60B894-C5A5-38F0-8755-53BD217B0E36> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff28bc6000 -     0x7fff28bc9fff  com.apple.dt.XCTTargetBootstrap (1.0 - 18119.1) <8828FD40-9EE5-3E09-9DD7-8B7E34B34C26> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff28bca000 -     0x7fff28bf3fff  com.apple.CoreSVG (1.0 - 149) <BA347BBA-DC27-3728-9728-A791957D3F59> /System/Library/PrivateFrameworks/CoreSVG.framework/Versions/A/CoreSVG
    0x7fff28bf4000 -     0x7fff28e30fff  com.apple.ImageIO (3.3.0 - 2130.5.4) <14E0D520-1EE1-3C80-9827-4E5F513A7289> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff28e31000 -     0x7fff291acfff  com.apple.CoreImage (16.3.0 - 1140.2) <4A5B2859-C1F7-3938-B4B6-DDEC972798D1> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff291ad000 -     0x7fff29213fff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <20902DA8-4AAB-36C8-9224-4F9E828B465A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff29214000 -     0x7fff29217fff  libsystem_configuration.dylib (1109.120.1) <C7A9BD10-192B-31D3-92ED-2581A61A99F6> /usr/lib/system/libsystem_configuration.dylib
    0x7fff29218000 -     0x7fff2921cfff  libsystem_sandbox.dylib (1441.120.5) <DC075A7C-9D4A-32D3-9022-CD47764AFDAD> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff2921d000 -     0x7fff2921efff  com.apple.AggregateDictionary (1.0 - 1) <4394E8DB-F6D9-3F85-B894-F463378DC1B4> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff2921f000 -     0x7fff29222fff  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <1826DE1C-06B1-3140-A9A2-F7D55C1D9DB6> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff29223000 -     0x7fff29224fff  liblangid.dylib (136) <ADE3A41C-F815-39DE-A978-1B0EE456167B> /usr/lib/liblangid.dylib
    0x7fff29225000 -     0x7fff292c9fff  com.apple.CoreNLP (1.0 - 245.2) <9B1C60E4-2B36-34A7-AF43-7EEC914FA1FE> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff292ca000 -     0x7fff292d0fff  com.apple.LinguisticData (1.0 - 399) <48C87E01-670A-336C-9D37-723E06BE422D> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff292d1000 -     0x7fff29979fff  libBNNS.dylib (288.100.5) <48BD7046-5DBD-3F3D-AD81-376AD24FA45D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff2997a000 -     0x7fff29b4cfff  libvDSP.dylib (760.100.3) <372AD8C6-F390-3257-A886-D3B545AAB98C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff29b4d000 -     0x7fff29b5efff  com.apple.CoreEmoji (1.0 - 128.4) <677784E7-E4E6-3405-AC53-DD66197C4821> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff29b5f000 -     0x7fff29b69fff  com.apple.IOMobileFramebuffer (343.0.0 - 343.0.0) <A57347A7-1354-3F54-B9EC-E5F83A200AAF> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/Versions/A/IOMobileFramebuffer
    0x7fff29b6a000 -     0x7fff29c3cfff  com.apple.framework.CoreWLAN (16.0 - 1657) <42166AAE-D9EF-3EE6-A0F3-8B3E320BB39E> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff29c3d000 -     0x7fff29e3efff  com.apple.CoreUtils (6.6 - 660.37) <D3F3801B-EC48-3C0B-9438-0C12C4A0BA87> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff29e3f000 -     0x7fff29e61fff  com.apple.MobileKeyBag (2.0 - 1.0) <1FCEE156-0810-3425-88FC-E7EA6B38ACA7> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff29e62000 -     0x7fff29e72fff  com.apple.AssertionServices (1.0 - 505.100.8) <E691B254-0792-348B-BC13-2B1A490174C4> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff29e73000 -     0x7fff29efefff  com.apple.securityfoundation (6.0 - 55240.40.4) <AD930CCB-A3F5-3C2C-A2CD-9963A63560F5> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff29eff000 -     0x7fff29f08fff  com.apple.coreservices.BackgroundTaskManagement (1.0 - 104) <4B88024D-62DB-3E5D-BCA2-076663214608> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff29f09000 -     0x7fff29f0dfff  com.apple.xpc.ServiceManagement (1.0 - 1) <7E760B22-944C-387A-903F-C9184CE788B9> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff29f0e000 -     0x7fff29f10fff  libquarantine.dylib (119.40.2) <4611645F-5817-3A80-8382-2DB03A8C0141> /usr/lib/system/libquarantine.dylib
    0x7fff29f11000 -     0x7fff29f1cfff  libCheckFix.dylib (31) <33CE141E-48F5-3974-BD63-1F63558BB452> /usr/lib/libCheckFix.dylib
    0x7fff29f1d000 -     0x7fff29f34fff  libcoretls.dylib (169.100.1) <68726723-2EA1-3007-89ED-F66725A6AA7E> /usr/lib/libcoretls.dylib
    0x7fff29f35000 -     0x7fff29f45fff  libbsm.0.dylib (68.40.1) <77DF90DF-D5C2-3178-AAA7-96FC6D9F2312> /usr/lib/libbsm.0.dylib
    0x7fff29f46000 -     0x7fff29f8ffff  libmecab.dylib (929.10) <48F1EC4F-7D85-347F-B20C-7225AF2499A4> /usr/lib/libmecab.dylib
    0x7fff29f90000 -     0x7fff29f95fff  libgermantok.dylib (24) <171A100F-C862-3CA2-A308-5AA9EF24B690> /usr/lib/libgermantok.dylib
    0x7fff29f96000 -     0x7fff29fabfff  libLinearAlgebra.dylib (1336.120.1) <09738E52-FA24-3239-895D-F762C920F03C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff29fac000 -     0x7fff2a1cafff  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <C515FA90-1022-308E-A513-0EA9831FE712> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff2a1cb000 -     0x7fff2a21afff  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <1C3D9332-2C1D-3B52-A679-35BC37A3E8F0> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff2a21b000 -     0x7fff2a37cfff  com.apple.MLCompute (1.0 - 1) <0B7ADB41-62BE-32EE-821A-BB7141DE8B42> /System/Library/Frameworks/MLCompute.framework/Versions/A/MLCompute
    0x7fff2a37d000 -     0x7fff2a3b3fff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <D5B2AEEE-3973-35A5-9FF9-1C7C031B7125> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff2a3b4000 -     0x7fff2a40afff  com.apple.MetalPerformanceShaders.MPSNDArray (1.0 - 1) <0E99566D-A21A-304F-AF1A-A9530AED8A92> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray
    0x7fff2a40b000 -     0x7fff2a49bfff  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <1C395A17-2F98-35A5-B768-F22A714100D0> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff2a49c000 -     0x7fff2a4abfff  com.apple.AppleFSCompression (125 - 1.0) <6BD3FF9C-BCEE-3AB9-AC52-71A75D1C54AD> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff2a4ac000 -     0x7fff2a4b8fff  libbz2.1.0.dylib (44) <CA69420A-25E7-344C-852F-808F09AD43D0> /usr/lib/libbz2.1.0.dylib
    0x7fff2a4b9000 -     0x7fff2a4bdfff  libsystem_coreservices.dylib (127.1) <1E2DA16B-D528-3D43-86C2-2BB9127954A0> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a4be000 -     0x7fff2a4ebfff  com.apple.CoreServices.OSServices (1122.38 - 1122.38) <D02BE0AC-0544-3D1F-9E79-37715E231214> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff2a4ec000 -     0x7fff2a61bfff  com.apple.AuthKit (1.0 - 1) <C35AA029-1F96-3F5F-B71C-EF55E59F8F0D> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff2a6ba000 -     0x7fff2a6ccfff  libz.1.dylib (76) <C1E6CE87-167E-39EC-8B8F-2C3213A0208E> /usr/lib/libz.1.dylib
    0x7fff2a6cd000 -     0x7fff2a714fff  libsystem_m.dylib (3186.100.3) <21949128-D4E6-3179-B248-41B05C1CE102> /usr/lib/system/libsystem_m.dylib
    0x7fff2a715000 -     0x7fff2a715fff  libcharset.1.dylib (59) <4B3453D8-277A-38D3-862D-28DF71F3E285> /usr/lib/libcharset.1.dylib
    0x7fff2a716000 -     0x7fff2a71bfff  libmacho.dylib (980) <3677B3B7-03E8-3804-B2FE-5640B18FE40E> /usr/lib/system/libmacho.dylib
    0x7fff2a71c000 -     0x7fff2a737fff  libkxld.dylib (7195.121.3) <A83BCE3F-35C1-34DD-B1C5-B4FDFB33B250> /usr/lib/system/libkxld.dylib
    0x7fff2a738000 -     0x7fff2a743fff  libcommonCrypto.dylib (60178.120.3) <BBA72D86-B9C1-3123-AE59-D629DE278695> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a744000 -     0x7fff2a74efff  libunwind.dylib (201) <3149D79A-911B-39ED-9C93-6C7E6B0860C7> /usr/lib/system/libunwind.dylib
    0x7fff2a74f000 -     0x7fff2a756fff  liboah.dylib (203.46) <0A17EAFC-15E9-37FE-8EE2-DE0F7F220AD8> /usr/lib/liboah.dylib
    0x7fff2a757000 -     0x7fff2a761fff  libcopyfile.dylib (173.40.2) <7304CA0D-E93C-367F-9BEE-AC56B873F06C> /usr/lib/system/libcopyfile.dylib
    0x7fff2a762000 -     0x7fff2a769fff  libcompiler_rt.dylib (102.2) <0DB1902E-C79C-3E26-BE51-F70960ECF0B9> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a76a000 -     0x7fff2a76cfff  libsystem_collections.dylib (1439.100.3) <E180C04A-9CFB-3C8E-9C2B-978D23A99F2A> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a76d000 -     0x7fff2a76ffff  libsystem_secinit.dylib (87.60.1) <8C33D323-C11C-34CB-9295-4D7C98B8AFD6> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a770000 -     0x7fff2a772fff  libremovefile.dylib (49.120.1) <6DEAEEC9-2A65-3C7B-A9CE-23245772FD07> /usr/lib/system/libremovefile.dylib
    0x7fff2a773000 -     0x7fff2a773fff  libkeymgr.dylib (31) <FD167835-3829-3FFD-B13E-D18113E271AB> /usr/lib/system/libkeymgr.dylib
    0x7fff2a774000 -     0x7fff2a77bfff  libsystem_dnssd.dylib (1310.120.71) <7BB607FE-EF79-3144-8BD0-A66792FF1443> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a77c000 -     0x7fff2a781fff  libcache.dylib (83) <8B201058-2C34-3C12-9A7A-898CB0AAD150> /usr/lib/system/libcache.dylib
    0x7fff2a782000 -     0x7fff2a783fff  libSystem.B.dylib (1292.120.1) <A8309074-31CC-31F0-A143-81DF019F7A86> /usr/lib/libSystem.B.dylib
    0x7fff2a784000 -     0x7fff2a787fff  libfakelink.dylib (3) <CF7D19AF-D162-369D-9501-0BEAC4D1188E> /usr/lib/libfakelink.dylib
    0x7fff2a788000 -     0x7fff2a788fff  com.apple.SoftLinking (1.0 - 1) <6C04D3E0-BFE0-32E2-A098-46D726F9B429> /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking
    0x7fff2a789000 -     0x7fff2a7c0fff  libpcap.A.dylib (98.100.3) <87B9769E-D88E-37F9-BB83-B327527AE79C> /usr/lib/libpcap.A.dylib
    0x7fff2a7c1000 -     0x7fff2a8b1fff  libiconv.2.dylib (59) <B9FD3BC7-6001-3E60-A7FB-CE8AAE07C805> /usr/lib/libiconv.2.dylib
    0x7fff2a8b2000 -     0x7fff2a8c3fff  libcmph.dylib (8) <AE1C3A87-5C44-3833-9DE1-31062A878138> /usr/lib/libcmph.dylib
    0x7fff2a8c4000 -     0x7fff2a935fff  libarchive.2.dylib (83.100.2) <5DF98631-FBAC-3F17-B4D1-0115CE6C009B> /usr/lib/libarchive.2.dylib
    0x7fff2a936000 -     0x7fff2a99dfff  com.apple.SearchKit (1.4.1 - 1.4.1) <FBAB58C4-1B62-39E8-9241-93966CC2C9C0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff2a99e000 -     0x7fff2a99ffff  libThaiTokenizer.dylib (3) <1D735582-F932-3279-9F47-D10EAD1CA9A2> /usr/lib/libThaiTokenizer.dylib
    0x7fff2a9a0000 -     0x7fff2a9c2fff  com.apple.applesauce (1.0 - 16.28) <F07DA929-24FA-36D3-A356-05C9565AC397> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff2a9c3000 -     0x7fff2a9dafff  libapple_nghttp2.dylib (1.41) <303C40AC-4212-3B20-ABF6-91F46A79B78B> /usr/lib/libapple_nghttp2.dylib
    0x7fff2a9db000 -     0x7fff2a9f1fff  libSparseBLAS.dylib (1336.120.1) <3C4D290C-13A4-3A3D-B7C9-3BA0A4C9C7A5> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff2a9f2000 -     0x7fff2a9f3fff  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <9D78B798-7218-3327-8E50-CF321EDB22B1> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff2a9f4000 -     0x7fff2a9f8fff  libpam.2.dylib (28.40.1) <A04A5DD4-34DE-3BFB-BB17-BD66F7FBA1B6> /usr/lib/libpam.2.dylib
    0x7fff2a9f9000 -     0x7fff2aa18fff  libcompression.dylib (96.120.1) <591F0E34-3C41-3D94-98BA-9BB50E608787> /usr/lib/libcompression.dylib
    0x7fff2aa19000 -     0x7fff2aa1efff  libQuadrature.dylib (7) <FD523210-15BE-3EE7-B2E2-892A7E198542> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff2aa1f000 -     0x7fff2adbcfff  libLAPACK.dylib (1336.120.1) <3F036666-341C-3570-8136-CDF170C02DE7> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff2adbd000 -     0x7fff2ae0cfff  com.apple.DictionaryServices (1.2 - 341) <3EC1918E-0345-3EC6-BAE0-04B94A0B6809> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff2ae0d000 -     0x7fff2ae25fff  liblzma.5.dylib (16) <10B7343A-0322-3A1F-B6AE-06FC709F1BDE> /usr/lib/liblzma.5.dylib
    0x7fff2ae26000 -     0x7fff2ae27fff  libcoretls_cfhelpers.dylib (169.100.1) <BACFE067-CAAB-3906-AAE5-A5E78CD22C6D> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff2ae28000 -     0x7fff2af23fff  com.apple.APFS (1677.120.9 - 1677.120.9) <599AAB82-F105-3ACC-BBFA-2D3D276A312C> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff2af24000 -     0x7fff2af31fff  libxar.1.dylib (452) <C5B63994-6F92-395D-9431-1574D6E1D89F> /usr/lib/libxar.1.dylib
    0x7fff2af32000 -     0x7fff2af35fff  libutil.dylib (58.40.2) <4D8FD41B-89A5-31DA-BB0E-7F13C3B1652F> /usr/lib/libutil.dylib
    0x7fff2af36000 -     0x7fff2af5efff  libxslt.1.dylib (17.4) <CADFABB2-F66B-39FF-B43A-17315815F664> /usr/lib/libxslt.1.dylib
    0x7fff2af5f000 -     0x7fff2af69fff  libChineseTokenizer.dylib (37.1) <44E1A716-E405-3E54-874F-C5011146B318> /usr/lib/libChineseTokenizer.dylib
    0x7fff2af6a000 -     0x7fff2b027fff  libvMisc.dylib (760.100.3) <E92C2BF3-02A5-31D1-BF6A-56BBA624CA90> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff2b028000 -     0x7fff2b0bffff  libate.dylib (3.0.6) <C73DF462-D92F-366F-ADBE-B140698DEBAF> /usr/lib/libate.dylib
    0x7fff2b0c0000 -     0x7fff2b0c7fff  libIOReport.dylib (64.100.1) <E7BCECCB-2F51-3A07-9C56-4EF4AFD59C80> /usr/lib/libIOReport.dylib
    0x7fff2b0c8000 -     0x7fff2b0dbfff  com.apple.CrashReporterSupport (10.13 - 15053) <14AF971D-F684-32BD-8BB6-BE9C4A01DDA5> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff2b1c9000 -     0x7fff2b1d0fff  libMatch.1.dylib (38) <121C98B5-D188-3E02-890D-F4F2CD91D2F2> /usr/lib/libMatch.1.dylib
    0x7fff2b1d1000 -     0x7fff2b25cfff  libCoreStorage.dylib (554) <3888A24D-7E72-3B58-A252-85373AFF3CE4> /usr/lib/libCoreStorage.dylib
    0x7fff2b25d000 -     0x7fff2b2b0fff  com.apple.AppleVAFramework (6.1.3 - 6.1.3) <D39DBE46-4BEB-316F-BAFA-8E2B03BED772> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff2b2b1000 -     0x7fff2b2c9fff  libexpat.1.dylib (26) <C0213844-67CA-38E7-A586-456A645E0BD0> /usr/lib/libexpat.1.dylib
    0x7fff2b2ca000 -     0x7fff2b2d3fff  libheimdal-asn1.dylib (597.121.1) <493CC99B-8939-3F7E-852C-9AB59B0DDC11> /usr/lib/libheimdal-asn1.dylib
    0x7fff2b2d4000 -     0x7fff2b2e8fff  com.apple.IconFoundation (479.4 - 479.4) <C0C5765F-6A1F-3D89-9AEE-5D49520CAAFD> /System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/IconFoundation
    0x7fff2b2e9000 -     0x7fff2b355fff  com.apple.IconServices (479.4 - 479.4) <8D31CC1A-C609-30EC-BCC3-251F7E4CDC10> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff2b356000 -     0x7fff2b3f4fff  com.apple.MediaExperience (1.0 - 1) <29CF7489-BA27-3789-95A2-F94CC6F09E7A> /System/Library/PrivateFrameworks/MediaExperience.framework/Versions/A/MediaExperience
    0x7fff2b3f5000 -     0x7fff2b41dfff  com.apple.persistentconnection (1.0 - 1.0) <5E4A9EC5-2E54-3EFF-A330-52C0D42B26AA> /System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection
    0x7fff2b41e000 -     0x7fff2b42cfff  com.apple.GraphVisualizer (1.0 - 100.1) <FFB7E9D0-F1D6-38E9-8BAD-759C3BFEE379> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff2b42d000 -     0x7fff2b848fff  com.apple.vision.FaceCore (4.3.2 - 4.3.2) <5A226A22-20F0-3196-915F-5DF94E1B3070> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff2b849000 -     0x7fff2b890fff  com.apple.OTSVG (1.0 - 677.5.0.5) <2E8C5AAB-E14B-3FC4-8872-332690419934> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff2b891000 -     0x7fff2b897fff  com.apple.xpc.AppServerSupport (1.0 - 2038.120.1) <256FB87D-3DD1-3B42-B095-B2E5FC3A755B> /System/Library/PrivateFrameworks/AppServerSupport.framework/Versions/A/AppServerSupport
    0x7fff2b898000 -     0x7fff2b8aafff  libhvf.dylib (1.0 - $[CURRENT_PROJECT_VERSION]) <C97DAB60-EA72-3822-A5F7-AF29C05DC1DD> /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
    0x7fff2b8ab000 -     0x7fff2b8adfff  libspindump.dylib (295.2) <63167B4A-D7D5-3146-86B6-988FC0AD4F14> /usr/lib/libspindump.dylib
    0x7fff2b8ae000 -     0x7fff2b96efff  com.apple.Heimdal (4.0 - 2.0) <B7D2D628-4503-3229-BFB4-FF60066104C1> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff2b96f000 -     0x7fff2b989fff  com.apple.login (3.0 - 3.0) <5D551803-8EF3-3F1F-9329-B35D3E017D25> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff2bb0e000 -     0x7fff2bb4afff  com.apple.bom (14.0 - 235) <B6D5DB5C-7E5B-3D1A-993B-06EDA9728BD9> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff2bb4b000 -     0x7fff2bb94fff  com.apple.AppleJPEG (1.0 - 1) <BE3058DB-0D49-3331-87A7-36D4651F143B> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff2bb95000 -     0x7fff2bc74fff  libJP2.dylib (2130.5.4) <E1F1DA3E-2EC4-3AC9-8171-E4777A9F5DBD> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff2bc75000 -     0x7fff2bc78fff  com.apple.WatchdogClient.framework (1.0 - 98.120.2) <DE7F64ED-82D2-325D-A031-0E805D52514C> /System/Library/PrivateFrameworks/WatchdogClient.framework/Versions/A/WatchdogClient
    0x7fff2bc79000 -     0x7fff2bcaffff  com.apple.MultitouchSupport.framework (4440.3 - 4440.3) <C22A0497-19D3-3365-8F59-9190C510F4BE> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff2bcb0000 -     0x7fff2be0efff  com.apple.VideoToolbox (1.0 - 2775.22) <88A013B6-FAB1-3BF9-A5C0-A92D8951E9E3> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2be0f000 -     0x7fff2be42fff  libAudioToolboxUtility.dylib (1181.68) <2AF3BF70-DCEC-3884-A75A-DDEF1F304964> /usr/lib/libAudioToolboxUtility.dylib
    0x7fff2be43000 -     0x7fff2be69fff  libPng.dylib (2130.5.4) <3D6AEF53-5D8E-3F8B-B80E-71D848BFD35F> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff2be6a000 -     0x7fff2bec9fff  libTIFF.dylib (2130.5.4) <F4B52A0F-2EF6-30BE-9870-CD2E8B5C3318> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff2beca000 -     0x7fff2bee6fff  com.apple.IOPresentment (58 - 37) <994E2AE6-D25E-32D5-9ABA-5A1979A659FE> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff2bee7000 -     0x7fff2beeefff  com.apple.GPUWrangler (6.3.3 - 6.3.3) <768299B7-C4B5-307D-A413-52DA0C269A9D> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff2beef000 -     0x7fff2bef2fff  libRadiance.dylib (2130.5.4) <5C83C72F-9F7B-341D-ADD7-DA12A728C9EA> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff2bef3000 -     0x7fff2bef8fff  com.apple.DSExternalDisplay (3.1 - 380) <AA11B104-262F-33B2-8564-EF47D24AC2B6> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff2bef9000 -     0x7fff2bf1dfff  libJPEG.dylib (2130.5.4) <70213D93-137E-39CE-82C9-BC238226AC05> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff2bf1e000 -     0x7fff2bf4dfff  com.apple.ATSUI (1.0 - 1) <63C289D7-9FD8-370D-9DFB-9C2B50E7978A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/ATSUI
    0x7fff2bf4e000 -     0x7fff2bf52fff  libGIF.dylib (2130.5.4) <961F6A97-AF22-3A45-BDCF-A425C23CA01A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff2bf53000 -     0x7fff2bf5cfff  com.apple.CMCaptureCore (1.0 - 82.6) <694884AA-070C-3EE5-B86C-F09ABB93A7D7> /System/Library/PrivateFrameworks/CMCaptureCore.framework/Versions/A/CMCaptureCore
    0x7fff2bf5d000 -     0x7fff2bfa4fff  com.apple.print.framework.PrintCore (16.1 - 531.1) <9D0760A9-DAE8-3BB5-AE31-4D945BA39D48> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff2bfa5000 -     0x7fff2c072fff  com.apple.TextureIO (3.10.9 - 3.10.9) <B68C877B-2BE2-3338-AACA-52DDD955017A> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff2c073000 -     0x7fff2c07bfff  com.apple.InternationalSupport (1.0 - 61.1) <0C4AFFAF-D59F-3B3E-A433-CE03BDE567A8> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff2c07c000 -     0x7fff2c0f6fff  com.apple.datadetectorscore (8.0 - 674) <2FC62BC9-F63C-30DB-BFEE-3CB8399D7F18> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff2c0f7000 -     0x7fff2c154fff  com.apple.UserActivity (439 - 439) <2C4D4B39-FA93-3ED5-8417-ACBE6C39BB92> /System/Library/PrivateFrameworks/UserActivity.framework/Versions/A/UserActivity
    0x7fff2c155000 -     0x7fff2c8effff  com.apple.MediaToolbox (1.0 - 2775.22) <F5CC3EEC-294B-3B88-BEF1-63BEF846EFF0> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff2cd30000 -     0x7fff2cd96fff  com.apple.imfoundation (10.0 - 1000) <340BD2E2-35E1-3C52-B41D-708DD38554AF> /System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation
    0x7fff2cd97000 -     0x7fff2cdbffff  com.apple.locationsupport (2420.19.23 - 2420.19.23) <E303FCD8-5B5D-3367-B7B3-144FA7002E24> /System/Library/PrivateFrameworks/LocationSupport.framework/Versions/A/LocationSupport
    0x7fff2cdc0000 -     0x7fff2cdf1fff  libSessionUtility.dylib (76.69) <143B9D4F-FDB1-3366-A20C-4B09A05FE862> /System/Library/PrivateFrameworks/AudioSession.framework/libSessionUtility.dylib
    0x7fff2cdf2000 -     0x7fff2cf26fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <1ABFDEA2-FB20-3E05-B4CC-84A2A796D089> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2cf27000 -     0x7fff2cf8cfff  com.apple.audio.AudioSession (1.0 - 76.69) <8D52DAFF-EBE7-3631-A645-E5CD509591A0> /System/Library/PrivateFrameworks/AudioSession.framework/Versions/A/AudioSession
    0x7fff2cf8d000 -     0x7fff2cf9ffff  libAudioStatistics.dylib (27.64) <0EF059FC-B386-3595-8BB5-57F0CADAA75F> /usr/lib/libAudioStatistics.dylib
    0x7fff2cfa0000 -     0x7fff2cfaffff  com.apple.speech.synthesis.framework (9.0.65 - 9.0.65) <4E88057A-948F-335D-9675-AAEC73F7DE6A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff2cfb0000 -     0x7fff2d01cfff  com.apple.ApplicationServices.ATS (377 - 516) <9DFEBC18-3BA6-3588-A5C5-6D974DF284A2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff2d01d000 -     0x7fff2d035fff  libresolv.9.dylib (68) <0E0E7298-2781-3D72-B40F-5FF7DE7DF068> /usr/lib/libresolv.9.dylib
    0x7fff2d036000 -     0x7fff2d049fff  libsasl2.2.dylib (214) <8A235B0C-CE89-3C11-8329-AF081227BB92> /usr/lib/libsasl2.2.dylib
    0x7fff2d168000 -     0x7fff2d247fff  libSMC.dylib (20) <7B4581C7-3E3F-33F7-AC74-BFC57A2991C4> /usr/lib/libSMC.dylib
    0x7fff2d248000 -     0x7fff2d2a7fff  libcups.2.dylib (494.1) <C96214CD-19F2-334A-95A0-25BA714D984A> /usr/lib/libcups.2.dylib
    0x7fff2d2a8000 -     0x7fff2d2b7fff  com.apple.LangAnalysis (1.7.0 - 254) <C53922F5-BD54-3594-9DCF-DF6D0379B40D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff2d2b8000 -     0x7fff2d2c2fff  com.apple.NetAuth (6.2 - 6.2) <32C039EF-D063-3F2B-B4AC-3103593A7D4E> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff2d2c3000 -     0x7fff2d2cafff  com.apple.ColorSyncLegacy (4.13.0 - 1) <6B94034B-8D84-3700-96D3-7A3208231BE9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff2d2cb000 -     0x7fff2d2d6fff  com.apple.QD (4.0 - 416) <AA06F3E8-FC88-3501-B05C-F2D0C4F56272> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff2d2d7000 -     0x7fff2d92bfff  com.apple.audio.AudioResourceArbitration (1.0 - 1) <21EB0A40-BA39-3423-AA4F-2E2A771157C1> /System/Library/PrivateFrameworks/AudioResourceArbitration.framework/Versions/A/AudioResourceArbitration
    0x7fff2d92c000 -     0x7fff2d937fff  com.apple.perfdata (1.0 - 67.40.1) <9D1542E2-52D5-3372-8F2B-B71E27E8050B> /System/Library/PrivateFrameworks/perfdata.framework/Versions/A/perfdata
    0x7fff2d938000 -     0x7fff2d946fff  libperfcheck.dylib (41) <AE0793DA-378F-343E-82AC-EEFBE0FF1818> /usr/lib/libperfcheck.dylib
    0x7fff2d947000 -     0x7fff2d956fff  com.apple.Kerberos (3.0 - 1) <6D0BA11B-3659-36F0-983E-5D0E51B25912> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff2d957000 -     0x7fff2d9a7fff  com.apple.GSS (4.0 - 2.0) <398B2978-DB62-3D24-A5DA-36599C401D7F> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff2d9a8000 -     0x7fff2d9b8fff  com.apple.CommonAuth (4.0 - 2.0) <A48CDBF5-8251-35AF-90F8-6FD9D64DA2D8> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff2d9b9000 -     0x7fff2d9e0fff  com.apple.MobileAssets (1.0 - 659.100.21) <4D326D1D-8AF7-3D30-841A-E7D0E549B146> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff2da0e000 -     0x7fff2da2dfff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <8493160A-57F2-37E2-8482-FE1619630B59> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff2da2e000 -     0x7fff2da36fff  com.apple.CorePhoneNumbers (1.0 - 1) <514729CE-5C41-3B60-888B-C7267C51B11F> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff2db89000 -     0x7fff2db89fff  liblaunch.dylib (2038.120.1) <FB6430FC-AACB-3AFF-8763-4C5AFABEF40E> /usr/lib/system/liblaunch.dylib
    0x7fff2e10e000 -     0x7fff2e20ffff  com.apple.ids (10.0 - 1000) <D603E099-0762-3528-8862-371F7F53BC8F> /System/Library/PrivateFrameworks/IDS.framework/Versions/A/IDS
    0x7fff2e210000 -     0x7fff2e36afff  com.apple.idsfoundation (10.0 - 1000) <1ECCE9AC-1672-3D62-945A-4FF0C09456D2> /System/Library/PrivateFrameworks/IDSFoundation.framework/Versions/A/IDSFoundation
    0x7fff2e36b000 -     0x7fff2e4b6fff  com.apple.Sharing (1622.1 - 1622.1) <B931F6D8-4831-34ED-A909-BEB824ADF533> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff2e4b7000 -     0x7fff2e5d8fff  com.apple.Bluetooth (8.0.5 - 8.0.5d7) <7630620F-575C-37A6-ACAA-3B9443127E88> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff2e5f2000 -     0x7fff2e64bfff  com.apple.ProtectedCloudStorage (1.0 - 1) <56DAAA40-66D4-3551-B196-B39604874CAA> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fff2e8ab000 -     0x7fff2fd9efff  com.apple.GeoServices (1.0 - 1757.25.3.15.4) <4507DDFE-EFF6-324D-A2BE-7D3FC044C58F> /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
    0x7fff2fdab000 -     0x7fff2fdd2fff  com.apple.RemoteViewServices (2.0 - 163) <2D91746F-1F8B-3D03-BED1-C1BD7FA14453> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff2fdd3000 -     0x7fff2fde2fff  com.apple.SpeechRecognitionCore (6.1.24 - 6.1.24) <4FD3C300-7679-3E30-BC40-5DC933BC287E> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff2fde3000 -     0x7fff2fdeafff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <F2C2E4FC-0EE0-38CC-AC0F-8F412A2859EE> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff30018000 -     0x7fff30018fff  libsystem_product_info_filter.dylib (8.40.1) <D5194AB1-61C4-3C8D-9E3C-C65702BAB859> /usr/lib/system/libsystem_product_info_filter.dylib
    0x7fff300f0000 -     0x7fff300f0fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <E0B5CB04-F282-3BF0-8D14-BE6E3ED7C0A2> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff30116000 -     0x7fff30116fff  com.apple.CoreServices (1122.38 - 1122.38) <FEC6CD87-0909-3554-B8F5-CE65A5BB032C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff302d2000 -     0x7fff302d2fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <2BCB5475-FDEF-379A-BB0E-B1A3AA7F5B83> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff30313000 -     0x7fff3031efff  com.apple.MediaAccessibility (1.0 - 130) <F8E31637-2B5F-3D89-94FA-BD4AF8A46BD6> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff3031f000 -     0x7fff3033efff  com.apple.networking.AlgosScoreFramework (1.0 - 1) <C14EC551-82CD-3A04-91F3-C35D48B5B583> /System/Library/PrivateFrameworks/AlgosScoreFramework.framework/Versions/A/AlgosScoreFramework
    0x7fff3033f000 -     0x7fff30343fff  com.apple.AppleSRP (5.0 - 1) <F9D14131-8FEA-3BBF-902E-16754ABE537F> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
    0x7fff30344000 -     0x7fff3034ffff  com.apple.frameworks.CoreDaemon (1.3 - 1.3) <36002664-194B-3D03-8EFC-94AA3857B08B> /System/Library/PrivateFrameworks/CoreDaemon.framework/Versions/B/CoreDaemon
    0x7fff30b14000 -     0x7fff30b79fff  com.apple.CoreBluetooth (1.0 - 1) <AB95AA98-5CDC-3D4D-8478-C6595447837F> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff30b7a000 -     0x7fff30b83fff  com.apple.SymptomDiagnosticReporter (1.0 - 79.120.1) <99674A3B-7319-30F1-922E-D665D01794AF> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff30b97000 -     0x7fff30ba3fff  com.apple.AppleIDAuthSupport (1.0 - 1) <079E30CC-40B7-3363-9A41-F9A0DE9ED742> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff30ba4000 -     0x7fff30c4cfff  com.apple.DiscRecording (9.0.3 - 9030.4.5) <55DD9802-821D-35F6-B21B-C96371FE46B4> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff30c4d000 -     0x7fff30c80fff  com.apple.MediaKit (16 - 927.40.2) <72F9BA2E-AF51-3E05-8DE4-00377CC79609> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff30c81000 -     0x7fff30d6cfff  com.apple.DiskManagement (14.0 - 1733.100.4) <6EAC9935-9B5A-3758-92D4-9E13CF570D3A> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fff30d6d000 -     0x7fff31127fff  com.apple.CoreAUC (326.2.0 - 326.2.0) <A03BBCB7-69FA-3E37-AD91-734771D91045> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff31128000 -     0x7fff3112bfff  com.apple.Mangrove (1.0 - 25) <06E20B3A-83F6-36A3-96B8-9185D1B0A42D> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff3112c000 -     0x7fff31159fff  com.apple.CoreAVCHD (6.1.0 - 6100.4.1) <B7888146-5DE1-306C-8C9C-E98E763E3A4E> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff3115a000 -     0x7fff312a9fff  com.apple.FileProvider (348.8 - 348.8) <34DFD3C5-B489-3A7A-9EC2-3A1E2970F74D> /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff312aa000 -     0x7fff312ccfff  com.apple.GenerationalStorage (2.0 - 323) <AF8A2D39-41B5-3229-B780-86622DB977FC> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff31b16000 -     0x7fff31b55fff  com.apple.AppleVPAFramework (3.26.1 - 3.26.1) <32F14A37-1FAB-3216-B3FD-D1FA9E4790DC> /System/Library/PrivateFrameworks/AppleVPA.framework/Versions/A/AppleVPA
    0x7fff31c08000 -     0x7fff31c43fff  com.apple.DebugSymbols (195.1 - 195.1) <A8313A86-04C7-37DC-A5D7-FF54EE39BC70> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff31c44000 -     0x7fff31cf9fff  com.apple.CoreSymbolication (12.5 - 64544.69.1) <8D4E5AA8-8C09-31A7-AABE-AA9421781821> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff31cfa000 -     0x7fff31d03fff  com.apple.CoreTime (284.0.4) <A9351B53-5048-39AD-BC68-170474CAB8CB> /System/Library/PrivateFrameworks/CoreTime.framework/Versions/A/CoreTime
    0x7fff32bec000 -     0x7fff32c4ffff  com.apple.framework.Apple80211 (17.0 - 1728) <6C1C9532-AD79-3E68-BFBB-2279AC8EA776> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff32c50000 -     0x7fff32da1fff  com.apple.CoreWiFi (3.0 - 341) <E1A3027C-0657-3609-8F5C-D89BF6B4B422> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff32dbd000 -     0x7fff32df4fff  com.apple.LDAPFramework (2.4.28 - 194.5) <DDC1A94A-3537-3980-904B-31C54DA385C9> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fff32df5000 -     0x7fff32df6fff  com.apple.TrustEvaluationAgent (2.0 - 35) <736DE13E-CC75-3D3A-BE5B-AF75CC241E0B> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff32df7000 -     0x7fff32efcfff  libcrypto.44.dylib (56.60.2) <777B260D-CD90-3AE2-986E-2E4D021E6ACC> /usr/lib/libcrypto.44.dylib
    0x7fff32efd000 -     0x7fff32f2afff  libssl.46.dylib (56.60.2) <F2AE005F-3974-38D1-AA71-26201D27031F> /usr/lib/libssl.46.dylib
    0x7fff33012000 -     0x7fff33021fff  com.apple.RemoteServiceDiscovery (1.0 - 1.120.1) <00009125-85E9-3214-9CA3-EC1AB4EF8D77> /System/Library/PrivateFrameworks/RemoteServiceDiscovery.framework/Versions/A/RemoteServiceDiscovery
    0x7fff3307f000 -     0x7fff33082fff  com.apple.help (1.3.8 - 71) <F8B97715-17C5-3789-8B89-5F08EFB70709> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff33083000 -     0x7fff3308afff  com.apple.EFILogin (2.0 - 2) <32EC4CD5-A6BD-31E9-BE52-BF79845F9EDB> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff3308b000 -     0x7fff33096fff  libcsfde.dylib (554) <D4C66851-FDFC-3B94-8B21-DCA76BDFE724> /usr/lib/libcsfde.dylib
    0x7fff33097000 -     0x7fff330fdfff  libcurl.4.dylib (121.100.3) <5701AB53-D57D-38AE-8E76-ADBC03205B84> /usr/lib/libcurl.4.dylib
    0x7fff332d5000 -     0x7fff332d5fff  com.apple.ApplicationServices (48 - 50) <374F91E8-9983-363E-B1E1-85CEB46A5D1E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff335ea000 -     0x7fff335eafff  libHeimdalProxy.dylib (79) <68F67BFE-F1E8-341C-A065-08954EF3F684> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
    0x7fff3369d000 -     0x7fff3369dfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <CD5DF240-D8F7-3349-88DC-423962E5A289> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff336c1000 -     0x7fff33704fff  com.apple.StreamingZip (1.0 - 1) <D5CEAC33-8D9C-3D74-9E5D-909F86441F4D> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff33745000 -     0x7fff3374afff  com.apple.PushKit (1.0 - 1) <03F9CDE4-B5D7-3B6B-A87F-710ED5419A82> /System/Library/Frameworks/PushKit.framework/Versions/A/PushKit
    0x7fff3374b000 -     0x7fff3377efff  com.apple.C2 (1.3 - 573) <06D74CE3-4E9E-3BD6-A8F2-139BAE23437A> /System/Library/PrivateFrameworks/C2.framework/Versions/A/C2
    0x7fff3466c000 -     0x7fff346bcfff  com.apple.ChunkingLibrary (334.1 - 334.1) <27ED7D22-A3D4-3161-A5DF-485711DB2F48> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff34f16000 -     0x7fff34f18fff  com.apple.ConstantClasses (1.0 - 1) <53A4025A-6518-36F9-B927-23F4EEDEF7AE> /System/Library/PrivateFrameworks/ConstantClasses.framework/Versions/A/ConstantClasses
    0x7fff364d3000 -     0x7fff36503fff  libtidy.A.dylib (18.1) <49BB5870-8F69-35C0-9A9A-DE589727ED65> /usr/lib/libtidy.A.dylib
    0x7fff36525000 -     0x7fff36538fff  com.apple.Engram (1.0 - 1) <96563E93-C7B4-3BD3-9CE7-46BF006DF337> /System/Library/PrivateFrameworks/Engram.framework/Versions/A/Engram
    0x7fff36539000 -     0x7fff3655cfff  com.apple.openscripting (1.7 - 190) <9EAC55CC-0ECC-3B41-BF97-53C32496C689> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff3655d000 -     0x7fff36560fff  com.apple.securityhi (9.0 - 55008) <56A728F6-162E-31DE-9C29-FB1BE44C6B89> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff36561000 -     0x7fff36564fff  com.apple.ink.framework (10.15 - 227) <65FAEF94-F18C-30E0-8129-952DE19A5FAF> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff36565000 -     0x7fff36568fff  com.apple.CommonPanels (1.2.6 - 101) <45DFDB05-1408-34B4-A2AD-5416C5176C26> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff36569000 -     0x7fff36570fff  com.apple.ImageCapture (1711.5.2 - 1711.5.2) <E3BCD3B4-4792-390D-890B-B7A860088A4C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff38cda000 -     0x7fff38cdafff  com.apple.marco (10.0 - 1000) <EC9EE664-92FD-38A8-83A8-BEB5011743CC> /System/Library/PrivateFrameworks/Marco.framework/Versions/A/Marco
    0x7fff39396000 -     0x7fff393a4fff  com.apple.accessibility.AXCoreUtilities (1.0 - 1) <D11C0413-B53C-3FD3-9E97-841F8CE92672> /System/Library/PrivateFrameworks/AXCoreUtilities.framework/Versions/A/AXCoreUtilities
    0x7fff393a5000 -     0x7fff393bcfff  libAccessibility.dylib (2885.46) <1DB54413-6681-35FE-8211-9ED94E518017> /usr/lib/libAccessibility.dylib
    0x7fff3caaa000 -     0x7fff3caadfff  com.apple.print.framework.Print (15 - 271) <5A0FE511-37C2-3065-9066-34F8F9EA23E5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff3caae000 -     0x7fff3cab1fff  com.apple.Carbon (160 - 164) <967F26C3-8582-3A33-945F-DDA8F103B2E2> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3cd64000 -     0x7fff3cd83fff  com.apple.private.SystemPolicy (1.0 - 1) <CAB3E8CD-1F31-343F-ABC1-9448543F211F> /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy
    0x7fff3ced0000 -     0x7fff3cf26fff  com.apple.AccessibilitySharedSupport (1.0 - 1) <90C68F4B-F054-33FC-A1F5-E2396F11C937> /System/Library/PrivateFrameworks/AccessibilitySharedSupport.framework/Versions/A/AccessibilitySharedSupport
    0x7fff3d69e000 -     0x7fff3d6a9fff  com.apple.MallocStackLogging (1.0 - 1) <394E6F65-386E-3488-BD68-1D3C2418694B> /System/Library/PrivateFrameworks/MallocStackLogging.framework/Versions/A/MallocStackLogging
    0x7fff3d6be000 -     0x7fff3d6d0fff  libmis.dylib (274.120.2) <1DE29019-5ECB-3BE2-8492-2385ED241950> /usr/lib/libmis.dylib
    0x7fff3d6d1000 -     0x7fff3d6d4fff  com.apple.gpusw.GPURawCounter (20.3 - 12.0) <EBB93DE3-AFE7-34FE-A194-7DFC62FFB9AA> /System/Library/PrivateFrameworks/GPURawCounter.framework/Versions/A/GPURawCounter
    0x7fff3fd41000 -     0x7fff3fdbefff  com.apple.TextInput (1.0 - 1.0) <BC1AA691-A1A5-3368-8267-FA912891F59D> /System/Library/PrivateFrameworks/TextInput.framework/Versions/A/TextInput
    0x7fff40ef4000 -     0x7fff40efdfff  com.apple.IOAccelMemoryInfo (1.0 - 1) <0BBA14A6-C060-3759-9B5E-4EDFEABED297> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff41380000 -     0x7fff4139efff  libCGInterfaces.dylib (544.4) <02C89930-F64D-354E-8C18-F3DDB419DC8D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff43929000 -     0x7fff43b9cfff  com.apple.RawCamera.bundle (9.10.0 - 1450.3) <408A3DFB-B3D3-3C15-88BB-16076BDFC74B> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff47aa3000 -     0x7fff47ae3fff  com.apple.osanalytics.OSAnalytics (1.0 - 1) <96B8D855-E10D-3E40-884F-DA0BBAE9F48F> /System/Library/PrivateFrameworks/OSAnalytics.framework/Versions/A/OSAnalytics
    0x7fff516fa000 -     0x7fff51727fff  com.apple.HelpData (2.3 - 201) <3125FBF3-30B7-3237-B001-2692332FF681> /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/HelpData
    0x7fff51728000 -     0x7fff51742fff  com.apple.shortcut (2.16 - 118) <1FD9ABCC-0B5B-37DC-9E6E-CC47C128DBB2> /System/Library/PrivateFrameworks/Shortcut.framework/Versions/A/Shortcut
    0x7fff51743000 -     0x7fff517e2fff  com.apple.Symbolication (12.5 - 64544.70.1) <B57534E5-43D5-38CA-9A8C-A66EBDFB820A> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff5ddbd000 -     0x7fff5e24cfff  com.apple.driver.AppleIntelKBLGraphicsMTLDriver (16.4.5 - 16.0.4) <994BBF27-F4D5-3561-BC2E-FECC0C460C76> /System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver
    0x7fff69773000 -     0x7fff69777fff  libmetal_timestamp.dylib (31001.189) <89A82967-B14D-3109-B45E-34717156E60E> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/libmetal_timestamp.dylib
    0x7fff6bbbe000 -     0x7fff6bbc4fff  libCoreFSCache.dylib (200.9) <12A2A7E7-39F7-30A5-AC0B-E09947417D3E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff6bbc5000 -     0x7fff6bbc9fff  libCoreVMClient.dylib (200.9) <F8C4D017-075A-37B2-AE8D-8CEB5FE1BC9B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff6bbca000 -     0x7fff6bbd9fff  com.apple.opengl (18.5.9 - 18.5.9) <1422D0CA-C3E2-3309-8897-018E651CB74E> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6bbda000 -     0x7fff6bbdcfff  libCVMSPluginSupport.dylib (18.5.9) <AC7D4088-7CA8-3A0B-9B55-08427083C382> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff6bbdd000 -     0x7fff6bbe5fff  libGFXShared.dylib (18.5.9) <76ABDB4A-3687-39E0-B8FB-125717742431> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff6bbe6000 -     0x7fff6bc19fff  libGLImage.dylib (18.5.9) <750C938A-9F4F-3BAD-8D3F-03EF619F28AD> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff6bc1a000 -     0x7fff6bc56fff  libGLU.dylib (18.5.9) <4A77F717-2BBC-3439-AE10-694E82C0A184> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff6bdeb000 -     0x7fff6bdf5fff  libGL.dylib (18.5.9) <95D5C72E-9352-39EC-83B1-6BB295A83462> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff6d235000 -     0x7fff6d28dfff  com.apple.opencl (4.6 - 4.6) <769BB23D-09E5-3A3A-B2EA-310157AA206D> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff6e337000 -     0x7fff6e33efff  com.apple.agl (3.3.4 - AGL-3.3.3) <23E38B10-2F27-3BB2-B78D-C28189C21601> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff77a33000 -     0x7fff77a3afff  libRosetta.dylib (203.46) <0A17EAFC-15E9-37FE-8EE2-DE0F7F220AD8> /usr/lib/libRosetta.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=789.9M resident=0K(0%) swapped_out_or_unallocated=789.9M(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 4032K        6 
CG image                           668K       20 
CG raster data                     352K        1 
CoreAnimation                      832K       12 
CoreGraphics                        12K        2 
CoreUI image data                 2332K       20 
Foundation                          32K        2 
Kernel Alloc Once                   28K        2 
MALLOC                             1.3G      122 
MALLOC guard page                   32K        6 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        8 
Stack                             11.6M        8 
VM_ALLOCATE                        420K       24 
VM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)
__DATA                            16.4M      383 
__DATA_CONST                      15.6M      211 
__DATA_DIRTY                       805K      116 
__FONT_DATA                          4K        1 
__LINKEDIT                       508.6M       44 
__OBJC_RO                         70.2M        1 
__OBJC_RW                         2480K        2 
__TEXT                           281.4M      381 
__UNICODE                          588K        1 
mapped file                      551.5M       39 
shared memory                      748K       14 
===========                     =======  ======= 
TOTAL                              3.2G     1432 
TOTAL, minus reserved VM space     2.8G     1432 

Model: MacBookPro16,1, BootROM 1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0), 8 processors, 8-Core Intel Core i9, 2.4 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5500MItem, AMD Radeon Pro 5500M, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 16 2021 03:05:58 version 9.30.444.10.32.5.67 FWID 01-3d719d60
Bluetooth: Version 8.0.5d7, 3 services, 25 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

</details>

After filing this report, I was able to install BOINC and attach to GRCPool, and the Gridcoin snapshot is almost finished downloading without any issues. Hope this helps!

Edit: another crash occurred near the end of the snapshot download:

<details>
<summary>Second crash logs</summary>
Process:               gridcoinresearch [3285]
Path:                  /Applications/Gridcoin.app/Contents/MacOS/gridcoinresearch
Identifier:            org.bitcoinfoundation.Bitcoin-Qt
Version:               5.3.1 (5.3.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           gridcoinresearch [3285]
User ID:               502

Date/Time:             2021-07-01 14:56:04.373 -0700
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        2AC711AD-12B3-4FE8-863A-EC5FBA337756

Sleep/Wake UUID:       AAD4B540-192A-4772-BCC8-3C7E21D1033D

Time Awake Since Boot: 5600 seconds
Time Since Wake:       3200 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000070000271bff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [3285]

VM Regions Near 0x70000271bff8:
    MALLOC_NANO (reserved)   600048000000-600060000000 [384.0M] rw-/rwx SM=NUL  reserved VM address space (unallocated)
--> STACK GUARD              70000271b000-70000271c000 [    4K] ---/rwx SM=NUL  stack guard for thread 4
    Stack                    70000271c000-70000279e000 [  520K] rw-/rwx SM=SHM  thread 4

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2057ecde __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205b1e49 _pthread_cond_wait + 1298
2   org.bitcoinfoundation.Bitcoin-Qt	0x0000000107c4b071 0x107927000 + 3293297
3   org.bitcoinfoundation.Bitcoin-Qt	0x0000000107c48fb4 0x107927000 + 3284916
4   org.bitcoinfoundation.Bitcoin-Qt	0x0000000107c48e94 0x107927000 + 3284628
5   org.bitcoinfoundation.Bitcoin-Qt	0x00000001079f11de 0x107927000 + 827870
6   org.bitcoinfoundation.Bitcoin-Qt	0x00000001079342c6 0x107927000 + 53958
7   libdyld.dylib                 	0x00007fff205ccf5d start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff2057c2ba mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff2057c62c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff206aab5f __CFRunLoopServiceMachPort + 316
3   com.apple.CoreFoundation      	0x00007fff206a923f __CFRunLoopRun + 1328
4   com.apple.CoreFoundation      	0x00007fff206a864c CFRunLoopRunSpecific + 563
5   com.apple.AppKit              	0x00007fff2302f68a _NSEventThread + 124
6   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
7   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff2057ecde __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff205b1e49 _pthread_cond_wait + 1298
2   org.bitcoinfoundation.Bitcoin-Qt	0x0000000107cdc2ad 0x107927000 + 3887789
3   org.bitcoinfoundation.Bitcoin-Qt	0x0000000107cdc25f 0x107927000 + 3887711
4   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
5   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff205ad420 start_wqthread + 0

Thread 4 Crashed:
0   libsystem_pthread.dylib       	0x00007fff205ad47f ___chkstk_darwin + 55
1   org.bitcoinfoundation.Bitcoin-Qt	0x00000001079f28d7 0x107927000 + 833751
2   libboost_thread-mt.dylib      	0x0000000108274bf8 0x108272000 + 11256
3   libsystem_pthread.dylib       	0x00007fff205b18fc _pthread_start + 224
4   libsystem_pthread.dylib       	0x00007fff205ad443 thread_start + 15

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000100138  rbx: 0x000070000279bf28  rcx: 0x000070000271c000  rdx: 0x0000000000000000
  rdi: 0x000070000279bf28  rsi: 0x00007fe9c8c2ad60  rbp: 0x000070000279bf10  rsp: 0x000070000279bed0
   r8: 0x00007fff808abb50   r9: 0x00000000190008ff  r10: 0x00007fe9c8c2ad60  r11: 0x0000000000000286
  r12: 0x0000600002507720  r13: 0x0000000000000000  r14: 0x00007fe9c8c2ad60  r15: 0x0000000000000000
  rip: 0x00007fff205ad47f  rfl: 0x0000000000010212  cr2: 0x000070000271bff8
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 4 instruction stream:
  90 6a 00 55 48 89 e5 48-83 ec 10 e8 f4 0e 00 00  .j.UH..H........
  0f 0b 0f 1f 00 6a 00 55-48 89 e5 48 83 ec 10 e8  .....j.UH..H....
  d9 43 00 00 c9 c3 0f 1f-00 51 48 8d 4c 24 10 65  .C.......QH.L$.e
  48 39 0c 25 d0 ff ff ff-72 2a 65 48 39 0c 25 d8  H9.%....r*eH9.%.
  ff ff ff 73 1f 48 29 c1-72 0d 65 48 39 0c 25 d8  ...s.H).r.eH9.%.
  ff ff ff 77 02 59 c3 65-48 8b 0c 25 d8 ff ff ff  ...w.Y.eH..%....
 [48]85 49 f8 48 3d 00 10-00 00 72 1a 50 48 81 e9  H.I.H=....r.PH..	<==
  00 10 00 00 48 85 09 48-2d 00 10 00 00 48 3d 00  ....H..H-....H=.
  10 00 00 77 e8 58 48 29-c1 48 85 09 59 c3 65 48  ...w.XH).H..Y.eH
  8b 04 fd 00 00 00 00 c3-48 8d 4f f6 b8 16 00 00  ........H.O.....
  00 48 81 f9 f5 02 00 00-77 22 65 48 8b 0c 25 00  .H......w"eH..%.
  00 00 00 4c 8d 05 77 e6-2f 60 49 8b 14 f8 48 81  ...L..w./`I...H.
  
Thread 4 last branch register state not available.

Binary Images:
       0x107927000 -        0x108106fff +org.bitcoinfoundation.Bitcoin-Qt (5.3.1 - 5.3.1) <7EF847B9-B90E-379D-92F9-C8ACE92AF6A6> /Applications/Gridcoin.app/Contents/MacOS/gridcoinresearch
       0x1081fb000 -        0x1081fefff +libboost_system.dylib (0) <AAAF2C2E-C95A-30A0-AA83-D37839B0F934> /Applications/Gridcoin.app/Contents/Frameworks/libboost_system.dylib
       0x108202000 -        0x108215fff +libboost_filesystem.dylib (0) <ED5058BA-697C-3391-A32E-96A71FD9829B> /Applications/Gridcoin.app/Contents/Frameworks/libboost_filesystem.dylib
       0x108225000 -        0x108254fff +libboost_program_options-mt.dylib (0) <21A3D046-A354-34AD-90C4-3060AAE2BDBD> /Applications/Gridcoin.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x108272000 -        0x10827dfff +libboost_thread-mt.dylib (0) <5A04F107-39F0-3560-8FAA-5CB5C94B5C9A> /Applications/Gridcoin.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x108290000 -        0x108293fff +libboost_chrono-mt.dylib (0) <8DD3519B-0184-321D-B401-81130FEE3BE5> /Applications/Gridcoin.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1082a3000 -        0x1082aefff +libboost_iostreams-mt.dylib (0) <6D652ACF-96B1-30C8-BA21-3ABF4836D1B3> /Applications/Gridcoin.app/Contents/Frameworks/libboost_iostreams-mt.dylib
       0x1082be000 -        0x1082c1fff +libboost_system-mt.dylib (0) <F77E16D3-42F5-3CFF-AD44-B03000D087EC> /Applications/Gridcoin.app/Contents/Frameworks/libboost_system-mt.dylib
       0x1082c6000 -        0x108809fff +org.qt-project.QtCore (5.15 - 5.15.2) <226F4F10-F8C2-301E-AA19-240048D7C206> /Applications/Gridcoin.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1088d4000 -        0x108dbffff +org.qt-project.QtGui (5.15 - 5.15.2) <535A424C-EF63-3E4C-A42A-5B5F18D0C07C> /Applications/Gridcoin.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x108ee0000 -        0x10932bfff +org.qt-project.QtWidgets (5.15 - 5.15.2) <151402D2-0EE6-34F3-A101-E6CDD04F398A> /Applications/Gridcoin.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x109491000 -        0x1095a4fff +org.qt-project.QtNetwork (5.15 - 5.15.2) <7C449550-8880-3C41-B131-388DCC0585FA> /Applications/Gridcoin.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x1095f4000 -        0x1095fbfff +org.qt-project.QtConcurrent (5.15 - 5.15.2) <ADB3D95D-2B0D-3B82-A68E-FFC9E063A29E> /Applications/Gridcoin.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent
       0x109606000 -        0x1096e1fff +org.qt-project.QtCharts (5.15 - 5.15.2) <8E09C7D2-5611-31B5-9D3C-264A159ACDF2> /Applications/Gridcoin.app/Contents/Frameworks/QtCharts.framework/Versions/5/QtCharts
       0x10978d000 -        0x1097ecfff +org.qt-project.QtDBus (5.15 - 5.15.2) <170FD3F7-EA0D-3344-8290-A0E9ACB3A883> /Applications/Gridcoin.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10980e000 -        0x109815fff +libqrencode.4.dylib (0) <CFF61E40-5BA6-362A-97C2-643588DE7A99> /Applications/Gridcoin.app/Contents/Frameworks/libqrencode.4.dylib
       0x109823000 -        0x109932fff +libdb_cxx-4.8.dylib (0) <77CBA1BA-E715-31C0-85AE-31B882D4E38E> /Applications/Gridcoin.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x10995f000 -        0x1099aefff +libssl.1.1.dylib (0) <9BD08628-AC20-3489-B3D2-AC117A5BC2F8> /Applications/Gridcoin.app/Contents/Frameworks/libssl.1.1.dylib
       0x1099dc000 -        0x109b9bfff +libcrypto.1.1.dylib (0) <EF694AAC-B437-322C-B619-BF3EB122466C> /Applications/Gridcoin.app/Contents/Frameworks/libcrypto.1.1.dylib
       0x109c23000 -        0x109c2efff +libminiupnpc.17.dylib (0) <3F1F08BD-AAD9-3F43-9E7E-0DF421C559CE> /Applications/Gridcoin.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x109c3d000 -        0x109c4dfff +libzip.5.dylib (0) <01712EF1-7BA0-3073-ACE4-806C184CE3D5> /Applications/Gridcoin.app/Contents/Frameworks/libzip.5.dylib
       0x10bb96000 -        0x10bcfdfff +libqcocoa.dylib (0) <FDFF1859-EE45-351C-8ECF-A60FE4EDACA0> /Applications/Gridcoin.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x10bd4e000 -        0x10bd79fff +org.qt-project.QtPrintSupport (5.15 - 5.15.2) <767E9D97-E124-385F-9679-87C5FE69CCE9> /Applications/Gridcoin.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10cb61000 -        0x10cb70fff  libobjc-trampolines.dylib (824) <361143B8-E66E-3402-85B5-C20893AAB9C9> /usr/lib/libobjc-trampolines.dylib
       0x10dc4d000 -        0x10dc74fff +libqmacstyle.dylib (0) <1849A958-4393-35D9-AEEC-ECEBE5934C8C> /Applications/Gridcoin.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x10dc86000 -        0x10dc8dfff +libqgif.dylib (0) <6E8E4247-37C6-3204-ADDC-6244EB6DE497> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x10dc94000 -        0x10dc9bfff +libqicns.dylib (0) <EB86CC3D-B823-343D-9044-8A219D8AF4C6> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x10dca3000 -        0x10dcaafff +libqico.dylib (0) <FCC41E97-598C-32F4-8BCF-B7C2825E64F7> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqico.dylib
       0x10dcb2000 -        0x10dd15fff +libqjpeg.dylib (0) <07224DB9-385C-330C-8B17-421EA26A9D9D> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x10dd1e000 -        0x10dd25fff +libqmacheif.dylib (0) <050A0EA9-DFE0-3D52-8C32-3B188BB04825> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqmacheif.dylib
       0x10dd2d000 -        0x10dd34fff +libqmacjp2.dylib (0) <3A670177-35BE-3FB6-A060-D758107E1F38> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x10dd3c000 -        0x10dd43fff +libqpdf.dylib (0) <E818633B-0FA2-38E4-9276-6BC5AE1F12C6> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqpdf.dylib
       0x10dd4a000 -        0x10e365fff +org.qt-project.QtPdf (5.15 - 5.15.2) <3DCCF55A-4EA3-3076-B5EC-3965580022CB> /Applications/Gridcoin.app/Contents/Frameworks/QtPdf.framework/Versions/5/QtPdf
       0x10e399000 -        0x10e3a0fff +libqtga.dylib (0) <B3FA3E55-84F4-3793-B4C6-F2A60F67FD3A> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x10e3a7000 -        0x10e40efff +libqtiff.dylib (0) <809F2B79-3FFC-359F-8893-73BBBCE6F317> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x10e417000 -        0x10e41efff +libqwbmp.dylib (0) <E24690D9-FB9A-3A1A-A5AC-B91010343286> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x10e425000 -        0x10e4c0fff +libqwebp.dylib (0) <3BD34DC5-8B37-37ED-ADBB-642DA4B98402> /Applications/Gridcoin.app/Contents/PlugIns/imageformats/libqwebp.dylib
       0x10f8f2000 -        0x10f8f9fff +libqsvgicon.dylib (0) <F6733EC9-07BB-30B7-8D8D-FE14B0918C93> /Applications/Gridcoin.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
       0x10f901000 -        0x10f938fff +org.qt-project.QtSvg (5.15 - 5.15.2) <4234EABD-88DA-328F-8A40-9A50E2C534CC> /Applications/Gridcoin.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x11036f000 -        0x11040afff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld
       0x125b26000 -        0x125fc5fff  com.apple.AMDRadeonX6000MTLDriver (4.5.14 - 4.0.5) <B3387E41-6C51-3665-8931-791F5EAC36D6> /System/Library/Extensions/AMDRadeonX6000MTLDriver.bundle/Contents/MacOS/AMDRadeonX6000MTLDriver
    0x7fff202e9000 -     0x7fff202eafff  libsystem_blocks.dylib (79) <48AF56A9-6E42-3A5E-A213-E6AFD8F81044> /usr/lib/system/libsystem_blocks.dylib
    0x7fff202eb000 -     0x7fff20320fff  libxpc.dylib (2038.120.1) <5751A7F5-6DC5-3090-B7F1-D90ED71BEF1F> /usr/lib/system/libxpc.dylib
    0x7fff20321000 -     0x7fff20338fff  libsystem_trace.dylib (1277.120.1) <8E243C00-BFC2-3FAA-989C-0D72314DB04D> /usr/lib/system/libsystem_trace.dylib
    0x7fff20339000 -     0x7fff203d6fff  libcorecrypto.dylib (1000.120.2) <FADB19A0-1BF3-3F47-B729-87B4FA8CA677> /usr/lib/system/libcorecrypto.dylib
    0x7fff203d7000 -     0x7fff20403fff  libsystem_malloc.dylib (317.121.1) <CAD162A5-7367-3A30-9C15-5D036411AEDE> /usr/lib/system/libsystem_malloc.dylib
    0x7fff20404000 -     0x7fff20448fff  libdispatch.dylib (1271.120.2) <7B229797-1F2E-3409-9D0C-060C7EEF2E12> /usr/lib/system/libdispatch.dylib
    0x7fff20449000 -     0x7fff20482fff  libobjc.A.dylib (824) <FE5AF22E-80A1-34BB-98D6-610879988BAA> /usr/lib/libobjc.A.dylib
    0x7fff20483000 -     0x7fff20485fff  libsystem_featureflags.dylib (28.60.1) <77F7F479-39BD-3111-BE3C-C74567FD120C> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff20486000 -     0x7fff2050efff  libsystem_c.dylib (1439.100.3) <38F8A126-C995-349A-B909-FF831914ED2E> /usr/lib/system/libsystem_c.dylib
    0x7fff2050f000 -     0x7fff20564fff  libc++.1.dylib (905.6) <B3812B86-4FCF-3A10-8866-DF67940A974C> /usr/lib/libc++.1.dylib
    0x7fff20565000 -     0x7fff2057afff  libc++abi.dylib (905.6) <A0FE88B7-E157-3C9C-A29A-11D3BE3436B3> /usr/lib/libc++abi.dylib
    0x7fff2057b000 -     0x7fff205aafff  libsystem_kernel.dylib (7195.121.3) <A4938CF5-ABC0-397B-8A6E-B7BEEFA24D0A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff205ab000 -     0x7fff205b6fff  libsystem_pthread.dylib (454.120.2) <17482C9D-061E-3769-AC9E-BE1239D33098> /usr/lib/system/libsystem_pthread.dylib
    0x7fff205b7000 -     0x7fff205f2fff  libdyld.dylib (852) <C10CEA28-D5A0-324F-8F07-8C7CE4805412> /usr/lib/system/libdyld.dylib
    0x7fff205f3000 -     0x7fff205fcfff  libsystem_platform.dylib (254.80.2) <8664A4CD-EE27-3C71-B5CC-06E2B1B4F394> /usr/lib/system/libsystem_platform.dylib
    0x7fff205fd000 -     0x7fff20628fff  libsystem_info.dylib (542.40.3) <EA3F9C9C-3116-3DB4-A3F1-5B03172C1E72> /usr/lib/system/libsystem_info.dylib
    0x7fff20629000 -     0x7fff20ac6fff  com.apple.CoreFoundation (6.9 - 1776.103) <01EFB7F8-BCE6-32DF-A0B8-02F9027F882C> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff20ac7000 -     0x7fff20cfbfff  com.apple.LaunchServices (1122.38 - 1122.38) <241B3D82-2C9C-3F7D-88BD-AC78A689FF04> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff20cfc000 -     0x7fff20dcffff  com.apple.gpusw.MetalTools (1.0 - 1) <03202B68-E515-3CBE-AC5A-39E80A702A6F> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff20dd0000 -     0x7fff2102cfff  libBLAS.dylib (1336.120.1) <44514FE9-B994-380E-8341-4ABA30DB8895> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff2102d000 -     0x7fff2107afff  com.apple.Lexicon-framework (1.0 - 86.2) <F69DF515-4980-36C8-9F5D-987B67D2AFAF> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff2107b000 -     0x7fff210e9fff  libSparse.dylib (106) <E7F273C0-18F8-3688-9B63-C86DEB06740A> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff210ea000 -     0x7fff21167fff  com.apple.SystemConfiguration (1.20 - 1.20) <81EDA68C-051A-3F4C-B79E-B53B365B67B1> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff21168000 -     0x7fff2119cfff  libCRFSuite.dylib (50) <703BB228-D959-3009-AF3F-0015588F531A> /usr/lib/libCRFSuite.dylib
    0x7fff2119d000 -     0x7fff213d5fff  libmecabra.dylib (929.10) <43C2A11F-7F68-31B6-AD65-31282837DED3> /usr/lib/libmecabra.dylib
    0x7fff213d6000 -     0x7fff21734fff  com.apple.Foundation (6.9 - 1776.103) <3C3B967D-778D-30BF-A3F8-E734FAFD76F2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff21735000 -     0x7fff2181dfff  com.apple.LanguageModeling (1.0 - 247.3) <58ACD840-A17B-3CB0-B010-7E4493C5BC5C> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff2181e000 -     0x7fff21954fff  com.apple.CoreDisplay (237.3 - 237.3) <65322ECF-632D-362D-870D-5CE69B1B6C60> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff21955000 -     0x7fff21bc5fff  com.apple.audio.AudioToolboxCore (1.0 - 1181.68) <87BA778B-6634-30D8-BF69-678C36246242> /System/Library/PrivateFrameworks/AudioToolboxCore.framework/Versions/A/AudioToolboxCore
    0x7fff21bc6000 -     0x7fff21dabfff  com.apple.CoreText (677.5.0.5 - 677.5.0.5) <C148A259-D01A-3634-9449-119EB084ABA9> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff21dac000 -     0x7fff2243cfff  com.apple.audio.CoreAudio (5.0 - 5.0) <E987DC18-3396-3AAD-A66A-2B755C8D242A> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff2243d000 -     0x7fff22791fff  com.apple.security (7.0 - 59754.120.12) <7C3D689E-9B3E-3F73-ACF0-F40C1297D180> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff22792000 -     0x7fff229f1fff  libicucore.A.dylib (66112) <9957A773-012E-3ABA-9587-CFF787170AE8> /usr/lib/libicucore.A.dylib
    0x7fff229f2000 -     0x7fff229fbfff  libsystem_darwin.dylib (1439.100.3) <BF5B5FD8-B5A3-3035-8641-466E625A6CE8> /usr/lib/system/libsystem_darwin.dylib
    0x7fff229fc000 -     0x7fff22ce7fff  com.apple.CoreServices.CarbonCore (1307.3 - 1307.3) <1C5425B5-0E8C-3691-99AB-44F17F357C81> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff22ce8000 -     0x7fff22d26fff  com.apple.CoreServicesInternal (476.1.1 - 476.1.1) <6CF5F363-4653-3605-A340-363C743BBEDD> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff22d27000 -     0x7fff22d61fff  com.apple.CSStore (1122.38 - 1122.38) <A664672F-440D-3BA8-8851-68B4C6AB1022> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
    0x7fff22d62000 -     0x7fff22e10fff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <C6E70E82-8508-3515-ACE1-361E575D466A> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22e11000 -     0x7fff22e1cfff  libsystem_notify.dylib (279.40.4) <7FFECC25-FA84-3B59-9CC8-4D9DC84E6EC1> /usr/lib/system/libsystem_notify.dylib
    0x7fff22e1d000 -     0x7fff22e6afff  libsandbox.1.dylib (1441.120.5) <F4FF5F3E-6533-3BD5-8EF1-D298E0C954F6> /usr/lib/libsandbox.1.dylib
    0x7fff22e6b000 -     0x7fff23bb3fff  com.apple.AppKit (6.9 - 2022.50.114) <02279013-2888-3A1D-8F28-0C39A64EF5FA> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff23bb4000 -     0x7fff23e02fff  com.apple.UIFoundation (1.0 - 728.8) <A901F2AB-A1C3-3BDB-A2ED-33CAEC118589> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff23e03000 -     0x7fff23e15fff  com.apple.UniformTypeIdentifiers (637 - 637) <8DEE5893-C380-335B-B3DA-DD49DA8FB037> /System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/UniformTypeIdentifiers
    0x7fff23e16000 -     0x7fff23fa0fff  com.apple.desktopservices (1.20 - 1346.5.1) <E4F2E32A-6D94-35D5-B510-44C604236A64> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff24280000 -     0x7fff24906fff  libnetwork.dylib (2288.121.1) <728F736C-8AB2-30C0-8E61-A84F34642B18> /usr/lib/libnetwork.dylib
    0x7fff24907000 -     0x7fff24da5fff  com.apple.CFNetwork (1240.0.4 - 1240.0.4) <83684BEF-A3CE-3227-8E10-A8A538CCA9AE> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff24da6000 -     0x7fff24db4fff  libsystem_networkextension.dylib (1295.120.5) <02486B74-EAAD-3055-AE20-F12E79B39297> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24db5000 -     0x7fff24db5fff  libenergytrace.dylib (22.100.1) <7039CE14-0DED-3FD3-A540-A01DEFC4314D> /usr/lib/libenergytrace.dylib
    0x7fff24db6000 -     0x7fff24e12fff  libMobileGestalt.dylib (978.120.1) <9FF187B8-854F-338D-BD6A-AE142C815617> /usr/lib/libMobileGestalt.dylib
    0x7fff24e13000 -     0x7fff24e29fff  libsystem_asl.dylib (385) <B3E89650-A7FE-3E93-8A1B-D88145FDD45C> /usr/lib/system/libsystem_asl.dylib
    0x7fff24e2a000 -     0x7fff24e41fff  com.apple.TCC (1.0 - 1) <5D202FF3-7BD8-3384-A8AB-7D62CD14C412> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff24e42000 -     0x7fff251a6fff  com.apple.SkyLight (1.600.0 - 588.1) <D5925B80-2468-3709-9DFD-BEAF418169EC> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff251a7000 -     0x7fff25830fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <8E1776B9-0046-3FCF-BF54-F76490EA4A27> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff25831000 -     0x7fff25927fff  com.apple.ColorSync (4.13.0 - 3473.4.3) <CB975116-61F8-330F-B111-3F0467F88BC1> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff25928000 -     0x7fff25983fff  com.apple.HIServices (1.22 - 716) <132B9E44-BF23-3B61-96F2-7678C81115AA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff25d2a000 -     0x7fff26149fff  com.apple.CoreData (120 - 1048) <D3DAFFD5-CC38-3A82-B138-015DBFD551D9> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff2614a000 -     0x7fff2615ffff  com.apple.ProtocolBuffer (1 - 285.24.10.20.1) <C92547DE-86B8-3734-A17D-D0F9B4AE1300> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff26160000 -     0x7fff26313fff  libsqlite3.dylib (321.3) <E9324AF2-968F-3459-A0EB-2FD4E8A3BF09> /usr/lib/libsqlite3.dylib
    0x7fff26314000 -     0x7fff26390fff  com.apple.Accounts (113 - 113) <E31BCCDB-C1E3-3C74-9527-EF1643FF6224> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff26391000 -     0x7fff263a8fff  com.apple.commonutilities (8.0 - 900) <4EBBE25A-3599-3DC8-B846-F90BD23FED85> /System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities
    0x7fff263a9000 -     0x7fff26428fff  com.apple.BaseBoard (526 - 526) <ECED5758-3FD9-3F09-8E55-2230E391373A> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff26429000 -     0x7fff26471fff  com.apple.RunningBoardServices (1.0 - 505.100.8) <F72D5FDE-6DC0-3068-AD08-CA8D165E574D> /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices
    0x7fff26472000 -     0x7fff264e6fff  com.apple.AE (918.6 - 918.6) <A9B7A6D0-85CE-31CD-8926-81D3A714AF42> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff264e7000 -     0x7fff264edfff  libdns_services.dylib (1310.120.71) <6F77A4C7-40B9-3062-8650-6E1E2FD07046> /usr/lib/libdns_services.dylib
    0x7fff264ee000 -     0x7fff264f5fff  libsystem_symptoms.dylib (1431.120.1) <3BEA5355-D267-39D4-8BC6-A1703845BD3F> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff264f6000 -     0x7fff26681fff  com.apple.Network (1.0 - 1) <39B5F4D8-5105-37CB-9F18-2B2C36CB4B42> /System/Library/Frameworks/Network.framework/Versions/A/Network
    0x7fff26682000 -     0x7fff266b1fff  com.apple.analyticsd (1.0 - 1) <2DABBC97-042F-39C7-85A5-A6F47BCAC5EC> /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics
    0x7fff266b2000 -     0x7fff266b4fff  libDiagnosticMessagesClient.dylib (112) <8D0655AC-218F-3AA6-9802-2444E6801067> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff266b5000 -     0x7fff26701fff  com.apple.spotlight.metadata.utilities (1.0 - 2150.21) <7CE4BC56-65ED-3D75-8DA0-05EFE1BA2256> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff26702000 -     0x7fff2679cfff  com.apple.Metadata (10.7.0 - 2150.21) <04F83B90-3535-326F-8897-D43F55DDE771> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff2679d000 -     0x7fff267a3fff  com.apple.DiskArbitration (2.7 - 2.7) <97F9E5D9-0942-3AD6-8D31-65106C452CB8> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff267a4000 -     0x7fff26e0bfff  com.apple.vImage (8.1 - 544.4) <A711FD44-1495-3D7B-BF5C-E238C17B1A79> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff26e0c000 -     0x7fff270e8fff  com.apple.QuartzCore (1.11 - 927.21) <F384A0C0-F855-3B4D-AAD0-E0F0550E226C> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff270e9000 -     0x7fff2712afff  libFontRegistry.dylib (309) <5D9848B3-14C7-34A8-A981-B3C2CFD12BD9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff2712b000 -     0x7fff2726bfff  com.apple.coreui (2.1 - 692.1) <76D85525-8D99-3F0F-BC36-DEA342D4589D> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff2726c000 -     0x7fff27357fff  com.apple.ViewBridge (553.1 - 553.1) <21A4A790-5A90-3C45-979E-9CF3ED9E8092> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff27358000 -     0x7fff27363fff  com.apple.PerformanceAnalysis (1.278.3 - 278.3) <3FE8B4FD-B159-38B0-BA07-DE6722AC9F55> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff27364000 -     0x7fff27373fff  com.apple.OpenDirectory (11.4 - 230.40.1) <32596EC3-5500-3B18-ABCD-D92EDEDE74BF> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff27374000 -     0x7fff27393fff  com.apple.CFOpenDirectory (11.4 - 230.40.1) <3AA364D1-58AE-3C8D-B897-5B4AC3256BE7> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff27394000 -     0x7fff273a0fff  com.apple.CoreServices.FSEvents (1290.120.5 - 1290.120.5) <4C4959DF-FE61-30E8-8BBB-3BF674BE203A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff273a1000 -     0x7fff273c5fff  com.apple.coreservices.SharedFileList (144 - 144) <4418DDA1-CA34-3402-97F2-CE9B60019617> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff273c6000 -     0x7fff273c8fff  libapp_launch_measurement.dylib (14.1) <78905455-A807-3D67-AD56-FF8C22D31B16> /usr/lib/libapp_launch_measurement.dylib
    0x7fff273c9000 -     0x7fff27410fff  com.apple.CoreAutoLayout (1.0 - 21.10.1) <E848DF1F-1C82-3F04-87B8-9BF0C956A587> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/Versions/A/CoreAutoLayout
    0x7fff27411000 -     0x7fff274f3fff  libxml2.2.dylib (34.9) <08E7CAB2-0EED-376C-880A-E52CC01E82F3> /usr/lib/libxml2.2.dylib
    0x7fff274f4000 -     0x7fff27541fff  com.apple.CoreVideo (1.8 - 414.7) <29D4EA46-F0B6-3004-863C-0940ACD200C2> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff27542000 -     0x7fff27544fff  com.apple.loginsupport (1.0 - 1) <02FCC3AF-1E2D-3603-9D6F-33589ED28A00> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff2756d000 -     0x7fff27588fff  com.apple.UserManagement (1.0 - 1) <12F6D91A-C660-37CD-90E7-A0137393F080> /System/Library/PrivateFrameworks/UserManagement.framework/Versions/A/UserManagement
    0x7fff284fc000 -     0x7fff2850cfff  libsystem_containermanager.dylib (318.100.4) <2BBFF58C-D27E-3371-968D-7DE1E53749F6> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff2850d000 -     0x7fff2851efff  com.apple.IOSurface (290.8.1 - 290.8.1) <BA97183F-8EE4-3833-8AA7-06D9B9D39BDF> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff2851f000 -     0x7fff28528fff  com.apple.IOAccelerator (442.9 - 442.9) <91FA0C86-BD36-373C-B91A-7360D27CA614> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff28529000 -     0x7fff2864cfff  com.apple.Metal (244.201 - 244.201) <5197E017-D6CD-3611-A8B5-76A4FB901C6A> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff2864d000 -     0x7fff28669fff  com.apple.audio.caulk (1.0 - 70) <B6AB0B5B-ED36-3567-8112-5C9DEDBFBBFA> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7fff2866a000 -     0x7fff28754fff  com.apple.CoreMedia (1.0 - 2775.22) <9C15E6D0-245E-3A6E-BC67-C1DF67F7EB2A> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff28755000 -     0x7fff288b5fff  libFontParser.dylib (305.5.0.1) <DFE3F79C-849C-3FC7-AFC0-24AB83171A36> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
    0x7fff288b6000 -     0x7fff28bb1fff  com.apple.HIToolbox (2.1.1 - 1061.11) <DFAA0674-E367-36D9-925A-4EA9A6954BB0> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff28bb2000 -     0x7fff28bc5fff  com.apple.framework.DFRFoundation (1.0 - 266) <0B60B894-C5A5-38F0-8755-53BD217B0E36> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff28bc6000 -     0x7fff28bc9fff  com.apple.dt.XCTTargetBootstrap (1.0 - 18119.1) <8828FD40-9EE5-3E09-9DD7-8B7E34B34C26> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff28bca000 -     0x7fff28bf3fff  com.apple.CoreSVG (1.0 - 149) <BA347BBA-DC27-3728-9728-A791957D3F59> /System/Library/PrivateFrameworks/CoreSVG.framework/Versions/A/CoreSVG
    0x7fff28bf4000 -     0x7fff28e30fff  com.apple.ImageIO (3.3.0 - 2130.5.4) <14E0D520-1EE1-3C80-9827-4E5F513A7289> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff28e31000 -     0x7fff291acfff  com.apple.CoreImage (16.3.0 - 1140.2) <4A5B2859-C1F7-3938-B4B6-DDEC972798D1> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff291ad000 -     0x7fff29213fff  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <20902DA8-4AAB-36C8-9224-4F9E828B465A> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff29214000 -     0x7fff29217fff  libsystem_configuration.dylib (1109.120.1) <C7A9BD10-192B-31D3-92ED-2581A61A99F6> /usr/lib/system/libsystem_configuration.dylib
    0x7fff29218000 -     0x7fff2921cfff  libsystem_sandbox.dylib (1441.120.5) <DC075A7C-9D4A-32D3-9022-CD47764AFDAD> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff2921d000 -     0x7fff2921efff  com.apple.AggregateDictionary (1.0 - 1) <4394E8DB-F6D9-3F85-B894-F463378DC1B4> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff2921f000 -     0x7fff29222fff  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <1826DE1C-06B1-3140-A9A2-F7D55C1D9DB6> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff29223000 -     0x7fff29224fff  liblangid.dylib (136) <ADE3A41C-F815-39DE-A978-1B0EE456167B> /usr/lib/liblangid.dylib
    0x7fff29225000 -     0x7fff292c9fff  com.apple.CoreNLP (1.0 - 245.2) <9B1C60E4-2B36-34A7-AF43-7EEC914FA1FE> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff292ca000 -     0x7fff292d0fff  com.apple.LinguisticData (1.0 - 399) <48C87E01-670A-336C-9D37-723E06BE422D> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff292d1000 -     0x7fff29979fff  libBNNS.dylib (288.100.5) <48BD7046-5DBD-3F3D-AD81-376AD24FA45D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff2997a000 -     0x7fff29b4cfff  libvDSP.dylib (760.100.3) <372AD8C6-F390-3257-A886-D3B545AAB98C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff29b4d000 -     0x7fff29b5efff  com.apple.CoreEmoji (1.0 - 128.4) <677784E7-E4E6-3405-AC53-DD66197C4821> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff29b5f000 -     0x7fff29b69fff  com.apple.IOMobileFramebuffer (343.0.0 - 343.0.0) <A57347A7-1354-3F54-B9EC-E5F83A200AAF> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/Versions/A/IOMobileFramebuffer
    0x7fff29b6a000 -     0x7fff29c3cfff  com.apple.framework.CoreWLAN (16.0 - 1657) <42166AAE-D9EF-3EE6-A0F3-8B3E320BB39E> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff29c3d000 -     0x7fff29e3efff  com.apple.CoreUtils (6.6 - 660.37) <D3F3801B-EC48-3C0B-9438-0C12C4A0BA87> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff29e3f000 -     0x7fff29e61fff  com.apple.MobileKeyBag (2.0 - 1.0) <1FCEE156-0810-3425-88FC-E7EA6B38ACA7> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff29e62000 -     0x7fff29e72fff  com.apple.AssertionServices (1.0 - 505.100.8) <E691B254-0792-348B-BC13-2B1A490174C4> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff29e73000 -     0x7fff29efefff  com.apple.securityfoundation (6.0 - 55240.40.4) <AD930CCB-A3F5-3C2C-A2CD-9963A63560F5> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff29eff000 -     0x7fff29f08fff  com.apple.coreservices.BackgroundTaskManagement (1.0 - 104) <4B88024D-62DB-3E5D-BCA2-076663214608> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff29f09000 -     0x7fff29f0dfff  com.apple.xpc.ServiceManagement (1.0 - 1) <7E760B22-944C-387A-903F-C9184CE788B9> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff29f0e000 -     0x7fff29f10fff  libquarantine.dylib (119.40.2) <4611645F-5817-3A80-8382-2DB03A8C0141> /usr/lib/system/libquarantine.dylib
    0x7fff29f11000 -     0x7fff29f1cfff  libCheckFix.dylib (31) <33CE141E-48F5-3974-BD63-1F63558BB452> /usr/lib/libCheckFix.dylib
    0x7fff29f1d000 -     0x7fff29f34fff  libcoretls.dylib (169.100.1) <68726723-2EA1-3007-89ED-F66725A6AA7E> /usr/lib/libcoretls.dylib
    0x7fff29f35000 -     0x7fff29f45fff  libbsm.0.dylib (68.40.1) <77DF90DF-D5C2-3178-AAA7-96FC6D9F2312> /usr/lib/libbsm.0.dylib
    0x7fff29f46000 -     0x7fff29f8ffff  libmecab.dylib (929.10) <48F1EC4F-7D85-347F-B20C-7225AF2499A4> /usr/lib/libmecab.dylib
    0x7fff29f90000 -     0x7fff29f95fff  libgermantok.dylib (24) <171A100F-C862-3CA2-A308-5AA9EF24B690> /usr/lib/libgermantok.dylib
    0x7fff29f96000 -     0x7fff29fabfff  libLinearAlgebra.dylib (1336.120.1) <09738E52-FA24-3239-895D-F762C920F03C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff29fac000 -     0x7fff2a1cafff  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <C515FA90-1022-308E-A513-0EA9831FE712> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff2a1cb000 -     0x7fff2a21afff  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <1C3D9332-2C1D-3B52-A679-35BC37A3E8F0> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff2a21b000 -     0x7fff2a37cfff  com.apple.MLCompute (1.0 - 1) <0B7ADB41-62BE-32EE-821A-BB7141DE8B42> /System/Library/Frameworks/MLCompute.framework/Versions/A/MLCompute
    0x7fff2a37d000 -     0x7fff2a3b3fff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <D5B2AEEE-3973-35A5-9FF9-1C7C031B7125> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff2a3b4000 -     0x7fff2a40afff  com.apple.MetalPerformanceShaders.MPSNDArray (1.0 - 1) <0E99566D-A21A-304F-AF1A-A9530AED8A92> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray
    0x7fff2a40b000 -     0x7fff2a49bfff  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <1C395A17-2F98-35A5-B768-F22A714100D0> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff2a49c000 -     0x7fff2a4abfff  com.apple.AppleFSCompression (125 - 1.0) <6BD3FF9C-BCEE-3AB9-AC52-71A75D1C54AD> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff2a4ac000 -     0x7fff2a4b8fff  libbz2.1.0.dylib (44) <CA69420A-25E7-344C-852F-808F09AD43D0> /usr/lib/libbz2.1.0.dylib
    0x7fff2a4b9000 -     0x7fff2a4bdfff  libsystem_coreservices.dylib (127.1) <1E2DA16B-D528-3D43-86C2-2BB9127954A0> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a4be000 -     0x7fff2a4ebfff  com.apple.CoreServices.OSServices (1122.38 - 1122.38) <D02BE0AC-0544-3D1F-9E79-37715E231214> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff2a4ec000 -     0x7fff2a61bfff  com.apple.AuthKit (1.0 - 1) <C35AA029-1F96-3F5F-B71C-EF55E59F8F0D> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff2a6ba000 -     0x7fff2a6ccfff  libz.1.dylib (76) <C1E6CE87-167E-39EC-8B8F-2C3213A0208E> /usr/lib/libz.1.dylib
    0x7fff2a6cd000 -     0x7fff2a714fff  libsystem_m.dylib (3186.100.3) <21949128-D4E6-3179-B248-41B05C1CE102> /usr/lib/system/libsystem_m.dylib
    0x7fff2a715000 -     0x7fff2a715fff  libcharset.1.dylib (59) <4B3453D8-277A-38D3-862D-28DF71F3E285> /usr/lib/libcharset.1.dylib
    0x7fff2a716000 -     0x7fff2a71bfff  libmacho.dylib (980) <3677B3B7-03E8-3804-B2FE-5640B18FE40E> /usr/lib/system/libmacho.dylib
    0x7fff2a71c000 -     0x7fff2a737fff  libkxld.dylib (7195.121.3) <A83BCE3F-35C1-34DD-B1C5-B4FDFB33B250> /usr/lib/system/libkxld.dylib
    0x7fff2a738000 -     0x7fff2a743fff  libcommonCrypto.dylib (60178.120.3) <BBA72D86-B9C1-3123-AE59-D629DE278695> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a744000 -     0x7fff2a74efff  libunwind.dylib (201) <3149D79A-911B-39ED-9C93-6C7E6B0860C7> /usr/lib/system/libunwind.dylib
    0x7fff2a74f000 -     0x7fff2a756fff  liboah.dylib (203.46) <0A17EAFC-15E9-37FE-8EE2-DE0F7F220AD8> /usr/lib/liboah.dylib
    0x7fff2a757000 -     0x7fff2a761fff  libcopyfile.dylib (173.40.2) <7304CA0D-E93C-367F-9BEE-AC56B873F06C> /usr/lib/system/libcopyfile.dylib
    0x7fff2a762000 -     0x7fff2a769fff  libcompiler_rt.dylib (102.2) <0DB1902E-C79C-3E26-BE51-F70960ECF0B9> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a76a000 -     0x7fff2a76cfff  libsystem_collections.dylib (1439.100.3) <E180C04A-9CFB-3C8E-9C2B-978D23A99F2A> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a76d000 -     0x7fff2a76ffff  libsystem_secinit.dylib (87.60.1) <8C33D323-C11C-34CB-9295-4D7C98B8AFD6> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a770000 -     0x7fff2a772fff  libremovefile.dylib (49.120.1) <6DEAEEC9-2A65-3C7B-A9CE-23245772FD07> /usr/lib/system/libremovefile.dylib
    0x7fff2a773000 -     0x7fff2a773fff  libkeymgr.dylib (31) <FD167835-3829-3FFD-B13E-D18113E271AB> /usr/lib/system/libkeymgr.dylib
    0x7fff2a774000 -     0x7fff2a77bfff  libsystem_dnssd.dylib (1310.120.71) <7BB607FE-EF79-3144-8BD0-A66792FF1443> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a77c000 -     0x7fff2a781fff  libcache.dylib (83) <8B201058-2C34-3C12-9A7A-898CB0AAD150> /usr/lib/system/libcache.dylib
    0x7fff2a782000 -     0x7fff2a783fff  libSystem.B.dylib (1292.120.1) <A8309074-31CC-31F0-A143-81DF019F7A86> /usr/lib/libSystem.B.dylib
    0x7fff2a784000 -     0x7fff2a787fff  libfakelink.dylib (3) <CF7D19AF-D162-369D-9501-0BEAC4D1188E> /usr/lib/libfakelink.dylib
    0x7fff2a788000 -     0x7fff2a788fff  com.apple.SoftLinking (1.0 - 1) <6C04D3E0-BFE0-32E2-A098-46D726F9B429> /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking
    0x7fff2a789000 -     0x7fff2a7c0fff  libpcap.A.dylib (98.100.3) <87B9769E-D88E-37F9-BB83-B327527AE79C> /usr/lib/libpcap.A.dylib
    0x7fff2a7c1000 -     0x7fff2a8b1fff  libiconv.2.dylib (59) <B9FD3BC7-6001-3E60-A7FB-CE8AAE07C805> /usr/lib/libiconv.2.dylib
    0x7fff2a8b2000 -     0x7fff2a8c3fff  libcmph.dylib (8) <AE1C3A87-5C44-3833-9DE1-31062A878138> /usr/lib/libcmph.dylib
    0x7fff2a8c4000 -     0x7fff2a935fff  libarchive.2.dylib (83.100.2) <5DF98631-FBAC-3F17-B4D1-0115CE6C009B> /usr/lib/libarchive.2.dylib
    0x7fff2a936000 -     0x7fff2a99dfff  com.apple.SearchKit (1.4.1 - 1.4.1) <FBAB58C4-1B62-39E8-9241-93966CC2C9C0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff2a99e000 -     0x7fff2a99ffff  libThaiTokenizer.dylib (3) <1D735582-F932-3279-9F47-D10EAD1CA9A2> /usr/lib/libThaiTokenizer.dylib
    0x7fff2a9a0000 -     0x7fff2a9c2fff  com.apple.applesauce (1.0 - 16.28) <F07DA929-24FA-36D3-A356-05C9565AC397> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff2a9c3000 -     0x7fff2a9dafff  libapple_nghttp2.dylib (1.41) <303C40AC-4212-3B20-ABF6-91F46A79B78B> /usr/lib/libapple_nghttp2.dylib
    0x7fff2a9db000 -     0x7fff2a9f1fff  libSparseBLAS.dylib (1336.120.1) <3C4D290C-13A4-3A3D-B7C9-3BA0A4C9C7A5> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff2a9f2000 -     0x7fff2a9f3fff  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <9D78B798-7218-3327-8E50-CF321EDB22B1> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff2a9f4000 -     0x7fff2a9f8fff  libpam.2.dylib (28.40.1) <A04A5DD4-34DE-3BFB-BB17-BD66F7FBA1B6> /usr/lib/libpam.2.dylib
    0x7fff2a9f9000 -     0x7fff2aa18fff  libcompression.dylib (96.120.1) <591F0E34-3C41-3D94-98BA-9BB50E608787> /usr/lib/libcompression.dylib
    0x7fff2aa19000 -     0x7fff2aa1efff  libQuadrature.dylib (7) <FD523210-15BE-3EE7-B2E2-892A7E198542> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff2aa1f000 -     0x7fff2adbcfff  libLAPACK.dylib (1336.120.1) <3F036666-341C-3570-8136-CDF170C02DE7> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff2adbd000 -     0x7fff2ae0cfff  com.apple.DictionaryServices (1.2 - 341) <3EC1918E-0345-3EC6-BAE0-04B94A0B6809> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff2ae0d000 -     0x7fff2ae25fff  liblzma.5.dylib (16) <10B7343A-0322-3A1F-B6AE-06FC709F1BDE> /usr/lib/liblzma.5.dylib
    0x7fff2ae26000 -     0x7fff2ae27fff  libcoretls_cfhelpers.dylib (169.100.1) <BACFE067-CAAB-3906-AAE5-A5E78CD22C6D> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff2ae28000 -     0x7fff2af23fff  com.apple.APFS (1677.120.9 - 1677.120.9) <599AAB82-F105-3ACC-BBFA-2D3D276A312C> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff2af24000 -     0x7fff2af31fff  libxar.1.dylib (452) <C5B63994-6F92-395D-9431-1574D6E1D89F> /usr/lib/libxar.1.dylib
    0x7fff2af32000 -     0x7fff2af35fff  libutil.dylib (58.40.2) <4D8FD41B-89A5-31DA-BB0E-7F13C3B1652F> /usr/lib/libutil.dylib
    0x7fff2af36000 -     0x7fff2af5efff  libxslt.1.dylib (17.4) <CADFABB2-F66B-39FF-B43A-17315815F664> /usr/lib/libxslt.1.dylib
    0x7fff2af5f000 -     0x7fff2af69fff  libChineseTokenizer.dylib (37.1) <44E1A716-E405-3E54-874F-C5011146B318> /usr/lib/libChineseTokenizer.dylib
    0x7fff2af6a000 -     0x7fff2b027fff  libvMisc.dylib (760.100.3) <E92C2BF3-02A5-31D1-BF6A-56BBA624CA90> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff2b028000 -     0x7fff2b0bffff  libate.dylib (3.0.6) <C73DF462-D92F-366F-ADBE-B140698DEBAF> /usr/lib/libate.dylib
    0x7fff2b0c0000 -     0x7fff2b0c7fff  libIOReport.dylib (64.100.1) <E7BCECCB-2F51-3A07-9C56-4EF4AFD59C80> /usr/lib/libIOReport.dylib
    0x7fff2b1c9000 -     0x7fff2b1d0fff  libMatch.1.dylib (38) <121C98B5-D188-3E02-890D-F4F2CD91D2F2> /usr/lib/libMatch.1.dylib
    0x7fff2b1d1000 -     0x7fff2b25cfff  libCoreStorage.dylib (554) <3888A24D-7E72-3B58-A252-85373AFF3CE4> /usr/lib/libCoreStorage.dylib
    0x7fff2b25d000 -     0x7fff2b2b0fff  com.apple.AppleVAFramework (6.1.3 - 6.1.3) <D39DBE46-4BEB-316F-BAFA-8E2B03BED772> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff2b2b1000 -     0x7fff2b2c9fff  libexpat.1.dylib (26) <C0213844-67CA-38E7-A586-456A645E0BD0> /usr/lib/libexpat.1.dylib
    0x7fff2b2ca000 -     0x7fff2b2d3fff  libheimdal-asn1.dylib (597.121.1) <493CC99B-8939-3F7E-852C-9AB59B0DDC11> /usr/lib/libheimdal-asn1.dylib
    0x7fff2b2d4000 -     0x7fff2b2e8fff  com.apple.IconFoundation (479.4 - 479.4) <C0C5765F-6A1F-3D89-9AEE-5D49520CAAFD> /System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/IconFoundation
    0x7fff2b2e9000 -     0x7fff2b355fff  com.apple.IconServices (479.4 - 479.4) <8D31CC1A-C609-30EC-BCC3-251F7E4CDC10> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff2b356000 -     0x7fff2b3f4fff  com.apple.MediaExperience (1.0 - 1) <29CF7489-BA27-3789-95A2-F94CC6F09E7A> /System/Library/PrivateFrameworks/MediaExperience.framework/Versions/A/MediaExperience
    0x7fff2b3f5000 -     0x7fff2b41dfff  com.apple.persistentconnection (1.0 - 1.0) <5E4A9EC5-2E54-3EFF-A330-52C0D42B26AA> /System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection
    0x7fff2b41e000 -     0x7fff2b42cfff  com.apple.GraphVisualizer (1.0 - 100.1) <FFB7E9D0-F1D6-38E9-8BAD-759C3BFEE379> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff2b42d000 -     0x7fff2b848fff  com.apple.vision.FaceCore (4.3.2 - 4.3.2) <5A226A22-20F0-3196-915F-5DF94E1B3070> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff2b849000 -     0x7fff2b890fff  com.apple.OTSVG (1.0 - 677.5.0.5) <2E8C5AAB-E14B-3FC4-8872-332690419934> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff2b891000 -     0x7fff2b897fff  com.apple.xpc.AppServerSupport (1.0 - 2038.120.1) <256FB87D-3DD1-3B42-B095-B2E5FC3A755B> /System/Library/PrivateFrameworks/AppServerSupport.framework/Versions/A/AppServerSupport
    0x7fff2b898000 -     0x7fff2b8aafff  libhvf.dylib (1.0 - $[CURRENT_PROJECT_VERSION]) <C97DAB60-EA72-3822-A5F7-AF29C05DC1DD> /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
    0x7fff2b8ab000 -     0x7fff2b8adfff  libspindump.dylib (295.2) <63167B4A-D7D5-3146-86B6-988FC0AD4F14> /usr/lib/libspindump.dylib
    0x7fff2b8ae000 -     0x7fff2b96efff  com.apple.Heimdal (4.0 - 2.0) <B7D2D628-4503-3229-BFB4-FF60066104C1> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff2b96f000 -     0x7fff2b989fff  com.apple.login (3.0 - 3.0) <5D551803-8EF3-3F1F-9329-B35D3E017D25> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff2bb0e000 -     0x7fff2bb4afff  com.apple.bom (14.0 - 235) <B6D5DB5C-7E5B-3D1A-993B-06EDA9728BD9> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff2bb4b000 -     0x7fff2bb94fff  com.apple.AppleJPEG (1.0 - 1) <BE3058DB-0D49-3331-87A7-36D4651F143B> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff2bb95000 -     0x7fff2bc74fff  libJP2.dylib (2130.5.4) <E1F1DA3E-2EC4-3AC9-8171-E4777A9F5DBD> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff2bc75000 -     0x7fff2bc78fff  com.apple.WatchdogClient.framework (1.0 - 98.120.2) <DE7F64ED-82D2-325D-A031-0E805D52514C> /System/Library/PrivateFrameworks/WatchdogClient.framework/Versions/A/WatchdogClient
    0x7fff2bc79000 -     0x7fff2bcaffff  com.apple.MultitouchSupport.framework (4440.3 - 4440.3) <C22A0497-19D3-3365-8F59-9190C510F4BE> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff2bcb0000 -     0x7fff2be0efff  com.apple.VideoToolbox (1.0 - 2775.22) <88A013B6-FAB1-3BF9-A5C0-A92D8951E9E3> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff2be0f000 -     0x7fff2be42fff  libAudioToolboxUtility.dylib (1181.68) <2AF3BF70-DCEC-3884-A75A-DDEF1F304964> /usr/lib/libAudioToolboxUtility.dylib
    0x7fff2be43000 -     0x7fff2be69fff  libPng.dylib (2130.5.4) <3D6AEF53-5D8E-3F8B-B80E-71D848BFD35F> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff2be6a000 -     0x7fff2bec9fff  libTIFF.dylib (2130.5.4) <F4B52A0F-2EF6-30BE-9870-CD2E8B5C3318> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff2beca000 -     0x7fff2bee6fff  com.apple.IOPresentment (58 - 37) <994E2AE6-D25E-32D5-9ABA-5A1979A659FE> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff2bee7000 -     0x7fff2beeefff  com.apple.GPUWrangler (6.3.3 - 6.3.3) <768299B7-C4B5-307D-A413-52DA0C269A9D> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff2beef000 -     0x7fff2bef2fff  libRadiance.dylib (2130.5.4) <5C83C72F-9F7B-341D-ADD7-DA12A728C9EA> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff2bef3000 -     0x7fff2bef8fff  com.apple.DSExternalDisplay (3.1 - 380) <AA11B104-262F-33B2-8564-EF47D24AC2B6> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff2bef9000 -     0x7fff2bf1dfff  libJPEG.dylib (2130.5.4) <70213D93-137E-39CE-82C9-BC238226AC05> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff2bf1e000 -     0x7fff2bf4dfff  com.apple.ATSUI (1.0 - 1) <63C289D7-9FD8-370D-9DFB-9C2B50E7978A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/ATSUI
    0x7fff2bf4e000 -     0x7fff2bf52fff  libGIF.dylib (2130.5.4) <961F6A97-AF22-3A45-BDCF-A425C23CA01A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff2bf53000 -     0x7fff2bf5cfff  com.apple.CMCaptureCore (1.0 - 82.6) <694884AA-070C-3EE5-B86C-F09ABB93A7D7> /System/Library/PrivateFrameworks/CMCaptureCore.framework/Versions/A/CMCaptureCore
    0x7fff2bf5d000 -     0x7fff2bfa4fff  com.apple.print.framework.PrintCore (16.1 - 531.1) <9D0760A9-DAE8-3BB5-AE31-4D945BA39D48> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff2bfa5000 -     0x7fff2c072fff  com.apple.TextureIO (3.10.9 - 3.10.9) <B68C877B-2BE2-3338-AACA-52DDD955017A> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff2c073000 -     0x7fff2c07bfff  com.apple.InternationalSupport (1.0 - 61.1) <0C4AFFAF-D59F-3B3E-A433-CE03BDE567A8> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff2c07c000 -     0x7fff2c0f6fff  com.apple.datadetectorscore (8.0 - 674) <2FC62BC9-F63C-30DB-BFEE-3CB8399D7F18> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff2c0f7000 -     0x7fff2c154fff  com.apple.UserActivity (439 - 439) <2C4D4B39-FA93-3ED5-8417-ACBE6C39BB92> /System/Library/PrivateFrameworks/UserActivity.framework/Versions/A/UserActivity
    0x7fff2c155000 -     0x7fff2c8effff  com.apple.MediaToolbox (1.0 - 2775.22) <F5CC3EEC-294B-3B88-BEF1-63BEF846EFF0> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff2cdc0000 -     0x7fff2cdf1fff  libSessionUtility.dylib (76.69) <143B9D4F-FDB1-3366-A20C-4B09A05FE862> /System/Library/PrivateFrameworks/AudioSession.framework/libSessionUtility.dylib
    0x7fff2cdf2000 -     0x7fff2cf26fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <1ABFDEA2-FB20-3E05-B4CC-84A2A796D089> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2cf27000 -     0x7fff2cf8cfff  com.apple.audio.AudioSession (1.0 - 76.69) <8D52DAFF-EBE7-3631-A645-E5CD509591A0> /System/Library/PrivateFrameworks/AudioSession.framework/Versions/A/AudioSession
    0x7fff2cf8d000 -     0x7fff2cf9ffff  libAudioStatistics.dylib (27.64) <0EF059FC-B386-3595-8BB5-57F0CADAA75F> /usr/lib/libAudioStatistics.dylib
    0x7fff2cfa0000 -     0x7fff2cfaffff  com.apple.speech.synthesis.framework (9.0.65 - 9.0.65) <4E88057A-948F-335D-9675-AAEC73F7DE6A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff2cfb0000 -     0x7fff2d01cfff  com.apple.ApplicationServices.ATS (377 - 516) <9DFEBC18-3BA6-3588-A5C5-6D974DF284A2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff2d01d000 -     0x7fff2d035fff  libresolv.9.dylib (68) <0E0E7298-2781-3D72-B40F-5FF7DE7DF068> /usr/lib/libresolv.9.dylib
    0x7fff2d036000 -     0x7fff2d049fff  libsasl2.2.dylib (214) <8A235B0C-CE89-3C11-8329-AF081227BB92> /usr/lib/libsasl2.2.dylib
    0x7fff2d168000 -     0x7fff2d247fff  libSMC.dylib (20) <7B4581C7-3E3F-33F7-AC74-BFC57A2991C4> /usr/lib/libSMC.dylib
    0x7fff2d248000 -     0x7fff2d2a7fff  libcups.2.dylib (494.1) <C96214CD-19F2-334A-95A0-25BA714D984A> /usr/lib/libcups.2.dylib
    0x7fff2d2a8000 -     0x7fff2d2b7fff  com.apple.LangAnalysis (1.7.0 - 254) <C53922F5-BD54-3594-9DCF-DF6D0379B40D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff2d2b8000 -     0x7fff2d2c2fff  com.apple.NetAuth (6.2 - 6.2) <32C039EF-D063-3F2B-B4AC-3103593A7D4E> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff2d2c3000 -     0x7fff2d2cafff  com.apple.ColorSyncLegacy (4.13.0 - 1) <6B94034B-8D84-3700-96D3-7A3208231BE9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff2d2cb000 -     0x7fff2d2d6fff  com.apple.QD (4.0 - 416) <AA06F3E8-FC88-3501-B05C-F2D0C4F56272> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff2d2d7000 -     0x7fff2d92bfff  com.apple.audio.AudioResourceArbitration (1.0 - 1) <21EB0A40-BA39-3423-AA4F-2E2A771157C1> /System/Library/PrivateFrameworks/AudioResourceArbitration.framework/Versions/A/AudioResourceArbitration
    0x7fff2d92c000 -     0x7fff2d937fff  com.apple.perfdata (1.0 - 67.40.1) <9D1542E2-52D5-3372-8F2B-B71E27E8050B> /System/Library/PrivateFrameworks/perfdata.framework/Versions/A/perfdata
    0x7fff2d938000 -     0x7fff2d946fff  libperfcheck.dylib (41) <AE0793DA-378F-343E-82AC-EEFBE0FF1818> /usr/lib/libperfcheck.dylib
    0x7fff2d947000 -     0x7fff2d956fff  com.apple.Kerberos (3.0 - 1) <6D0BA11B-3659-36F0-983E-5D0E51B25912> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff2d957000 -     0x7fff2d9a7fff  com.apple.GSS (4.0 - 2.0) <398B2978-DB62-3D24-A5DA-36599C401D7F> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff2d9a8000 -     0x7fff2d9b8fff  com.apple.CommonAuth (4.0 - 2.0) <A48CDBF5-8251-35AF-90F8-6FD9D64DA2D8> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff2d9b9000 -     0x7fff2d9e0fff  com.apple.MobileAssets (1.0 - 659.100.21) <4D326D1D-8AF7-3D30-841A-E7D0E549B146> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff2da0e000 -     0x7fff2da2dfff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <8493160A-57F2-37E2-8482-FE1619630B59> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff2da2e000 -     0x7fff2da36fff  com.apple.CorePhoneNumbers (1.0 - 1) <514729CE-5C41-3B60-888B-C7267C51B11F> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff2db89000 -     0x7fff2db89fff  liblaunch.dylib (2038.120.1) <FB6430FC-AACB-3AFF-8763-4C5AFABEF40E> /usr/lib/system/liblaunch.dylib
    0x7fff2e36b000 -     0x7fff2e4b6fff  com.apple.Sharing (1622.1 - 1622.1) <B931F6D8-4831-34ED-A909-BEB824ADF533> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff2e4b7000 -     0x7fff2e5d8fff  com.apple.Bluetooth (8.0.5 - 8.0.5d7) <7630620F-575C-37A6-ACAA-3B9443127E88> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff2e5f2000 -     0x7fff2e64bfff  com.apple.ProtectedCloudStorage (1.0 - 1) <56DAAA40-66D4-3551-B196-B39604874CAA> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fff2fdab000 -     0x7fff2fdd2fff  com.apple.RemoteViewServices (2.0 - 163) <2D91746F-1F8B-3D03-BED1-C1BD7FA14453> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff2fdd3000 -     0x7fff2fde2fff  com.apple.SpeechRecognitionCore (6.1.24 - 6.1.24) <4FD3C300-7679-3E30-BC40-5DC933BC287E> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff2fde3000 -     0x7fff2fdeafff  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <F2C2E4FC-0EE0-38CC-AC0F-8F412A2859EE> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff30018000 -     0x7fff30018fff  libsystem_product_info_filter.dylib (8.40.1) <D5194AB1-61C4-3C8D-9E3C-C65702BAB859> /usr/lib/system/libsystem_product_info_filter.dylib
    0x7fff300f0000 -     0x7fff300f0fff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <E0B5CB04-F282-3BF0-8D14-BE6E3ED7C0A2> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff30116000 -     0x7fff30116fff  com.apple.CoreServices (1122.38 - 1122.38) <FEC6CD87-0909-3554-B8F5-CE65A5BB032C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff302d2000 -     0x7fff302d2fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <2BCB5475-FDEF-379A-BB0E-B1A3AA7F5B83> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff30313000 -     0x7fff3031efff  com.apple.MediaAccessibility (1.0 - 130) <F8E31637-2B5F-3D89-94FA-BD4AF8A46BD6> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff3031f000 -     0x7fff3033efff  com.apple.networking.AlgosScoreFramework (1.0 - 1) <C14EC551-82CD-3A04-91F3-C35D48B5B583> /System/Library/PrivateFrameworks/AlgosScoreFramework.framework/Versions/A/AlgosScoreFramework
    0x7fff3033f000 -     0x7fff30343fff  com.apple.AppleSRP (5.0 - 1) <F9D14131-8FEA-3BBF-902E-16754ABE537F> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
    0x7fff30344000 -     0x7fff3034ffff  com.apple.frameworks.CoreDaemon (1.3 - 1.3) <36002664-194B-3D03-8EFC-94AA3857B08B> /System/Library/PrivateFrameworks/CoreDaemon.framework/Versions/B/CoreDaemon
    0x7fff30b14000 -     0x7fff30b79fff  com.apple.CoreBluetooth (1.0 - 1) <AB95AA98-5CDC-3D4D-8478-C6595447837F> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff30b7a000 -     0x7fff30b83fff  com.apple.SymptomDiagnosticReporter (1.0 - 79.120.1) <99674A3B-7319-30F1-922E-D665D01794AF> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff30b97000 -     0x7fff30ba3fff  com.apple.AppleIDAuthSupport (1.0 - 1) <079E30CC-40B7-3363-9A41-F9A0DE9ED742> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff30ba4000 -     0x7fff30c4cfff  com.apple.DiscRecording (9.0.3 - 9030.4.5) <55DD9802-821D-35F6-B21B-C96371FE46B4> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff30c4d000 -     0x7fff30c80fff  com.apple.MediaKit (16 - 927.40.2) <72F9BA2E-AF51-3E05-8DE4-00377CC79609> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff30c81000 -     0x7fff30d6cfff  com.apple.DiskManagement (14.0 - 1733.100.4) <6EAC9935-9B5A-3758-92D4-9E13CF570D3A> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fff30d6d000 -     0x7fff31127fff  com.apple.CoreAUC (326.2.0 - 326.2.0) <A03BBCB7-69FA-3E37-AD91-734771D91045> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff31128000 -     0x7fff3112bfff  com.apple.Mangrove (1.0 - 25) <06E20B3A-83F6-36A3-96B8-9185D1B0A42D> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff3112c000 -     0x7fff31159fff  com.apple.CoreAVCHD (6.1.0 - 6100.4.1) <B7888146-5DE1-306C-8C9C-E98E763E3A4E> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff3115a000 -     0x7fff312a9fff  com.apple.FileProvider (348.8 - 348.8) <34DFD3C5-B489-3A7A-9EC2-3A1E2970F74D> /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff312aa000 -     0x7fff312ccfff  com.apple.GenerationalStorage (2.0 - 323) <AF8A2D39-41B5-3229-B780-86622DB977FC> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff31b16000 -     0x7fff31b55fff  com.apple.AppleVPAFramework (3.26.1 - 3.26.1) <32F14A37-1FAB-3216-B3FD-D1FA9E4790DC> /System/Library/PrivateFrameworks/AppleVPA.framework/Versions/A/AppleVPA
    0x7fff31c08000 -     0x7fff31c43fff  com.apple.DebugSymbols (195.1 - 195.1) <A8313A86-04C7-37DC-A5D7-FF54EE39BC70> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff31c44000 -     0x7fff31cf9fff  com.apple.CoreSymbolication (12.5 - 64544.69.1) <8D4E5AA8-8C09-31A7-AABE-AA9421781821> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff32bec000 -     0x7fff32c4ffff  com.apple.framework.Apple80211 (17.0 - 1728) <6C1C9532-AD79-3E68-BFBB-2279AC8EA776> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff32c50000 -     0x7fff32da1fff  com.apple.CoreWiFi (3.0 - 341) <E1A3027C-0657-3609-8F5C-D89BF6B4B422> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff32dbd000 -     0x7fff32df4fff  com.apple.LDAPFramework (2.4.28 - 194.5) <DDC1A94A-3537-3980-904B-31C54DA385C9> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fff32df5000 -     0x7fff32df6fff  com.apple.TrustEvaluationAgent (2.0 - 35) <736DE13E-CC75-3D3A-BE5B-AF75CC241E0B> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff32df7000 -     0x7fff32efcfff  libcrypto.44.dylib (56.60.2) <777B260D-CD90-3AE2-986E-2E4D021E6ACC> /usr/lib/libcrypto.44.dylib
    0x7fff32efd000 -     0x7fff32f2afff  libssl.46.dylib (56.60.2) <F2AE005F-3974-38D1-AA71-26201D27031F> /usr/lib/libssl.46.dylib
    0x7fff3307f000 -     0x7fff33082fff  com.apple.help (1.3.8 - 71) <F8B97715-17C5-3789-8B89-5F08EFB70709> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff33083000 -     0x7fff3308afff  com.apple.EFILogin (2.0 - 2) <32EC4CD5-A6BD-31E9-BE52-BF79845F9EDB> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff3308b000 -     0x7fff33096fff  libcsfde.dylib (554) <D4C66851-FDFC-3B94-8B21-DCA76BDFE724> /usr/lib/libcsfde.dylib
    0x7fff33097000 -     0x7fff330fdfff  libcurl.4.dylib (121.100.3) <5701AB53-D57D-38AE-8E76-ADBC03205B84> /usr/lib/libcurl.4.dylib
    0x7fff332d5000 -     0x7fff332d5fff  com.apple.ApplicationServices (48 - 50) <374F91E8-9983-363E-B1E1-85CEB46A5D1E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff335ea000 -     0x7fff335eafff  libHeimdalProxy.dylib (79) <68F67BFE-F1E8-341C-A065-08954EF3F684> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
    0x7fff3369d000 -     0x7fff3369dfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <CD5DF240-D8F7-3349-88DC-423962E5A289> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff336c1000 -     0x7fff33704fff  com.apple.StreamingZip (1.0 - 1) <D5CEAC33-8D9C-3D74-9E5D-909F86441F4D> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff3466c000 -     0x7fff346bcfff  com.apple.ChunkingLibrary (334.1 - 334.1) <27ED7D22-A3D4-3161-A5DF-485711DB2F48> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff36539000 -     0x7fff3655cfff  com.apple.openscripting (1.7 - 190) <9EAC55CC-0ECC-3B41-BF97-53C32496C689> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff3655d000 -     0x7fff36560fff  com.apple.securityhi (9.0 - 55008) <56A728F6-162E-31DE-9C29-FB1BE44C6B89> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff36561000 -     0x7fff36564fff  com.apple.ink.framework (10.15 - 227) <65FAEF94-F18C-30E0-8129-952DE19A5FAF> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff36565000 -     0x7fff36568fff  com.apple.CommonPanels (1.2.6 - 101) <45DFDB05-1408-34B4-A2AD-5416C5176C26> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff36569000 -     0x7fff36570fff  com.apple.ImageCapture (1711.5.2 - 1711.5.2) <E3BCD3B4-4792-390D-890B-B7A860088A4C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff3caaa000 -     0x7fff3caadfff  com.apple.print.framework.Print (15 - 271) <5A0FE511-37C2-3065-9066-34F8F9EA23E5> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff3caae000 -     0x7fff3cab1fff  com.apple.Carbon (160 - 164) <967F26C3-8582-3A33-945F-DDA8F103B2E2> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3cd64000 -     0x7fff3cd83fff  com.apple.private.SystemPolicy (1.0 - 1) <CAB3E8CD-1F31-343F-ABC1-9448543F211F> /System/Library/PrivateFrameworks/SystemPolicy.framework/Versions/A/SystemPolicy
    0x7fff3d6be000 -     0x7fff3d6d0fff  libmis.dylib (274.120.2) <1DE29019-5ECB-3BE2-8492-2385ED241950> /usr/lib/libmis.dylib
    0x7fff3d6d1000 -     0x7fff3d6d4fff  com.apple.gpusw.GPURawCounter (20.3 - 12.0) <EBB93DE3-AFE7-34FE-A194-7DFC62FFB9AA> /System/Library/PrivateFrameworks/GPURawCounter.framework/Versions/A/GPURawCounter
    0x7fff40ef4000 -     0x7fff40efdfff  com.apple.IOAccelMemoryInfo (1.0 - 1) <0BBA14A6-C060-3759-9B5E-4EDFEABED297> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff41380000 -     0x7fff4139efff  libCGInterfaces.dylib (544.4) <02C89930-F64D-354E-8C18-F3DDB419DC8D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff43929000 -     0x7fff43b9cfff  com.apple.RawCamera.bundle (9.10.0 - 1450.3) <408A3DFB-B3D3-3C15-88BB-16076BDFC74B> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff516fa000 -     0x7fff51727fff  com.apple.HelpData (2.3 - 201) <3125FBF3-30B7-3237-B001-2692332FF681> /System/Library/PrivateFrameworks/HelpData.framework/Versions/A/HelpData
    0x7fff51728000 -     0x7fff51742fff  com.apple.shortcut (2.16 - 118) <1FD9ABCC-0B5B-37DC-9E6E-CC47C128DBB2> /System/Library/PrivateFrameworks/Shortcut.framework/Versions/A/Shortcut
    0x7fff5ddbd000 -     0x7fff5e24cfff  com.apple.driver.AppleIntelKBLGraphicsMTLDriver (16.4.5 - 16.0.4) <994BBF27-F4D5-3561-BC2E-FECC0C460C76> /System/Library/Extensions/AppleIntelKBLGraphicsMTLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsMTLDriver
    0x7fff69773000 -     0x7fff69777fff  libmetal_timestamp.dylib (31001.189) <89A82967-B14D-3109-B45E-34717156E60E> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/libmetal_timestamp.dylib
    0x7fff6bbbe000 -     0x7fff6bbc4fff  libCoreFSCache.dylib (200.9) <12A2A7E7-39F7-30A5-AC0B-E09947417D3E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff6bbc5000 -     0x7fff6bbc9fff  libCoreVMClient.dylib (200.9) <F8C4D017-075A-37B2-AE8D-8CEB5FE1BC9B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff6bbca000 -     0x7fff6bbd9fff  com.apple.opengl (18.5.9 - 18.5.9) <1422D0CA-C3E2-3309-8897-018E651CB74E> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff6bbda000 -     0x7fff6bbdcfff  libCVMSPluginSupport.dylib (18.5.9) <AC7D4088-7CA8-3A0B-9B55-08427083C382> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff6bbdd000 -     0x7fff6bbe5fff  libGFXShared.dylib (18.5.9) <76ABDB4A-3687-39E0-B8FB-125717742431> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff6bbe6000 -     0x7fff6bc19fff  libGLImage.dylib (18.5.9) <750C938A-9F4F-3BAD-8D3F-03EF619F28AD> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff6bc1a000 -     0x7fff6bc56fff  libGLU.dylib (18.5.9) <4A77F717-2BBC-3439-AE10-694E82C0A184> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff6bdeb000 -     0x7fff6bdf5fff  libGL.dylib (18.5.9) <95D5C72E-9352-39EC-83B1-6BB295A83462> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff6d235000 -     0x7fff6d28dfff  com.apple.opencl (4.6 - 4.6) <769BB23D-09E5-3A3A-B2EA-310157AA206D> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff6e337000 -     0x7fff6e33efff  com.apple.agl (3.3.4 - AGL-3.3.3) <23E38B10-2F27-3BB2-B78D-C28189C21601> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff77a33000 -     0x7fff77a3afff  libRosetta.dylib (203.46) <0A17EAFC-15E9-37FE-8EE2-DE0F7F220AD8> /usr/lib/libRosetta.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=761.2M resident=0K(0%) swapped_out_or_unallocated=761.2M(100%)
Writable regions: Total=1.7G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.7G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               640K        5 
Activity Tracing                   256K        1 
CG backing stores                 4032K        6 
CG image                           640K       16 
CG raster data                     352K        1 
CoreAnimation                      832K       12 
CoreGraphics                        12K        2 
CoreUI image data                 1864K       17 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.4G      135 
MALLOC guard page                   32K        6 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        5 
Stack                             10.0M        6 
VM_ALLOCATE                        412K       22 
VM_ALLOCATE (reserved)             256K        1         reserved VM address space (unallocated)
__DATA                            15.6M      359 
__DATA_CONST                      12.7M      190 
__DATA_DIRTY                       565K      100 
__FONT_DATA                          4K        1 
__LINKEDIT                       508.6M       44 
__OBJC_RO                         70.2M        1 
__OBJC_RW                         2480K        2 
__TEXT                           252.7M      357 
__UNICODE                          588K        1 
mapped file                      404.1M       39 
shared memory                      752K       15 
===========                     =======  ======= 
TOTAL                              3.0G     1347 
TOTAL, minus reserved VM space     2.7G     1347 

</details>

I actually think the second crash is a separate issue, because it is reproducable: I download the Gridcoin snapshot, it checks the SHA256 sum, and on step 3/4 where it cleans up, it crashes.

### PR DESCRIPTION
**Pull request by jamescowens**
This fixes the snapshot download for macOS and also makes other cleanups and adjustments.

Note that this draft PR uses a single additional worker thread for the heavyweight download/verification/unpack functions, with a "ping-pong" triggered workflow. Given that the actual cause of the crash was not due to the threading, I may revert back to the simpler workflow, invoking a separate worker thread in each step. -- Update nope. What I did is working very well, so I am going to leave it.

I went ahead and did progress updating for both the SHA256SUM verification and the blockchain data cleanup function, since they are pretty heavyweight and take a pretty long time on slower machines, so it is good to see actual progress, instead of going from 0 to 100 instantaneously.

I also changed the SnapshotStatus and SnapshotExtractStatus structs into thread safe classes with getters and setters because they are accessed by multiple threads.

This has been tested on macOS Catalina (10.15) and works well.

Closes #2208.

### CODE REVIEW

File: src/gridcoin/upgrade.cpp [hunk 1]
```diff
@@ -472,66 +701,73 @@ bool Upgrade::ExtractSnapshot()
...
-                    while ((uint64_t)sum != ZipStat.size)
+                    while ((uint64_t) sum < ZipStat.size)
                     {
+                        int64_t len = 0;
+                        char Buf[256*1024];
+
                         boost::this_thread::interruption_point();
 
-                        len = zip_fread(ZipFile, Buf, 1024*1024);
+                        len = zip_fread(ZipFile, &Buf, 256*1024);
```
Comment (jamescowens) [inline src/gridcoin/upgrade.cpp:762]: Believe it or not, this is the actual bug on the mac. It blows up on a 1M char buffer size. You have to lower it to 256*1024. I can't believe how long it took me to find this...

File: src/gridcoin/upgrade.cpp [hunk 2]
```diff
@@ -149,15 +142,17 @@ bool Upgrade::CheckForLatestUpdate(std::string& client_message_out, bool ui_dial
     }
     catch (std::exception& ex)
     {
-        LogPrintf("%s: Exception occurred checking client version against github version (%s)", __func__, ToString(ex.what()));
+        LogPrintf("%s: Exception occurred checking client version against github version (%s)",
```
Comment (barton2526) [inline src/gridcoin/upgrade.cpp]:
```suggestion
        LogPrintf("%s: Exception occurred checking client version against GitHub version (%s)",
```

File: src/gridcoin/upgrade.cpp [hunk 3]
```diff
@@ -149,15 +142,17 @@ bool Upgrade::CheckForLatestUpdate(std::string& client_message_out, bool ui_dial
...
         return false;
     }
 
     if (!NewVersion) return NewVersion;
 
     // New version was found
-    client_message_out = _("Local version: ") + strprintf("%d.%d.%d.%d", CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD) + "\r\n";
+    client_message_out = _("Local version: ") + strprintf("%d.%d.%d.%d", CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR,
+                                                          CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD) + "\r\n";
     client_message_out.append(_("Github version: ") + GithubReleaseData + "\r\n");
```
Comment (barton2526) [inline src/gridcoin/upgrade.cpp]: here too?

File: src/gridcoin/upgrade.cpp [hunk 4]
```diff
@@ -623,7 +874,9 @@ std::string Upgrade::ResetBlockchainMessages(ResetBlockchainMsg _msg)
             break;
         }
 
-        case UpdateAvailable: stream << _("Unable to download a snapshot, as the wallet has detected that a new mandatory version is available for install. The mandatory upgrade must be installed before the snapshot can be downloaded and applied."); break;
+        case UpdateAvailable: stream << _("Unable to download a snapshot, as the wallet has detected that a new mandatory "
+                                          "version is available for install. The mandatory upgrade must be installed before "
+                                          "the snapshot can be downloaded and applied."); break;
         case GithubResponse: stream << _("Latest Version github data response:"); break;
```
Comment (barton2526) [inline src/gridcoin/upgrade.cpp]: same as above

**Review by iFoggz — APPROVED** [review]
tACK 2caebc2
Osx + Ubuntu 21.04
