### PR TITLE
gui: Fix nomenclature

### LINKED ISSUE #2103: Renaming Suggestions
Various terminology in the wallet can be made better. Some of it is confusing, misleading, and or not correct anymore. Here are some suggestions of some renamings. Other names could be used instead of those suggested here 

- [x]  "Mined - POR" -> Mined Research Rewards or Mined With Research Rewards or even Mined - RR
- [x] "Proof of Research Difficulty" (in the debug console) -> Difficultly 
- [x] "Investor" -> Non-Cruncher
- [x]  "Beacon rain address" -> Beacon Associated Address or Beacon Address 
- [x] "Best answer" -> Top answer since best puts more of a value judgment there
~~- [ ] "Export" (under the File tab)  -> "Export Transaction Data"~~

### PR DESCRIPTION
**Pull request by jamescowens**
Partially addresses #2103. Let's get the four easy ones out of the way first. I will address the "investor" one in a separate PR.

### CODE REVIEW

**Review by iFoggz — COMMENTED** [review]
utACK -- nice clean up, nice to see some of the small stuff pushing through. :+1:

File: src/gridcoin/researcher.cpp [hunk 1]
```diff
@@ -664,7 +664,7 @@ AdvertiseBeaconResult GenerateBeaconKey(const Cpid& cpid)
     // help identify transactions in the GUI:
     //
     const std::string address_label = strprintf(
-        "Beacon Rain Address for CPID %s (at %" PRIu64 ")",
+        "Beacon Address for CPID %s (at %" PRIu64 ")",
```
Comment (cyrossignol) [inline src/gridcoin/researcher.cpp:667]: If we don't want to keep the word "rain", we should delete the comment above this line. I added "rain" because people were always confused by rain transactions that showed up as the beacon addresses. I saw several instances where people thought they received research rewards. The "rain" label helps to distinguish those transactions from stakes for new users and makes it easier for helpers to provide support for those questions since there is nothing that explicitly categorizes a transaction as rain. I've seen less confusion about the label now than before Fern, but maybe that's just me. 

The label also allows for a semi-relevant result if someone happens to search for "rain" in the transaction list.

Comment (jamescowens) [reply src/gridcoin/researcher.cpp:667]: I don't think we can win here. We have also received reports of people confused by the presence of Rain in the address field. It is more accurately the beacon address anyway, not just the address that rains are sent to.

Comment (cyrossignol) [reply src/gridcoin/researcher.cpp:667]: Yeah, it's a tough one. I think "rain" is a net positive, but I trust your judgement.

Comment (jamescowens) [reply src/gridcoin/researcher.cpp:667]: I changed the comment.

**Review by cyrossignol — APPROVED** [review]
